### ISSUE TITLE
Update Go to 1.14

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#1006]
Our CI is currently based on Go 1.13, and Go 1.14 has been out sufficiently long now that the update risk is low, currently 1.14.5 is available.

There's no need to alter our supported platforms statement because of this update:
https://golang.org/doc/go1.14#ports
https://github.com/brimsec/brim/wiki/Supported-Platforms

**Comment by mikesbrown** [comment]
I asked @alfred-landrum Do you want a "soft" upgrade to Go 1.14, for CI-*only*? Or do you want a "hard" upgrade, i.e., updating `go.mod`, `CONTRIBUTING.md`, etc.? The answer was hard.
