### ISSUE TITLE
AST transform for parallelizing flowgraphs (step 2)

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1034]
#1022 is the first step towards splitting a flowgraph for parallel execution. It handles the case of splitting at a decomposable aggregation that comes after stateless procs. 

This is a placeholder for more general splitting. I'll just provide a few examples of what could be done:

1. Splitting at `sort x`, with arbitrary input sortedness

`<stateless procs> ... | sort x | <other procs>` can be transformed into

```
(
  <stateless procs> ... | sort x;
  ...                                                  
  <stateless procs> ... | sort x
) 
| merge x | <other procs>
```
(where `merge x` means "merge in the order of field x").

2. Splitting with `head` and `tail`, with input sorted in x:

`<stateless procs> ... | head N | <stateless procs> | <other procs>` can be transformed into

```
(
  <stateless procs> ... | head N | <other procs>;
  ...                                                                                     
  <stateless procs> ... | head N | <other procs> 
) 
| merge x | head N | <other procs>
```
(this one seems less useful in practice given that for reasonable N, things should be fast without distribution... but tbd).

3. Undoubtedly more!

**Comment by alfred-landrum** [comment]
A comment on case 1 above: the merge of sorted streams can support a form of 'early release' of data, the same way the groupby code does (that @henridf wrote :) ). When we schedule the scanning of input partitions, we'll have the info needed to schedule them in sorted order. They may not finish perfectly in order, of course, but doing so could help reduce the amount of memory the merge needs on average.

**Comment by henridf** [comment]
The two suggestions from the issue description were done in #1022 and #1182 respectively.
