### ISSUE TITLE
Configurable merging

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1036]
#1022 will automatically create split flowgraphs that have a merge point. As described in that issue, in some cases, records can be read in arbitrary order at the merge point, while in other cases the merge point needs to read them in order of a configurable field.

This issue consists of adding support for either behaviors. Currently the merge proc is implicitly added during compilation rather than being represented in the AST; it is tbd whether that should remain the case. Maybe we can have an implicit "unordered merge", and an explicit "order on X merge" that is represented in the AST.

**Comment by alfred-landrum** [comment]
We'll need an "order on X merge" when we distribute queries without aggregations, to maintain the currently expected reverse timestamp order of query results.
