### ISSUE TITLE
investigate zar test failure involving windows rename

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#1043]
` Failed: "\"D:\\a\\brim\\brim\\node_modules\\zq\\dist\\zar\" index -R \"D:\\var\\tmp\\brimsec\\itest\\zar.test.js\\1\\data\\spaces\\sp_1f8xc4o5zhmqZSvNffMH53EPjab\" uid: rename D:\\var\\tmp\\brimsec\\itest\\zar.test.js\\1\\data\\spaces\\sp_1f8xc4o5zhmqZSvNffMH53EPjab\\.tmp-zar.json475034943 D:\\var\\tmp\\brimsec\\itest\\zar.test.js\\1\\data\\spaces\\sp_1f8xc4o5zhmqZSvNffMH53EPjab\\zar.json: Access is denied.`

See:
https://github.com/brimsec/brim/pull/940

https://github.com/brimsec/brim/runs/907699957

**Comment by alfred-landrum** [comment]
Fixed with https://github.com/brimsec/brim/pull/944 ; multiple processes were trying to update the metadata file.

**Comment by philrz** [comment]
We can't recall having seen this lately, so going off @alfred-landrum's comment above that we thought it had been fixed, closing.
