### ISSUE TITLE
zqd pcap post: delete cancel error message

### ISSUE THREAD

**Issue by mattnibs** [brimsec/zq#1100]
Steps to reproduce:
1. Start a pcap post (`zapi -s myspace pcappost -f /pcapfile`)- preferably some pcapfile large enough to take zeek sometime to churn through
2. Wait till the api starts returning stats on the ingest process (this means that pcap index is complete and zeek has started)
3. Issue a delete command on the space (`zapi rm myspace`)

Observe that the return error message is "zeek exited with error code: -1". The error code is probably because the cancel operation tells zeek to shutdown. We should be ignoring the zeek error code in this case and instead return an error message like "pcap post operation canceled".

**Comment by philrz** [comment]
Verified in commit `b7023d5` of `zqd` & `zapi`.

Repeating the original repro steps, now we see the improved error message:

```
$ zapi -s myspace pcappost -f ./all.pcap 
 11.9% 520.7MB/4.38GB
pcap post operation canceled
```

Thanks @mattnibs!
