### ISSUE TITLE
"truncated input" error on pcap slice operation

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#1117]
A Brim community user reported an issue where they were able to import a pcapng successfully into Brim but not able to extract any flows from it via the Packets button.

Suspecting a problem with the packet indexing/extraction, we debugged at the command line. Per a [Slack thread](https://brimsec.slack.com/archives/C010DR0HHMF/p1597642269030000), we baselined a "happy path" of functionality equivalent to what `zqd` normally does to extract packets. Using a known good sample [hello.pcapng.zip](https://github.com/brimsec/zq/files/5091162/hello.pcapng.zip), to build the packet index:

```
$ ./pcap index -r hello.pcapng -x hello.idx
```

To look at some sample packet timestamps in the pcapng:

```
$ ./pcap ts -r hello.pcapng 
1583768523.826851
1583768523.826857
1583768523.826968
...
```

To extract a "slice" by using some of those timestamps against the index:

```
$ ./pcap slice -x hello.idx -r hello.pcapng -from 1583768523.826851 -to 1583774873.620491 > tmp.pcapng
```

That resulting `tmp.pcapng` is similar to what the daemon should be creating behind the Brim app when you click on the Packets button in Brim, and this slice from the example `hello.pcapng` can, indeed, be opened in Wireshark.

The user completed the equivalent steps with their sample pcap and at the `pcap slice` step saw the failure message `truncated input: truncated input`.

The user's pcapng file unfortunately cannot be shared due to NDA issues. We may need to provide a debug build to gain further insight into why we're not able to work with this pcapng file.

While we're at it, we should better understand if it would have been possible to surface this error in the app, since going into CLI mode to debug is pretty painful. https://github.com/brimsec/brim/issues/1003 is already tracking the app's role in this, but I imagine the backend might have something to add here as well.

**Comment by mccanne** [comment]
Ok, the fix is to log a warning when there is extra junk at the end of a pcap-ng file but not throw an error.

We will also add a new protocol message so the client can receive warnings during a pcap post.

**Comment by mccanne** [comment]
The warnings extension has been put up as PR #1175

The final pcap-ng fix will come in a subsequent PR rebased to master once #1175 is merged.

**Comment by philrz** [comment]
Verified in Brim commit `d8b8f1e` talking to `zqd` commit `4444632`.

First I'll step back and give more detail on the repro. As described above and in the linked PR, we were able to reproduce the same symptom that the user saw by creating a pcapng with extra bytes in it ([bad.pcapng.zip](https://github.com/brimsec/zq/files/5139452/bad.pcapng.zip)). This pcapng does open in Wireshark, but it pops up an error message:

![image](https://user-images.githubusercontent.com/5934157/91509806-22807500-e890-11ea-9537-530f76b8b5d4.png)

In terms of what a user would see with this pcap in a repro in GA `pcap` tagged `v0.19.1`, the same error is returned that the user reported:

```
$ pcap index -r bad.pcapng -x bad.idx
truncated input
```

Likewise in GA Brim tagged `v0.15.1`, when that pcapng is dragged into the app, the same error message bubbles up into the UI.

![image](https://user-images.githubusercontent.com/5934157/91510028-af2b3300-e890-11ea-9ca6-93378152baeb.png)

The user had not reported seeing this message in Brim when they originally reported the issue. In their case the pcap appeared to import ok and it was only when trying to extract a particular flow that they saw the "Download Error: object Object" error (better surfacing of this error is being tracked separately in https://github.com/brimsec/brim/issues/1003). However, the user also explained that they're using a custom Zeek _and_ Lua in Wireshark, so this may help explain why their baseline experiences working with their pcapng were different. There's still an ongoing [Slack thread](https://brimsec.slack.com/archives/C010DR0HHMF/p1597642269030000) where we're continuing to understand that the best we can, given we don't have access to the original pcapng. Regardless, I'm happy to the report that the user _did_ perform an early test with the fix in the branch in the linked PR and said they were able to import & extract with their pcapng, so it seems the fix is effective for them as described below.

Now in Brim commit `d8b8f1e` talking to `zqd` commit `4444632`, as shown in the attached video, with the benefit of the fix we can drag the same pcapng into the app and it imports successfully, then I'm able to extract a flow from it into Wireshark.

[Verify.zip](https://github.com/brimsec/zq/files/5139505/Verify.zip)

As also noted in the PR, there's now a warning generated in the backend, but it's not yet surfaced in the app. A capture in Wireshark during the pcap import shows the exchange.

The request:

```
POST /space/sp_1ghs0BczuKhYsDXVbEwFXlnLMwg/pcap HTTP/1.1
Host: localhost:9867
Connection: keep-alive
Content-Length: 41
sec-ch-ua: 
Origin: file://
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Brim/0.15.1 Chrome/78.0.3904.130 Electron/7.3.2 Safari/537.36
Content-Type: text/plain;charset=UTF-8
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US

{"path":"/Users/phil/Desktop/bad.pcapng"}
```

The response:

```
Content-Type: application/ndjson
X-Request-Id: 16
Date: Fri, 28 Aug 2020 01:25:32 GMT
Transfer-Encoding: chunked

23
{"type":"TaskStart","task_id":2}



4c
{"type":"PcapPostWarning","warning":"pcap-ng has extra bytes at eof: 20"}



10f
{"type":"PcapPostStatus","start_time":{"sec":1598577932,"ns":887796000},"update_time":{"sec":1598577933,"ns":886545000},"pcap_total_size":12401,"pcap_read_size":12401,"snapshot_count":1,"span":{"ts":{"sec":1583768523,"ns":826851000},"dur":{"sec":6349,"ns":865915001}}}



1f
{"type":"TaskEnd","task_id":2}

0
```

The surfacing of this error into the app is being tracked separately via https://github.com/brimsec/brim/issues/1028.

Thanks @mccanne!
