### ISSUE TITLE
concurrency handling for unordered inputs

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#1159]
See discussion at https://github.com/brimsec/zq/pull/1145#discussion_r475112253 . If the input to a query doesn't have a known/declared order, how would we determine if we can concurrently execute some or all of the query?

**Comment by alfred-landrum** [comment]
After some discussion, we decided that for now we wouldn't try to optimize cases where the ordering of data is unknown, as that doesn't arise in Brim usage cases.

**Comment by henridf** [comment]
> we wouldn't try to optimize cases where the ordering of data is unknown

For anyone who might come across this issue in the future, it's worth noting that we still do optimize certain queries when inputs are unordered, such as aggregations, or queries with a sort. The query shapes that we can't optimize are those described here: https://github.com/brimsec/zq/blob/2742f1833298e6a19f77359504a47b4aeed61c0a/driver/compile.go#L552
