### ISSUE TITLE
reducer/compile and proc/compiler should be consistent

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1162]
This is a simply rename task.  @mccanne votes to change reducer/compile to reducer/compiler.

**Comment by henridf** [comment]
Now I think of it, another avenue might be to have a top-level compile/ directory with the contents of reducer/compiler and proc/compiler, as well as most/all of driver/compile.go (which has grown a lot recently).

**Comment by mccanne** [comment]
I just re-read @henridf and agree that a common top-level directory makes more sense so I'll close this PR and we'll leave the issue open.

**Comment by mccanne** [comment]
Oops, I mean to close the PR.

**Comment by mccanne** [comment]
For this task, we also should 

- move all expr compilation logic from package expr to compiler
- move filter compilation logic
- move bufferfilter compilation logic
- move rest of ast-dependent logic out of various proc constructors
