### ISSUE TITLE
iosrc.URI: Preserve file names with url encoded characters

### ISSUE THREAD

**Issue by mattnibs** [brimsec/zq#1196]
Steps to reproduce:

1. call iosrc.ParseURI on a file with url encoded characters `c:\data\file%20with%20spaces`
2. On the resultant uri, call Filepath()
3. Observe that the printed value is different than the file name `c:\data\file with spaces`

This will result in all parts of zq/zqd/zar that rely on iosrc.URI being unable to find the file name with url encoded characters in them.

This should be fixed so the actual file name is preserved.

**Comment by philrz** [comment]
Verified in Brim commit `73d51c1` talking to `zqd` commit `e322b38`.

To revisit the user-facing impact of the issue as it looked in Brim GA tagged `v0.16.0` talking to `zqd` GA tagged `v0.20.0`, the attached video shows what would happen if I dragged a pcap into the app from a directory on my Desktop called `My%Pcaps`:

![image](https://user-images.githubusercontent.com/5934157/92820378-bec17600-f37e-11ea-9ea6-fc2705a77cb2.png)

[Repro.zip](https://github.com/brimsec/zq/files/5205020/Repro.zip)

Now in Brim commit `73d51c1` talking to `zqd` commit `e322b38`, it's working:

![image](https://user-images.githubusercontent.com/5934157/92820507-e6184300-f37e-11ea-88f7-ed7b3efb9f72.png)

[Verify.zip](https://github.com/brimsec/zq/files/5205025/Verify.zip)

Thanks @alfred-landrum!
