### ISSUE TITLE
Deterministic ordered merge

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1215]
As noted in #1204:

> Ordered merge does not have sufficient information to sort stably: when multiple records with same sort field are present at different upstreams, it does not know what their original order (*) was.

We need to make ordered merge deterministic. Note "deterministic" and not "stable", because in a case such as multiple input files that overlap in the sort key, there is no stable ordering in the data. This ordering must be imposed externally.

**Comment by alfred-landrum** [comment]
In recent discussions, @henridf suggested if the sort field value is the same, we can compare the entire zcode.Bytes of the record, which has the desirable quality of not requiring any external information to be present to provide the ordering.
