### ISSUE TITLE
Search doesn't search records inside arrays

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1223]
(I noticed this while working on #1069)

```
$ cat input.tzng 
#0:record[r1:record[a:array[string]]]
0:[[[foo;]]]
#1:record[r1:array[record[r2:string]]]
1:[[[foo;]]]

$ zq -t "foo" input.tzng 
#0:record[r1:record[a:array[string]]]
0:[[[foo;]]]
```

Both records should match, but only the first one does. It looks like `(*fieldIter).Next()` needs to step into arrays.

**Comment by philrz** [comment]
@alfred-landrum noted that this likely touches the Boyer-Moore code, and there's at least one piece of unfinished business in that area, so we've added it to that Epic for consideration.

**Comment by philrz** [comment]
Verified in `zq` commit `702d877`. Revisiting the original repro steps, now both records match.

```
$ cat input.tzng 
#0:record[r1:record[a:array[string]]]
0:[[[foo;]]]
#1:record[r1:array[record[r2:string]]]
1:[[[foo;]]]

$ zq -version
Version: v0.22.0-73-g702d877

$ zq -t "foo" input.tzng
#0:record[r1:record[a:array[string]]]
0:[[[foo;]]]
#1:record[r1:array[record[r2:string]]]
1:[[[foo;]]]
```

Thanks @nwt!
