### ISSUE TITLE
Inconsistent search behavior on field names with unset values

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1224]
Another obscure issue I noticed while working on #1069. In this example, we run a search for `a` on a record with a field name matching that search. In this record, the value for the field is unset. The record matches the search.

```
$ cat input.tzng 
#0:record[a:string]
0:[-;]
$ zq -t "a" input.tzng 
#0:record[a:string]
0:[-;]
```

This is the same setup, except that the field `a` is a record. The value for `a` is again unset. The search does not match.  For consistency, both should match, or neither should match.

```
$ cat input.tzng 
#0:record[a:record[b:string]]
0:[-;]
$ zq -t "a" input.tzng 
```

**Comment by philrz** [comment]
@henridf: In terms of what should be the consistent behavior, we made a conscious decision some time ago that "bare" searches should match on field names. There's precedent here in other search tools with which users might be familiar, plus we've had good user experiences thus far to date with our "type the least, get the most" approach to bare searches. If you need more background on this hit me up on Slack can I can send you some of the detailed user conversations from back when we first made this decision.

**Comment by henridf** [comment]
Thanks @philrz. No need for more background 🙂

**Comment by philrz** [comment]
@alfred-landrum noted that this likely touches the Boyer-Moore code, and there's at least one piece of unfinished business in that area, so we've added it to that Epic for consideration.

**Comment by philrz** [comment]
Verified in `zq` commit `702d877`. The search now matches against the field name even when it's a record with an unset value.

```
$ cat input.tzng 
#0:record[a:record[b:string]]
0:[-;]

$ zq -version
Version: v0.22.0-73-g702d877

$ zq -t "a" input.tzng
#0:record[a:record[b:string]]
0:[-;]
```

Thanks @nwt!
