### ISSUE TITLE
"bad uvarint" with cut -c

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1226]
```
$ cat input.tzng 
#0:record[id:record[ip:ip],id2:record[ip:ip]]
  0:[-;[1.1.1.1;]]
$ zq -t "cut -c id" input.tzng 
bad uvarint: 0
```

This is due to `*fieldIter.Next()`trying to step into an unset record. That's easy to fix, but what `*fieldIter.Next()` should return here is less obvious, since it currently returns leaves only (bug #1223 notwithstanding).

**Comment by henridf** [comment]
(This was getting in the way of #1069 so I did it now).

**Comment by henridf** [comment]
(Actually it didn't get in the way of #1069 ... that was a mirage. But I did _find_ it while working on #1069 🤔 ).

**Comment by philrz** [comment]
Verified in `zq` commit `b2c8356`.

Just to take a quick step back, an example of a commit where I could repro this was `42103ef`.

```
$ /Applications/Brim.app/Contents/Resources/app/zdeps/zq -version
Version: 42103ef

$ /Applications/Brim.app/Contents/Resources/app/zdeps/zq -t "cut -c id" input.tzng 
bad uvarint: 0
```

Now with `zq` commit `b2c8356`:

```
$ zq -version
Version: v0.20.0-18-gb2c8356

$ zq -t "cut -c id" input.tzng 
#0:record[id2:record[ip:ip]]
0:[[1.1.1.1;]]
```

Thanks @henridf!
