### ISSUE TITLE
finish up zng beta spec & zq implementation

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1259]
Let's try to move the zng spec into "beta".  There are non-breaking additions and breaking changes.

## Non-breaking additions 

1. Implements bytes type. 
2. Add float32
3. Define enums more appropriately and implement and change zeek enums to zenum as string alias (the problem with zeek enums is you don't know the full set of enum symbols ahead of time, and they need to go in the typedef). Won't break any old zng but the zng will look different for zeek enums compared to the old zng.
4. Define and implement map type (aka table).  This could be good design brainstorm as there are clever ways we could build this on top of zng.Record and then the table could be a first class object in the zql runtime to do joins etc. loaded from external places or loaded from another query.
5. Relax the syntax for zng columns names.  We currently require conformance with JSON identifiers but even javascript and JSON allow object keys to be arbitrary keys.  Thus to properly ingest any JSON, we should support arbitrary strings as keys.  This means we will need a zql special syntax to support record accesses that have special chars and we might as well follow javascript convention e.g., `rec.@foo` should be rec["@foo"].
6. First-class types.  @henridf suggested having type IDs available to zql (e.g., to do `count() by id(fld)`), but since they are arbitrary integers this would an odd semantics.   So, instead we could have first-class types in zng where typeof(fld) is a type value that images the same as a zng type string but is a bona fide value in the zq runtime. 
7. Error values. Make errors a type so error messages (e.g., divide by zero) can be embedded in a zng stream and errors can easily be queried, searched and aggregated.  Similar to the go error type where the presence of the built-in type is very useful and its value is just a string.
8. Change "container" in the spec to the agreed-upon term "complex" type.  We can use both container and complex in the code, depending on whether we're talking about the type or the container construct in the code to whole the values of a complex type (e.g., the bool returned by it.Next() is called container everywhere).

## Breaking changes 

1. Change sets to allow only one type (breaking change to set typedef; everything else should just work as is.)
2. Rework type ID space so that numbers are packed better for attributes checks like `IsSignedInteger` and finalize  "23" to the number that will be start of dynamic typedefs.
3. Rework encoding of ctrl/value encoding so as to not "waste" 128 codes for control functions.  Code the top-level value as a zcode tagged value and get rid of the special case length management encoded at the start of the zng value.   This will get rid of the need for zcode.ContainerBody() when encoding top-level row values into zng.Records.

## Other stuff?

We should also refactor 

What else should we look at?  Do final cross-reviews with:

* parquet 
* avro
* orc
* protobufs
* flatbuffers
* flexbuffers
* arrow (in memory)
* bson

**Comment by henridf** [comment]
> What else should we look at?

Support non-record top-level values as per the spec. I think what that means for ZNG specifically is clear; but it will lead to the question of if/how to handle such values in ZQL, where the assumption of top-level record values is pervasive. Maybe we can just start off with just saying that the ZQL runtime doesn't handle these values.

**Comment by mccanne** [comment]
@henridf you want to change the pull interface to fetch zng.Values instead of zng.Records then have each proc deal with arbitrary streams of values?  I was thinkiing the data pipeline would support just zng.Records but that concepts like marshaling could take any zng.Value...

**Comment by henridf** [comment]
>  you want to change the pull interface to fetch zng.Values instead of zng.Records

@mccanne I wasn't suggesting that, I do see some upside to keeping all procs record-oriented (if only to keep the ZQL model simple for the user). 

I was more concerned with the implementation question of how to cordon off "data pipeline" from "marshaling" as they are quite intertwined. But maybe it's easier than I'm thinking though. We'd need to start off with having `zq` recognize `*` as a special case for which case it shouldn't compile a flowgraph...

**Comment by philrz** [comment]
RE: "...and change zeek enums to zenum as string alias"

This is already there in the zq implementation:

```
$ zq -t 'cut proto | head 1' conn.log.gz
#zenum=string
#0:record[proto:zenum]
0:[tcp;]
```

Or are you saying that in the spec we should explicitly call out why an implementation like zq has to do this rather than using the true ZNG `enum` type?

**Comment by mccanne** [comment]
@phil re enums, yes, the zng spec defines them incorrectly.  The first step was doing zng alias so it's good that this is already there.  To be clear, the typedef of an enum should be an ordered list of enum names and a value is encoded with the integer position of the name in the list.

**Comment by philrz** [comment]
While complete functionality in zq/ZQL for some ZNG beta changes have been implemented in the work linked to this Epic, where there's no exposure to backward compatibility problems, we've intentionally held off on implementing some portions in zq/ZQL until they become a priority. Those loose ends are called out in the [beta notification](https://github.com/brimsec/zq/blob/master/zng/docs/spec.md#note-this-specification-is-in-beta-development) at the top of the ZNG spec and tracked in https://github.com/brimsec/zq/issues/1520.
