### ISSUE TITLE
add vanilla ndjson to search endpoint

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1275]
Add an ndjson writer path to the search endpoint that is used when the format in the API request is "ndjson".  The client currently requests "zjson" so this won't break anything.

Change the response mime type for in the current zjson responder to be application/x-szjson (i.e,. steaming zjson).

Given the clean design of zqd/search, this task should be trivial by following the pattern of the zng responder using an ndjsonio.Writer and dropping control messages.

**Comment by philrz** [comment]
Verified in `zqd` commit `4bce00d`.

If a user just wants to see NDJSON output, they now have two ways to functionally arrive at that, the latter being the new one:

```
$ zapi -s foo get -f ndjson > /tmp/f.ndjson
$ zapi -s foo get -e ndjson > /tmp/e.ndjson

$ ls -al /tmp/*.ndjson
-rw-r--r--  1 phil  wheel  5468027 Sep 17 09:15 /tmp/e.ndjson
-rw-r--r--  1 phil  wheel  5468027 Sep 17 09:15 /tmp/f.ndjson

$ diff /tmp/e.ndjson /tmp/f.ndjson 
$ echo $?
0
```

The difference is that for `-f ndjson`, the response comes back from `zqd` as ZNG and it's up to the client to format it (into NDJSON in this case). As sniffed on the wire, the response begins:

```
Content-Type: application/x-zng
X-Request-Id: 6
Date: Thu, 17 Sep 2020 16:02:08 GMT
Transfer-Encoding: chunked
...
```

For `-e ndjson`, the response comes back from the server already rendered as NDJSON.

```
Content-Type: application/x-ndjson
X-Request-Id: 4
Date: Thu, 17 Sep 2020 16:00:59 GMT
Transfer-Encoding: chunked

800
{"_path":"stats","active_dns_requests":0,"active_files":0,"active_icmp_conns":1,"active_tcp_conns":3,"active_timers":197,"active_udp_conns":8,"bytes_recv":1185720,"dns_requests":0,"events_proc":6654,"events_queued":6648,"files":154,"icmp_conns":1,"mem":117,"peer":"bro","pkt_lag":null,"pkts_dropped":null,"pkts_link":null,"pkts_proc":3185,"reassem_file_size":0,"reassem_frag_size":0,"reassem_tcp_size":0,"reassem_unknown_size":0,"tcp_conns":156,"timers":2661,"ts":"1428917544.44639","udp_conns":98}
...
```

As explained by @mccanne, this (along with the similar CSV response recently added) could allow users to make REST calls to `zqd` with everyday tooling (`curl`, Python, etc.) and start immediately processing the response as opposed to getting back ZNG or zjson and not knowing what to do with it or having to use a tool like `zapi` to convert it.

Thanks @mccanne!
