### ISSUE TITLE
"zng syntax error" when TZNG field contains a right square bracket

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#1305]
A community user ran into this bug while reading NDJSON data that had been converted to TZNG. Repro is on `zq` commit `2608a46`.

Start with some valid NDJSON:

```
$ echo '{"dstUdata": "]..3O7x"}' | jq .
{
  "dstUdata": "]..3O7x"
}
```

`zq` turns it into what's assumed to be valid TZNG.

```
$ echo '{"dstUdata": "]..3O7x"}' | zq -i ndjson -t -
#0:record[dstUdata:string]
0:[]..3O7x;]
```

However, if `zq` is asked to read that same TZNG, it chokes.

```
$ echo '{"dstUdata": "]..3O7x"}' | zq -i ndjson -t - | zq -i tzng -t -
/dev/stdin: line 2: zng syntax error
```

If I drop the `]` from the field value, it stops complaining, so that seems to be what's significant here.

```
$ echo '{"dstUdata": "..3O7x"}' | zq -i ndjson -t - | zq -i tzng -t -
#0:record[dstUdata:string]
0:[..3O7x;]
```

**Comment by mccanne** [comment]
Interesting.  If you save as zng the data is fine.  The problem is the tzng writer isn't escaping the bracket.

**Comment by philrz** [comment]
Indeed, I now see where `zq` behavior is out of sync with the spec. In [4.3.1 Character Escape Rules](
https://github.com/brimsec/zq/blob/master/zng/docs/spec.md#431-character-escape-rules) it says:

> Likewise, these characters must be escaped if they appear as the first character of a value:
> `[ ]`

**Comment by philrz** [comment]
Verified in `zq` commit `e278c5c8`.

The original repro attempt no longer produces an error:

```
$ echo '{"dstUdata": "]..3O7x"}' | zq -i ndjson -t - | zq -i tzng -t -
#0:record[dstUdata:string]
0:[\u{5d}..3O7x;]
```

Thanks @mccanne!
