### ISSUE TITLE
implement byte type

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1316]
Implement the byte type and add to coercion logic.

**Comment by mccanne** [comment]
Implement the byte type and add to coercion logic.

**Comment by mccanne** [comment]
Maybe we should have uint8 and int8?

**Comment by mccanne** [comment]
We adopted int8 and uint8 ini zng-beta and abandoned byes so this is done.  bytes[k] will give a uint8.

**Comment by philrz** [comment]
Per the previous comment, the change in #1394 was to remove `byte` from the [Primitive Types](https://github.com/brimsec/zq/blob/master/zng/docs/spec.md#5-primitive-types) in the ZNG spec and use `uint8` in contexts where we'd previously envisioned `byte` would be applicable. This is not to be confused with the `bytes` (plural!) type that remains.

Also per the comment above, the ability to invoke the index operator in ZQL such that "bytes[k] will give a uint8" has yet to be addressed. That is tracked in #1421.
