### ISSUE TITLE
text zng should have end-of-stream

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1364]
Text zng should have an end-of-stream marker so tzng flies can be concatenated the same way zng files can.

**Comment by philrz** [comment]
The [TZNG End of Stream marker is now mentioned in the ZNG spec](https://github.com/brimsec/zq/blob/master/zng/docs/spec.md#414-end-of-stream), but it's not output in the TZNG generated by `zq` (current commit `0c6b642`). It seems at this point we could go one of two directions:

1. Implement it in `zq`, or,
2. Choose not to implement it for now. And there's already a disclosure to this effect in the [beta notification at the top of the ZNG spec](https://github.com/brimsec/zq/blob/master/zng/docs/spec.md#note-this-specification-is-in-beta-development), so there'd be no effort required to choose this option.

**Comment by mccanne** [comment]
I had a new thought here that maybe it would be cleaner to simply change the semantics of a tzng typedef for an id that already exists to simply redefine it rather than cause an error.

**Comment by mccanne** [comment]
We decided to do this differently as in #1568
