### ISSUE TITLE
clarify/improve expression/search zql syntax

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1371]
Now that we have ample experience with the zql syntax, there a few areas that need attention.

Our philosophy is to mix the right amount of ad-hoc, intuitive search syntax with formal and predictable semantics.

e.g., if you say `p1 < p2` even if they are both port fields, you get a comparison between field `p1` and the string `"p2"`. 

This is rooted in the simple syntax for field matching, i.e., `field=pattern` where you generally don't need to put quotes around strings to look for strings.

We changed the record syntax so you can also say `.fld` to mean the field `fld` of the top-level record, e.g., so you can say `.p1 < .p2` to provide clarity, though here .p2 still parses as a string (we need to fix). 

Complicating matters we have two different syntaxes for search/filter vs expressions in groupby-keys, puts, etc.  Also, syntax for reducers (since there is no groupby keywords) is ambiguous with a function called in the context of expression if we allow expression to be free form searches, so this needs a bit of thinking.

After some discussion, we decided that _identifier_ tokens (as compared with quoted string constants) will parse as identifiers unless they are the RHS of a simple comparison:
```
ident=ident
```
in which case the ident on the RHS will be interpreted as a string.  This will be true of expressions everywhere, e.g.,
```
_path=conn | count() 
```
should be the same as 
```
* | count() where _path=conn 
```
where the first expression is a form of free-form "search" and the second expression is a boolean expression.
In the latter case you can also do keyword searches like:
```
GET AND index.html
```
which does a text search for "GET" (i.e., you don't have to quote it) and "index.html", but you can't say 
```
* | count() where GET AND index.html
```
because the latter phrase is an expression not a free-form search.  But if we say 
```
* | count() where a.b=a.c 
```
we then have ambiguity as to 
```
* | count() where a.b=index.html
```
Is the first case a field access and the second a string?  We need to decide how to disambiguate this.  
Should the rules be different for expr and search?

Perhaps we should bite the bullet and make expressions a superset of search patterns?  This could be ergonomically advantageous and I don't know that this has been done before.

Some previous notes:

* _word_ means _*=word_
* _word1=word2_ means  _.[word1]=word2:string_
* _word1=word2.word3_ means _.[word1]=.[word2][word3]_

What about dots in words?

And you can always say _word1=.word2_ to be explicit (and in the rare case you are really checking for equality between two fields) and of course this is equivalent to .word1=.word2

Come to think of it for assignments like put and groupby, you already have lhs=... so the first case (*=word) is irrelevant and we're really talking abouut letting rhs as a word be a string when it's a simple word=word form, otherwise the RHS is an expession.

**Comment by henridf** [comment]
Sounds good. This would be for all expression syntax, including functions and or syntactically function-like operators right?
That could then solve the question raised in https://github.com/brimsec/zq/issues/1365#issuecomment-699669534 by having `typeof(field)` vs `typeof(.field)`. 

One challenge is having different defaults in different parts of the expression syntax (e.g. in `p1<p2` the lhs is a field deref and the rhs is a literal). I'd think we want the same default everywhere in expressions, but that would be a breaking change, and may have other downsides.

**Comment by henridf** [comment]
Separately, if we adopt the `.field` syntax, then `.` could mean "the entire record" à la `jq`. For example `typeof(.)` vs `typeof()` as discussed in https://github.com/brimsec/zq/issues/1365#issuecomment-698981035.

**Comment by mccanne** [comment]
Also, we'll add support for multi-line comments using `/* ... */` from issue #1646 as this will introduce some lexical ambiguity which will be better resolved in the work here.
