### ISSUE TITLE
drop package names in functions

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1379]
Currently, the list of function names supported in expr/functions.go uses a package-style naming convention, i.e., `pkgname.func()`.  Until and unless we support a package import concept in zql this seems clunky and like overkill, and it's burdensome to have to type the package name.

Perhaps this is a bikeshed topic, but the proposal here is to drop the package name prefix from our library of function names, e.g., `Strings.tolower()` becomes `tolower()`, `Math.log()` becomes `log()` etc.

**Comment by mccanne** [comment]
We should also 
* unify the different variants of length() into a single len() function
* get rid of functions that are deprecated with :casts
* use snake_case

**Comment by philrz** [comment]
I'll plan to write the ZQL user docs for these soon, tracked in #1621.
