### ISSUE TITLE
Distributed Flowgraph Execution

### ISSUE THREAD

**Issue by marktwallace** [brimsec/zq#1382]
OK, still working on this, and I am expecting to give it a try without using a Redis queue. I'm keeping the text below, but it needs a rewrite.

--------------

This will generalize the zqd service (#1208) to execute parallelizable queries using multiple K8s pods. 
The zqd process will work as it does now, receiving queries from Brim as a JSON AST of Procs.
There will be an env var that configures zqd to support distributed Flowgraph execution, if this is set, then
in driver.Compile, when Procs are detected that can have parallel execution, zqd will take the Proc that can be executed in parallel, and the sources of data for those process (e.g. S3 objects), serialize them, and add this to a work queue that we will maintain on Redis.

There will be a pool of "zq workers" that pull work items from the Redis queue, and send the completed work back to the zqd instance that requested it. (Right now I'm not sure whether the completed work will written directly back to to the zqd instance, or whether it will be buffered through a Redis data structure like a stream.)

One subtask will be to create a zqd queue command that starts a zq worker, which will be similar to zqd listen, except that it will have no Rest API, and will obtain work from a Redis work queue. 

Another subtask will be to modify zqd to add work to the Redis queue.

[Eventually, after the basic stuff works, we can make the zqw processes smart about what they will pull off the queue. For example, they could selectively pull queued work items that require access to S3 objects that they already have in local cache. The point is that scheduling work will be a distributed task where the workers can attempt to optimize their throughput based on their context. ]

There is a google doc that discusses some future options for zq workers. It is very rough now, and does not mention Redis, but it will eventually be "pounded" into a roadmap for more advanced distributed Flowgraph execution.

https://docs.google.com/document/d/1ugCkJMTXPKe1UCTRxU4MKeodbrFySVeQpP2QBgCuctA/edit#

**Comment by marktwallace** [comment]
After a discussion with Henri, I've refined some of the idea about how to implement this.

Henri pointed out that Procs are receiver driven, so having a Proc pull fits more naturally into the existing pattern. He suggested I could implement a new type of Proc that pulls results that the zq workers have completed. To make this convenient, the first approach I will try is to have the zq workers pull their work items from a queue in Redis, and then have them write their results back to a Redis stream. Then, on the receiver side, a Proc in the zqd instance that initiated to work will pull the data from the Redis stream.

On the driver side, Henri suggested that the code is driver that set up the Procs could also enqueue the work to be done in parallel to the Redis queue.

So, (1) I need a new Proc type to Pull results from a Redis stream (this Proc would be added into the FlowGraph, for example, right before a "Merge" Proc, 
(2) that Proc is created in the Driver around the same time the Driver code enqueue the work item runs. (We do not need to involve Procs in the queuing of work.)

**Comment by henridf** [comment]
👍 

> (2) that Proc is created in the Driver around the same time the Driver code enqueue the work item runs. (We do not need to involve Procs in the queuing of work.)

I think the way to do this would be in two steps, similarly to how we parallelize an flowgraph for local execution:
0. A new AST node and proc implementation are created for the "redis reader" proc
1. An AST transform adds parallel branches with "redis reader" procs (invoked similarly to `driver.parallelizeFlowgraph()`). 
2. driver.Compile() gets compiles that transformed AST which will result in the redis reader procs starting to read from redis as soon as their `Pull()` method is called.

**Comment by marktwallace** [comment]
This is still a work in progress -- the comments above reflect how the ideas are evolving. I'll add more later.

**Comment by marktwallace** [comment]
This design has changed enough for me to use a new epic. Closing.
