### ISSUE TITLE
Halted by "incompatible types" error due to lack of a record field

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#1415]
With the merge of #1375, I've noticed that one of the index creation steps in the [`zar README`](https://github.com/brimsec/zq/blob/master/cmd/zar/README.md) that worked before now fails.

```
$ zq zng/*.gz | zar import -s 25MB -
$ zar index -q -o custom.zng -k id.orig_h -z "count() by _path, id.orig_h | sort id.orig_h"
incompatible types
```

I narrowed it down to a characteristic our Zeek test data. Specifically, whereas most Zeek events have an `id` field that's a `record` containing fields `orig_h`, `orig_p`, `resp_h`, `resp_p`, the Zeek `x509` event happens to contain a top-level field called `id` that's a `string`. Here's a trimmed down data set that covers the repro:

```
$ cat input.tzng 
#0:record[_path:string,id:record[orig_h:ip,orig_p:port,resp_h:ip,resp_p:port]]
0:[weird;[10.47.1.152;49562;23.217.103.245;80;]]
#1:record[_path:string,id:bstring]
1:[x509;FYNFkU3KccxXgIuUg5;]
0:[weird;[10.47.5.155;40712;91.189.91.23;80;]]
```

At commit `a80c575` that came right before the merge of #1375, `zq` seemed to quietly "skip over" the `x509` record. This made sense to me as a user because `id.orig_h` didn't exist in the `x509` event.

```
$ zq -version
Version: v0.22.0-18-ga80c575

$ zq -t 'count() by id.orig_h' input.tzng 
#0:record[id:record[orig_h:ip],count:uint64]
0:[[10.47.1.152;]1;]
0:[[10.47.5.155;]1;]
```

Now at commit `56ed80d` that comes with the merge of #1375:

```
$ zq -version
Version: v0.22.0-19-g56ed80d

$ zq -t 'count() by id.orig_h' input.tzng 
incompatible types
```

I wondered if maybe this is some intentional new stricter behavior. However, we do still quietly "skip over" attempts to aggregate by wholly absent top-level fields, e.g.:

```
$ zq -version
Version: v0.22.0-19-g56ed80d

$ zq -t 'count() by foo' input.tzng
[no output]
```

Therefore I assume this is worth a look. If consensus is that the current behavior is actually desired, then at minimum we'll need to adjust the `zar` README.

**Comment by henridf** [comment]
I think this is a bug, but since @mccanne is reworking how dot-fields are handled, this bug might be fixed along with that.

**Comment by philrz** [comment]
Verified in `zq` commit `e65ed59`.

First, I had to update the input data from the alpha TZNG format shown above to the new beta ZNG format.

```
$ zq -version
Version: v0.22.0

$ zq input.tzng > input.zng
```

[...update to current `zq` commit `e65ed59`...]

```
$ zq -version
Version: v0.22.0-50-ge65ed59

$ zq -t input.zng > input-beta.tzng 
warning: input.zng: converting from alpha zng to beta zng (slow)
warning: update zng by running 'zq -o new.zng old.zng'

$ zq -t 'count() by id.orig_h' input-beta.tzng 
#0:record[id:record[orig_h:ip],count:uint64]
0:[[10.47.1.152;]1;]
0:[[10.47.5.155;]1;]
```

The index creation shown from the `zar` README that was broken also works now.

```
$ zar -version
Version: v0.22.0-50-ge65ed59

$ zq zng/*.gz | zar import -s 25MB -
$ zar index -q -o custom.zng -k id.orig_h -z "count() by _path, id.orig_h | sort id.orig_h"
$ zar ls -l
file:///Users/phil/logs/zd/20180324/d-1ise0yfDIpEGpbBGxou72pNvfgD-188695-1521912990158766000-1521911720601474000.zng.zar/custom.zng
file:///Users/phil/logs/zd/20180324/d-1ise0qTowgbKLIwFJhd6FPwOBmF-212117-1521912809032641000-1521911720612096000.zng.zar/custom.zng
file:///Users/phil/logs/zd/20180324/d-1ise0s6m9ZfpD1MJcko4aaBDNbt-224712-1521912573152746000-1521911720608867000.zng.zar/custom.zng
file:///Users/phil/logs/zd/20180324/d-1ise0jbLU2Pfc3fy7smVHJILJFF-199875-1521912355502512000-1521911720601374000.zng.zar/custom.zng
file:///Users/phil/logs/zd/20180324/d-1ise0edG7qOGsK0UU32FCiRPbsx-209351-1521912172917284000-1521911720609380000.zng.zar/custom.zng
file:///Users/phil/logs/zd/20180324/d-1ise0RmPPNQbS2FruKI4lpDdl4c-212678-1521911994618642000-1521911720726418000.zng.zar/custom.zng
file:///Users/phil/logs/zd/20180324/d-1ise0NrwoZ2ROt4g5yheRuaHwlc-214650-1521911858335096000-1521911720600725000.zng.zar/custom.zng
```

Thanks @mccanne!
