### ISSUE TITLE
add decimal type placeholder

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1422]

**Comment by alfred-landrum** [comment]
@mccanne : I see the decimal128 entry in the zng spec; is that enough to call this issue done?

**Comment by philrz** [comment]
@alfred-landrum @mccanne: I'm certainly fine with leaving `decimal128` unimplemented in `zq`. But if we go that route, we should add a note to that effect in the [beta notification at the top of the ZNG spec](https://github.com/brimsec/zq/blob/master/zng/docs/spec.md#note-this-specification-is-in-beta-development) wherein we've traditionally made these disclosures.

**Comment by philrz** [comment]
Once #1523 is merged, the fact it's not-yet-supported in zq will be documented. I've opened #1522 to track its eventual implementation.
