### ISSUE TITLE
grammar for reducer names should allow arbitrary identifier

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1466]
The grammar for reducers hard codes the list of reducers.  We should change the grammar so any identifier can be a reducer name and the code generator does a semantic check for known reducers.  This will make it easier to add reducers without having to change the grammar.

**Comment by philrz** [comment]
@mccanne: It looks like this one already got taken care of. Sound correct?

**Comment by nwt** [comment]
Done in #1490.
