### ISSUE TITLE
TZNG pretty printer

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#1499]
@mccanne and I both have a habit of often running `zq -f ndjson ... | jq .` to see pretty-printed output. Of course, this also amputates the rich typing info that would have been visible in TZNG format.

@mccanne has an idea for a TZNG pretty printer that could be backward-compatible with current TZNG. He's expressed an interest in prototyping it so others can react and see if we want to keep it.

A summary of what @mccanne spoke of in one conversation about this, though by no means a commitment we have to take this approach:

> We could relax the whitespace semantics to allow you to embed newlines and spaces. You'd have the option to put whitespace in front of a value if you want, and if the first char of a value is whitespace, you escape it. Old TZNG would still work.

**Comment by mccanne** [comment]
Closing as this has been subsumed by ZSON.
