### ISSUE TITLE
zql: can't rename `.`

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1518]
The long way (`put | cut`) works:

```
$ cat in.tzng 
#0:record[a:int32,b:int32]
0:[1;2;]
$ zq -t "put rec=. | cut rec" in.tzng 
#0:record[rec:record[a:int32,b:int32]]
0:[[1;2;]]
```

but the short way (`rename`) doesn't:
```
$ zq -t "rename rec=." in.tzng 
cannot rename  to rec
```

**Comment by nwt** [comment]
As currently implemented, `rename` is limited to changing names of existing fields and can't modify record structure. 

Is that something we want to change?

**Comment by henridf** [comment]
@nwt I think this should be closed as invalid. I didn't think it through properly when opening it.
