### ISSUE TITLE
Hook type context into expressions library package

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#1524]
There's a few things that would benefit from type context being accessible from the expression library package:

* Implementing the ZNG `error` type as an alias rather than a primitive type
* Proper casting of complex types
* Creating complex literals

**Comment by mccanne** [comment]
Repurposing this issue as work from the error-alias branch to change the expr.Function type to an interface and pass the type context into the expr compiler.  We need this change anyway for function like "cut" which is like the cut proc but  callable from an expression context, e.g., `union(cut(id)) by _path`...
