### ISSUE TITLE
ZNG type "error" should be an alias

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#1525]
ZNG type `error` is currently a Primitive Type in the ZNG spec, but we've reached consensus that it should be implemented as an `alias` in `zq` instead. Therefore the ZNG spec will need to have ZNG removed from the spec, then the `zq` implementation changed to match. #1524 should help make this possible.

When talking about making this change, we realized that there probably should be a place in the `zq` repo where we divulge the current list of aliased types and if there's any special handling attached to them. At the moment the only aliases are from the Zeek `enum` and `port` types, and this is covered in [ZNG Compatibility with Zeek Logs](https://github.com/brimsec/zq/blob/master/zng/docs/zeek-compat.md). However once we turn `error` into an alias we probably should break out the proposed doc to describe all three there.

**Comment by mccanne** [comment]
Closing as we decided to keep "error" as a native type.
