### ISSUE TITLE
Update Suricata rules

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#1552]
Suricata needs to be kept abreast of the latest threats. Typically these are kept up-to-date by running the `suricata-update` tool that comes with Suricata. When we have a bundled Suricata artifact with Brim, we'll surely want a way for this update to run periodically, hopefully with little/no effort on the user's part.

One possibility that comes to mind is to just run the update once whenever the app is launched, though if users use Brim so much that they keep it always open on the desktop, perhaps this would not be enough. Maybe some `cron`-like scheduler could do the update on a regular schedule. Some button/control in the app to trigger an immediate update might be yet another option. We might also want to think about a place in the app where we could provide minimally-disruptive informative messages saying the update has run.

**Comment by henridf** [comment]
Some notes from looking at `suricata-update`.

- The suricata distribution has some basic rules included (https://github.com/OISF/suricata/blob/master-5.0.x/rules/http-events.rules). When `suricata-update` is run, these rules are added to the remote rules fetched by suricata-update. 

- `suricata-update` freshness / change detection: if the last download time is more than 15 minutes ago, it then compares the https://rules.emergingthreats.net/open/suricata-5.0/emerging.rules.tar.gz.md5 with the md5 of the previously downloaded rules.

**Comment by henridf** [comment]
Also, we've talked about BYO Suricata as the escape hatch for users who want other rules than the default etopen. A simpler route might just be for those users to manually run `suricata-update` pointed at whichever sources they typically use.
