### ISSUE TITLE
allow Z type names to be redefined

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1568]
After further design considerations regarding Z lakes, we realized it would be architecturally favorable to allow Z type names to be redefined.  This is preferred over managing the policing and rejection process when ingesting data into a lake.  This simply means that typedef names may change during a scan and because Z has flexible and forgiving semantics, this will all "just work".  For example, the canonical Z type value will simply have two different values for a type name and the most recent binding in a Z sequence defines the type for any given scan of the sequence. For example, such type definitions will show up in an aggregation by type value and when the resulting aggregate type value keys are scanned the name would simply be redefined in sequence.  Since canonical type values embed the type name mapping, this all just works.

To make this change we should:
* update the tzngio reader, which currently halts with an error with a type tag is reused
* update the zson reader,
* update the zng reader,
* change the zson.Context API to allow alias redefs,
* update the Z spec (ZSON and ZNG)

A technical detail: when type names are redefined, the old type structure and references still exist in the zson.Context with any runtime zng Values referring to them.  For ZST, this is very manageable but means the ZST reader must track which type name bindings are valid in which parts of the columnar data when such typedefs change.  This could be easily stored in the meta-data as another (typically absent or very small) section.  We will put the ZST work in a separate issue.

For tzng, we should allow this in accordance with the XXX in the code (line 132 in tzngio/reader.go)

This will us allow tzng files to be concatenated without error.

While we're at it here, we should change the deprecated "descriptor" references in the tzngio package to refer to record types and type tags instead of descriptors.

With this change, the distrinction between type names as integers and identifiers is less important, though by convention it still is important that locally type names can be chosen from the space of integers as a way to avoid user-defined type names that span a lake.

One more technical point:  in thinking further, the fact that type names can be redefined is really important for high-level types that might represent a common schema where elements of the common schema have union sub-columns and the union content is a function of actual data in the part of the lake that the type refers to.

**Comment by mccanne** [comment]
This issue is part of the larger change to allow Z types to be redefined.  I am changing the title of this issue and broadening its scope.

**Comment by philrz** [comment]
Verified in `zq` commit `28a347d`.

At commit 62bf54d that came right before the changes in the linked PR, redefining type definitions was a fatal error.

```
$ cat input.zson 
{x:1} (=foo)
{x:2} (foo)
{x:"hello"} (=foo)
{x:"world"} (foo)

$ zq -version
Version: v0.29.0-150-g62bf54df

$ zq -z input.zson 
input.zson: type "foo" redefined from "foo=({x:int64})" to "{x:string}"
```

Now at commit `28a347d`, the input is read without error.

```
$ zq -version
Version: v0.29.0-167-g28a347d7

$ zq -z input.zson 
{x:1} (=foo)
{x:2} (foo)
{x:"hello"} (=foo)
{x:"world"} (foo)
```

Thanks @mccanne!
