### ISSUE TITLE
prevent seek index misses from consecutive timestamps

### ISSUE THREAD

**Issue by mattnibs** [brimsec/zq#1594]
@alfred-landrum brought up a valid concern that records with the same timestamp could result in seek index misses: If the record chosen as an entry in the seek index has the same timestamp as the previous record, that previous record would be missed.

This ticket aims to prevent this scenario from happening.

**Comment by alfred-landrum** [comment]
Note that this may be the cause of, or at least related to, the record count discrepancy in https://github.com/brimsec/zq/issues/1579 .

**Comment by mattnibs** [comment]
> Note that this may be the cause of, or at least related to, the record count discrepancy in #1579 .

I can verify that this is not the case, pr arriving shortly.
