### ISSUE TITLE
Batch.Records() should return []zng.Record

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1613]
Batch.Records() should return []zng.Record instead of *[]zng.Record.

This could make things more efficient by getting rid of an extra layer of indirection in Batch objects.
To support filter, the Batch interface could implement a copy-on-write model where an outer Batch wraps an inner batch as holds a subset of the inner batch's records.  When the outer batch is unref'd, it would unref the inner batch.  The outer Batch buffer could come from the same pool as the original batch or it could be a separately allocated wrapper.

This would make zbuf.Merger more efficient when there are non-overlapping batches (a common case in the s3 reader path) because the Records pointer array would not have to be copied and GC'd.

**Comment by alfred-landrum** [comment]
Closing, as I believe this is subsumed by #1762
