### ISSUE TITLE
zq flag for loading zql query from a file

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1624]
With the addition of joins and more complex aggregations, zql queries are getting more sophisticated and it's easier to write them over multiple lines in a "source file".  Also, automated scripts might be more easily specified by referring to zql queries stored elsewhere.

Thus, we should add an option to zq and related tooling to specify that the zql query to be executed comes from a named file rather than the query explicitly appearing on the command-line.

**Comment by philrz** [comment]
Verified in #1646.
