### ISSUE TITLE
time grouping not working for zar archives

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#1641]
I was testing Brim with some archive spaces, and noticed that the histogram seemed wrong: a) it populated oddly, with values appearing through the entire time span sporadically, and b) the final result visually looked different when compared with importing data into a file-based store.

I created a small input file (the data I used in Brim was large), and was able to see the difference by using a local `zqd` and some `zapi` commands.

I used this tzng file:
https://gist.github.com/alfred-landrum/cb40d931697223e4a52c5f28cf251627

and ran a comparison like so:

```
$ zapi -s gtest-ark post -k archivestore -thresh 1KiB -f group-test.tzng
$ zapi -s gtest-file post -f group-test.tzng
$ zapi -s gtest-ark get -t 'every 3600s count() by g | count()'
#0:record[count:uint64]
0:[628;]
$ zapi -s gtest-file get -t 'every 3600s count() by g | count()'
#0:record[count:uint64]
0:[480;]
```

Looking at the output from the archive operation, the groupings are out-of-order.

**Comment by philrz** [comment]
Verified in `zq` commit `20329d11`. Repeating the original repro steps, now the counts match.

```
$ zq -version
Version: v0.23.0-45-g20329d11

$ zapi -s gtest-ark post -k archivestore -thresh 1KiB -f group-test.tzng
posted 54.67KB in 31.45706ms

$ zapi -s gtest-file post -f group-test.tzng
posted 54.67KB in 10.551633ms

$ zapi -s gtest-ark get -t 'every 3600s count() by g | count()'
#0:record[count:uint64]
0:[480;]

$ zapi -s gtest-file get -t 'every 3600s count() by g | count()'
#0:record[count:uint64]
0:[480;]
```

Thanks @alfred-landrum!
