### ISSUE TITLE
zql source files, multi-line zql syntax, and embedded comment syntax

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1646]
With joins, we now have complex flowgraphs across multiple lines as well as being able to specify a source file containing a zql query instead of having to format multi-line zql queries on the command line.

Add multi-line add support as well as comment syntax.

@nwt suggests both single-line `//` comments as well as multi-line C-style comments `/* ... */``

**Comment by mccanne** [comment]
Moving multi-line comment work to issue #1371

**Comment by philrz** [comment]
Verified in `zq` commit `b20a71ba`. Here's a file containing multi-line ZQL and single-line comments, running successfully against the zq-sample-data:

```
~/work/zq-sample-data/zeek-default$ zq -version
Version: v0.23.0-59-gb20a71ba

~/work/zq-sample-data/zeek-default$ cat ~/work/zq-1654/my_query.zql 
// This is a comment about my query
count() by _path |
(
  count();
  all_paths=collect(_path)
)

// Here's another comment

~/work/zq-sample-data/zeek-default$ zq -t -z ~/work/zq-1654/my_query.zql *
#0:record[all_paths:array[string]]
0:[[conn;ftp;modbus;kerberos;capture_loss;http;x509;dce_rpc;smb_mapping;ntlm;snmp;pe;smb_files;rfb;files;dns;ssl;notice;dpd;rdp;smtp;ntp;stats;weird;syslog;ssh;]]
#1:record[count:uint64]
1:[26;]
```

Some relevant follow-on issues:
1. Multi-line comments are being pursued as part of #1371.
2. The syntax with `;` to separate multiple branches in a flowgraph may be subject to change, as tracked in #1644.

Thanks @mccanne!
