### ISSUE TITLE
archive focused parallel query tests

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#1660]
The recent work in #1650 and #1635 highlighted a need for more tests that exercise parallel queries against real archives. We can also use this time to restructure the initial parallel analysis code if that's helpful, as we've implemented considerable changes in merge, groupby, etc. since it first went in.

**Comment by nwt** [comment]
brimsec/rug#189, brimsec/rug#190, brimsec/rug#191, and brimsec/rug#192 update the old boom correctness tests for zqd.
