### ISSUE TITLE
nested lval support for put

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1753]
The put proc gives an error if you use a nested field reference as the target.  We should fix this as it's easy now.  We have the technology.

**Comment by henridf** [comment]
While doing this, ensure that #1932 is addressed too.

**Comment by philrz** [comment]
Verified in `zq` commit `2294ca24` using the [zq-sample-data](https://github.com/brimsec/zq-sample-data).

The linked PR has tests that include several examples of this, but just to give an easy one, this used to not work (plus the error message had a typo in it :trollface:):

```
$ zq -f zson 'head 1 | cut id | put id.comment="my favorite flow"' conn.log.gz 
id.comment: put currently supports only top-level field assignemnts
```

Now it works.

```
$ zq -f zson 'head 1 | cut id | put id.comment="my favorite flow"' conn.log.gz 
{
    id: {
        orig_h: 10.164.94.120,
        orig_p: 39681 (port=(uint16)),
        resp_h: 10.47.3.155,
        resp_p: 3389 (port),
        comment: "my favorite flow"
    } (=0)
} (=1)
```

Thanks @henridf!
