### ISSUE TITLE
Get "chunk span does intersect provided span" on query of zar archive

### ISSUE THREAD

**Issue by marktwallace** [brimsec/zq#1758]
This occurred with commit 78cc64ccecc2dac44dd69a51235cbbdec8b86151
On branch master, tag was v0.24.0-19-g78cc64cc

I created a 14 GB zar archive with the command:

[ec2-user@ip-172-31-19-39 ~]$ time zar import -bufsize 1000MB -s 100MB -R s3://zqd-demo-1/mark/zeek-logs/conn-try3 s3://brim-sampledata/wrccdc/zeek-logs/conn.log.gz

real	93m36.353s
user	126m19.417s
sys	2m37.429s

(Note that this took over 80 minutes on an ec2  m5d.large)

Then on my laptop, I created an archive with zapi:

zapi new -k archivestore -d s3://zqd-demo-1/mark/zeek-logs/conn-try3 conn-100

And ran the following queries:

$ time zapi ls
conn-100
zapi ls  0.02s user 0.01s system 0% cpu 20.577 total
$ time zapi -s conn-100 get -t head 5
#port=uint16
#zenum=string
#0:record[_path:string,ts:time,uid:bstring,id:record[orig_h:ip,orig_p:port,resp_h:ip,resp_p:port],proto:zenum,service:bstring,duration:duration,orig_bytes:uint64,resp_bytes:uint64,conn_state:bstring,local_orig:bool,local_resp:bool,missed_bytes:uint64,history:bstring,orig_pkts:uint64,orig_ip_bytes:uint64,resp_pkts:uint64,resp_ip_bytes:uint64,tunnel_parents:set[bstring]]
0:[conn;1521940133.838568;CWMAhm3fIlJPE8Rp8c;[10.230.73.251;38491;10.47.6.30;443;]tcp;-;-;-;-;S0;-;-;0;S;1;44;0;0;-;]
0:[conn;1521940133.765872;C0JVnY3iTsTikg2rH5;[10.0.0.111;43416;10.47.5.208;80;]tcp;-;-;-;-;S0;-;-;0;S;1;60;0;0;-;]
0:[conn;1521940133.738418;CfFhAb3ii6EHIrCo3c;[10.230.73.251;38478;10.47.6.30;111;]tcp;-;-;-;-;S0;-;-;0;S;1;44;0;0;-;]
0:[conn;1521940133.710309;C0Yha7UpCgYes56g4;[10.0.0.111;35357;10.47.5.142;80;]tcp;-;-;-;-;S0;-;-;0;S;1;60;0;0;-;]
0:[conn;1521940133.638178;Cvg3tt1l4jL7hl4MEf;[10.230.73.251;38477;10.47.6.30;111;]tcp;-;-;-;-;S0;-;-;0;S;1;44;0;0;-;]
zapi -s conn-100 get -t head 5  0.02s user 0.01s system 0% cpu 22.977 total
$ time zapi -s conn-100 get -workers 10 -t "73841"
chunk span does intersect provided span
zapi -s conn-100 get -workers 10 -t "73841"  0.03s user 0.01s system 0% cpu 27.384 total
$

Note that only the last query got an error. I included the "head" query to show that the archive is readable for some queries.

And here are some useful comments from Al:

"Hmm, that's bad: it means we incorrectly selected a chunk for a given time range. It would take some digging to see what's wrong; it could be the chunk metadata that's wrong, or something about the selected span for the timerange that's off."

**Comment by marktwallace** [comment]
I will leave the corrupted archive on S3 until we have resolved the issue:
s3://zqd-demo-1/mark/zeek-logs/conn-try3

**Comment by marktwallace** [comment]
As mentioned in #1759, I continued trying to get the 14GB archive working, this time by choosing the default chunk size of 500GB. Unfortunately, the new archive hit the same problem as above:

$ time zapi -s conn-500 get -workers 10 -t "73841"
#port=uint16
#zenum=string
#0:record[_path:string,ts:time,uid:bstring,id:record[orig_h:ip,orig_p:port,resp_h:ip,resp_p:port],proto:zenum,service:bstring,duration:duration,orig_bytes:uint64,resp_bytes:uint64,conn_state:bstring,local_orig:bool,local_resp:bool,missed_bytes:uint64,history:bstring,orig_pkts:uint64,orig_ip_bytes:uint64,resp_pkts:uint64,resp_ip_bytes:uint64,tunnel_parents:set[bstring]]
0:[conn;1521930320.138611;CLX73841Eh29ks34i;[10.202.163.124;15120;10.47.44.40;4945;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;80;0;0;-;]
0:[conn;1521930320.138611;CLX73841Eh29ks34i;[10.202.163.124;15120;10.47.44.40;4945;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;80;0;0;-;]
0:[conn;1521926972.96147;Cg73841Clb05Dc0Hpk;[10.168.36.216;14500;10.47.41.20;1073;]tcp;-;0.008974;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521926972.96147;Cg73841Clb05Dc0Hpk;[10.168.36.216;14500;10.47.41.20;1073;]tcp;-;0.008974;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521915092.374446;CsXis73841uXeEuOD5;[10.128.0.235;34998;10.47.24.128;35662;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;120;0;0;-;]
0:[conn;1521915092.374446;CsXis73841uXeEuOD5;[10.128.0.235;34998;10.47.24.128;35662;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;120;0;0;-;]
0:[conn;1521913226.575198;C9EMv73841waY7Zic5;[10.128.0.227;58253;10.10.1.101;1000;]tcp;-;0.041305;0;0;S0;-;-;0;S;342;21888;0;0;-;]
0:[conn;1521913226.575198;C9EMv73841waY7Zic5;[10.128.0.227;58253;10.10.1.101;1000;]tcp;-;0.041305;0;0;S0;-;-;0;S;342;21888;0;0;-;]
chunk span does intersect provided span
zapi -s conn-500 get -workers 10 -t "73841"  0.08s user 0.05s system 0% cpu 5:57.23 total
$

I will try this once more overnight with few workers, to see if there is any interaction between this problem and the number or workers (I do not expect there is.) It will also give me a rough benchmark to compare to the ~6 minutes until failure seen above.

**Comment by marktwallace** [comment]
Here is the same query with 1 worker, rather than 10. I runs for longer and returns more rows, then terminates with "key not found":

$ time zapi -s conn-500 get -workers 1 -t "73841"
#port=uint16
#zenum=string
#0:record[_path:string,ts:time,uid:bstring,id:record[orig_h:ip,orig_p:port,resp_h:ip,resp_p:port],proto:zenum,service:bstring,duration:duration,orig_bytes:uint64,resp_bytes:uint64,conn_state:bstring,local_orig:bool,local_resp:bool,missed_bytes:uint64,history:bstring,orig_pkts:uint64,orig_ip_bytes:uint64,resp_pkts:uint64,resp_ip_bytes:uint64,tunnel_parents:set[bstring]]
0:[conn;1521930320.138611;CLX73841Eh29ks34i;[10.202.163.124;15120;10.47.44.40;4945;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;80;0;0;-;]
0:[conn;1521930320.138611;CLX73841Eh29ks34i;[10.202.163.124;15120;10.47.44.40;4945;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;80;0;0;-;]
0:[conn;1521926972.96147;Cg73841Clb05Dc0Hpk;[10.168.36.216;14500;10.47.41.20;1073;]tcp;-;0.008974;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521926972.96147;Cg73841Clb05Dc0Hpk;[10.168.36.216;14500;10.47.41.20;1073;]tcp;-;0.008974;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521915092.374446;CsXis73841uXeEuOD5;[10.128.0.235;34998;10.47.24.128;35662;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;120;0;0;-;]
0:[conn;1521915092.374446;CsXis73841uXeEuOD5;[10.128.0.235;34998;10.47.24.128;35662;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;120;0;0;-;]
0:[conn;1521913226.575198;C9EMv73841waY7Zic5;[10.128.0.227;58253;10.10.1.101;1000;]tcp;-;0.041305;0;0;S0;-;-;0;S;342;21888;0;0;-;]
0:[conn;1521913226.575198;C9EMv73841waY7Zic5;[10.128.0.227;58253;10.10.1.101;1000;]tcp;-;0.041305;0;0;S0;-;-;0;S;342;21888;0;0;-;]
0:[conn;1521875954.14656;CV73841GUIMlauNkck;[10.163.143.94;43480;10.47.3.54;22;]tcp;-;0.001148;0;0;RSTO;-;-;0;ShR;4;168;2;88;-;]
0:[conn;1521859119.117362;CHIOM73841amC5i7O;[10.129.182.98;21701;10.47.26.80;56645;]tcp;-;0.001408;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521859119.117362;CHIOM73841amC5i7O;[10.129.182.98;21701;10.47.26.80;56645;]tcp;-;0.001408;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521859119.117362;CHIOM73841amC5i7O;[10.129.182.98;21701;10.47.26.80;56645;]tcp;-;0.001408;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521859119.117362;CHIOM73841amC5i7O;[10.129.182.98;21701;10.47.26.80;56645;]tcp;-;0.001408;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521858627.696983;CUAjpN1FXS73841sx4;[10.178.98.167;54563;10.47.8.152;21678;]tcp;-;0.000302;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521858627.696983;CUAjpN1FXS73841sx4;[10.178.98.167;54563;10.47.8.152;21678;]tcp;-;0.000302;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521858627.696983;CUAjpN1FXS73841sx4;[10.178.98.167;54563;10.47.8.152;21678;]tcp;-;0.000302;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521858627.696983;CUAjpN1FXS73841sx4;[10.178.98.167;54563;10.47.8.152;21678;]tcp;-;0.000302;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521853977.951621;CF1px73841wwqzhx1;[10.216.207.9;20776;10.47.25.186;32846;]tcp;-;0.001294;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521853977.951621;CF1px73841wwqzhx1;[10.216.207.9;20776;10.47.25.186;32846;]tcp;-;0.001294;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521853977.951621;CF1px73841wwqzhx1;[10.216.207.9;20776;10.47.25.186;32846;]tcp;-;0.001294;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521853977.951621;CF1px73841wwqzhx1;[10.216.207.9;20776;10.47.25.186;32846;]tcp;-;0.001294;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521851720.232576;CR273841qKJXT2Z0Gl;[10.128.0.225;53939;10.47.3.154;29604;]tcp;-;0.000271;0;0;REJ;-;-;0;Sr;2;88;2;80;-;]
0:[conn;1521851720.232576;CR273841qKJXT2Z0Gl;[10.128.0.225;53939;10.47.3.154;29604;]tcp;-;0.000271;0;0;REJ;-;-;0;Sr;2;88;2;80;-;]
0:[conn;1521851720.232576;CR273841qKJXT2Z0Gl;[10.128.0.225;53939;10.47.3.154;29604;]tcp;-;0.000271;0;0;REJ;-;-;0;Sr;2;88;2;80;-;]
0:[conn;1521851720.232576;CR273841qKJXT2Z0Gl;[10.128.0.225;53939;10.47.3.154;29604;]tcp;-;0.000271;0;0;REJ;-;-;0;Sr;2;88;2;80;-;]
0:[conn;1521851387.050202;Ck73841Jwef1UxYYk5;[10.157.156.128;31597;10.47.21.172;63292;]tcp;-;0.001345;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521851387.050202;Ck73841Jwef1UxYYk5;[10.157.156.128;31597;10.47.21.172;63292;]tcp;-;0.001345;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521851387.050202;Ck73841Jwef1UxYYk5;[10.157.156.128;31597;10.47.21.172;63292;]tcp;-;0.001345;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521851387.050202;Ck73841Jwef1UxYYk5;[10.157.156.128;31597;10.47.21.172;63292;]tcp;-;0.001345;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521850520.224789;CXj73841K2RDbzXyZ6;[10.252.54.106;56651;10.47.27.80;23406;]tcp;-;0.000599;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521850520.224789;CXj73841K2RDbzXyZ6;[10.252.54.106;56651;10.47.27.80;23406;]tcp;-;0.000599;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521850520.224789;CXj73841K2RDbzXyZ6;[10.252.54.106;56651;10.47.27.80;23406;]tcp;-;0.000599;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521850520.224789;CXj73841K2RDbzXyZ6;[10.252.54.106;56651;10.47.27.80;23406;]tcp;-;0.000599;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521848775.616015;Cf73841vdzo0ORs5nk;[10.128.0.235;39306;10.47.24.253;10043;]tcp;-;0.000043;0;0;S0;-;-;0;S;2;120;0;0;-;]
0:[conn;1521848775.616015;Cf73841vdzo0ORs5nk;[10.128.0.235;39306;10.47.24.253;10043;]tcp;-;0.000043;0;0;S0;-;-;0;S;2;120;0;0;-;]
key not found
zapi -s conn-500 get -workers 1 -t "73841"  0.26s user 0.14s system 0% cpu 19:13.92 total
$

**Comment by marktwallace** [comment]
The different termination of this 1 worker run makes me think it never got to the "chunk span does intersect provided span" part of the archive, an may have hit a different termination condition earlier in the archive. I will try again one more time with -workers=2

**Comment by marktwallace** [comment]
Here are the results with -workers 2:

$ time zapi -s conn-500 get -workers 2 -t "73841"
#port=uint16
#zenum=string
#0:record[_path:string,ts:time,uid:bstring,id:record[orig_h:ip,orig_p:port,resp_h:ip,resp_p:port],proto:zenum,service:bstring,duration:duration,orig_bytes:uint64,resp_bytes:uint64,conn_state:bstring,local_orig:bool,local_resp:bool,missed_bytes:uint64,history:bstring,orig_pkts:uint64,orig_ip_bytes:uint64,resp_pkts:uint64,resp_ip_bytes:uint64,tunnel_parents:set[bstring]]
0:[conn;1521930320.138611;CLX73841Eh29ks34i;[10.202.163.124;15120;10.47.44.40;4945;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;80;0;0;-;]
0:[conn;1521930320.138611;CLX73841Eh29ks34i;[10.202.163.124;15120;10.47.44.40;4945;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;80;0;0;-;]
0:[conn;1521926972.96147;Cg73841Clb05Dc0Hpk;[10.168.36.216;14500;10.47.41.20;1073;]tcp;-;0.008974;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521926972.96147;Cg73841Clb05Dc0Hpk;[10.168.36.216;14500;10.47.41.20;1073;]tcp;-;0.008974;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521915092.374446;CsXis73841uXeEuOD5;[10.128.0.235;34998;10.47.24.128;35662;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;120;0;0;-;]
0:[conn;1521915092.374446;CsXis73841uXeEuOD5;[10.128.0.235;34998;10.47.24.128;35662;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;120;0;0;-;]
0:[conn;1521913226.575198;C9EMv73841waY7Zic5;[10.128.0.227;58253;10.10.1.101;1000;]tcp;-;0.041305;0;0;S0;-;-;0;S;342;21888;0;0;-;]
0:[conn;1521913226.575198;C9EMv73841waY7Zic5;[10.128.0.227;58253;10.10.1.101;1000;]tcp;-;0.041305;0;0;S0;-;-;0;S;342;21888;0;0;-;]
0:[conn;1521875954.14656;CV73841GUIMlauNkck;[10.163.143.94;43480;10.47.3.54;22;]tcp;-;0.001148;0;0;RSTO;-;-;0;ShR;4;168;2;88;-;]
0:[conn;1521859119.117362;CHIOM73841amC5i7O;[10.129.182.98;21701;10.47.26.80;56645;]tcp;-;0.001408;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521859119.117362;CHIOM73841amC5i7O;[10.129.182.98;21701;10.47.26.80;56645;]tcp;-;0.001408;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521859119.117362;CHIOM73841amC5i7O;[10.129.182.98;21701;10.47.26.80;56645;]tcp;-;0.001408;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521859119.117362;CHIOM73841amC5i7O;[10.129.182.98;21701;10.47.26.80;56645;]tcp;-;0.001408;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521858627.696983;CUAjpN1FXS73841sx4;[10.178.98.167;54563;10.47.8.152;21678;]tcp;-;0.000302;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521858627.696983;CUAjpN1FXS73841sx4;[10.178.98.167;54563;10.47.8.152;21678;]tcp;-;0.000302;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521858627.696983;CUAjpN1FXS73841sx4;[10.178.98.167;54563;10.47.8.152;21678;]tcp;-;0.000302;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521858627.696983;CUAjpN1FXS73841sx4;[10.178.98.167;54563;10.47.8.152;21678;]tcp;-;0.000302;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521853977.951621;CF1px73841wwqzhx1;[10.216.207.9;20776;10.47.25.186;32846;]tcp;-;0.001294;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521853977.951621;CF1px73841wwqzhx1;[10.216.207.9;20776;10.47.25.186;32846;]tcp;-;0.001294;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521853977.951621;CF1px73841wwqzhx1;[10.216.207.9;20776;10.47.25.186;32846;]tcp;-;0.001294;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521853977.951621;CF1px73841wwqzhx1;[10.216.207.9;20776;10.47.25.186;32846;]tcp;-;0.001294;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521851720.232576;CR273841qKJXT2Z0Gl;[10.128.0.225;53939;10.47.3.154;29604;]tcp;-;0.000271;0;0;REJ;-;-;0;Sr;2;88;2;80;-;]
0:[conn;1521851720.232576;CR273841qKJXT2Z0Gl;[10.128.0.225;53939;10.47.3.154;29604;]tcp;-;0.000271;0;0;REJ;-;-;0;Sr;2;88;2;80;-;]
0:[conn;1521851720.232576;CR273841qKJXT2Z0Gl;[10.128.0.225;53939;10.47.3.154;29604;]tcp;-;0.000271;0;0;REJ;-;-;0;Sr;2;88;2;80;-;]
0:[conn;1521851720.232576;CR273841qKJXT2Z0Gl;[10.128.0.225;53939;10.47.3.154;29604;]tcp;-;0.000271;0;0;REJ;-;-;0;Sr;2;88;2;80;-;]
0:[conn;1521851387.050202;Ck73841Jwef1UxYYk5;[10.157.156.128;31597;10.47.21.172;63292;]tcp;-;0.001345;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521851387.050202;Ck73841Jwef1UxYYk5;[10.157.156.128;31597;10.47.21.172;63292;]tcp;-;0.001345;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521851387.050202;Ck73841Jwef1UxYYk5;[10.157.156.128;31597;10.47.21.172;63292;]tcp;-;0.001345;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521851387.050202;Ck73841Jwef1UxYYk5;[10.157.156.128;31597;10.47.21.172;63292;]tcp;-;0.001345;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521850520.224789;CXj73841K2RDbzXyZ6;[10.252.54.106;56651;10.47.27.80;23406;]tcp;-;0.000599;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521850520.224789;CXj73841K2RDbzXyZ6;[10.252.54.106;56651;10.47.27.80;23406;]tcp;-;0.000599;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521850520.224789;CXj73841K2RDbzXyZ6;[10.252.54.106;56651;10.47.27.80;23406;]tcp;-;0.000599;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521850520.224789;CXj73841K2RDbzXyZ6;[10.252.54.106;56651;10.47.27.80;23406;]tcp;-;0.000599;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521848775.616015;Cf73841vdzo0ORs5nk;[10.128.0.235;39306;10.47.24.253;10043;]tcp;-;0.000043;0;0;S0;-;-;0;S;2;120;0;0;-;]
0:[conn;1521848775.616015;Cf73841vdzo0ORs5nk;[10.128.0.235;39306;10.47.24.253;10043;]tcp;-;0.000043;0;0;S0;-;-;0;S;2;120;0;0;-;]
key not found
zapi -s conn-500 get -workers 2 -t "73841"  0.15s user 0.08s system 0% cpu 10:22.72 total
$

**Comment by marktwallace** [comment]
Results with -worker 2 are identical to -workers 1, both terminate with "key not found".

Steve added the "key not found" error message in early November, which after the last time I worked successful with a zar archive for wrccdc/zeek-logs/conn.log.gz

**Comment by marktwallace** [comment]
I ran the same test over again, after your fix, and this time I got a result with no errors.

$ time zapi -s conn-try6 get -workers 10 -t "73841"
Handling connection for 9867
#port=uint16
#zenum=string
#0:record[_path:string,ts:time,uid:bstring,id:record[orig_h:ip,orig_p:port,resp_h:ip,resp_p:port],proto:zenum,service:bstring,duration:duration,orig_bytes:uint64,resp_bytes:uint64,conn_state:bstring,local_orig:bool,local_resp:bool,missed_bytes:uint64,history:bstring,orig_pkts:uint64,orig_ip_bytes:uint64,resp_pkts:uint64,resp_ip_bytes:uint64,tunnel_parents:set[bstring]]
0:[conn;1521933253.146685;C9DP873841kgzEus0k;[10.201.50.237;17639;10.47.21.65;16415;]tcp;-;0.013465;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521930320.138611;CLX73841Eh29ks34i;[10.202.163.124;15120;10.47.44.40;4945;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;80;0;0;-;]
0:[conn;1521929201.360795;Cp0ua73841Mfuk35ng;[10.253.172.70;18122;10.47.43.20;2683;]tcp;-;0.000699;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521926972.96147;Cg73841Clb05Dc0Hpk;[10.168.36.216;14500;10.47.41.20;1073;]tcp;-;0.008974;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521915092.374446;CsXis73841uXeEuOD5;[10.128.0.235;34998;10.47.24.128;35662;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;120;0;0;-;]
0:[conn;1521913226.575198;C9EMv73841waY7Zic5;[10.128.0.227;58253;10.10.1.101;1000;]tcp;-;0.041305;0;0;S0;-;-;0;S;342;21888;0;0;-;]
0:[conn;1521905152.416637;C473841X1Phko7C7Lg;[10.163.143.94;38091;10.47.6.56;80;]tcp;-;0.000972;0;0;REJ;-;-;0;Sr;2;88;2;80;-;]
0:[conn;1521891246.282486;CH973841MdPwwnpZZ1;[10.174.251.215;38980;10.47.27.82;32768;]tcp;-;0.000508;0;0;REJ;-;-;0;Sr;2;88;2;80;-;]
0:[conn;1521875954.14656;CV73841GUIMlauNkck;[10.163.143.94;43480;10.47.3.54;22;]tcp;-;0.001148;0;0;RSTO;-;-;0;ShR;4;168;2;88;-;]
0:[conn;1521859119.117362;CHIOM73841amC5i7O;[10.129.182.98;21701;10.47.26.80;56645;]tcp;-;0.001408;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521858627.696983;CUAjpN1FXS73841sx4;[10.178.98.167;54563;10.47.8.152;21678;]tcp;-;0.000302;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521853977.951621;CF1px73841wwqzhx1;[10.216.207.9;20776;10.47.25.186;32846;]tcp;-;0.001294;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521851720.232576;CR273841qKJXT2Z0Gl;[10.128.0.225;53939;10.47.3.154;29604;]tcp;-;0.000271;0;0;REJ;-;-;0;Sr;2;88;2;80;-;]
0:[conn;1521851387.050202;Ck73841Jwef1UxYYk5;[10.157.156.128;31597;10.47.21.172;63292;]tcp;-;0.001345;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521850520.224789;CXj73841K2RDbzXyZ6;[10.252.54.106;56651;10.47.27.80;23406;]tcp;-;0.000599;0;0;REJ;-;-;0;Sr;2;80;2;80;-;]
0:[conn;1521848775.616015;Cf73841vdzo0ORs5nk;[10.128.0.235;39306;10.47.24.253;10043;]tcp;-;0.000043;0;0;S0;-;-;0;S;2;120;0;0;-;]
0:[conn;1521846025.526976;CWFpoXc73841hz574;[10.198.224.255;51821;10.47.8.56;23646;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;80;0;0;-;]
0:[conn;1521845924.199051;CYd738418AjUo3uXS;[10.128.0.236;45138;10.47.2.118;5211;]tcp;-;0.000043;0;0;S0;-;-;0;S;2;88;0;0;-;]
0:[conn;1521842737.71937;Cnv73841B6zgdjwRX5;[10.128.0.207;48948;10.47.225.172;443;]tcp;-;0.004848;0;0;S0;-;-;0;S;98;4312;0;0;-;]
0:[conn;1521837582.075709;Cg73841CqFWrbjcHIa;[10.128.0.235;37840;10.47.4.226;21684;]tcp;-;0.000002;0;0;S0;-;-;0;S;2;120;0;0;-;]
0:[conn;1521837182.963677;CW73841ndiqqrU3fn5;[10.128.0.235;52782;10.47.4.199;53221;]tcp;-;0.000002;0;0;S0;-;-;0;S;2;120;0;0;-;]
0:[conn;1521837125.900097;CYq738419DDNUFoao;[10.128.0.235;35374;10.47.4.218;1077;]tcp;-;0.000004;0;0;S0;-;-;0;S;2;120;0;0;-;]
0:[conn;1521834923.430526;C173841XshEky3tIEc;[10.128.0.235;39292;10.47.4.188;51851;]tcp;-;0.000091;0;0;S0;-;-;0;S;2;120;0;0;-;]
0:[conn;1521828936.736347;C2B573841QzERJRo6;[10.202.111.195;32819;10.47.5.150;62385;]tcp;-;0.000004;0;0;S0;-;-;0;S;2;80;0;0;-;]
0:[conn;1521826607.418913;CCcJd23B2FZtP73841;[10.142.116.252;15008;10.47.6.50;52021;]tcp;-;0.000002;0;0;S0;-;-;0;S;2;80;0;0;-;]
0:[conn;1490477974.949995;CGt73841Jh8RWc0Px5;[10.192.0.232;51717;172.16.31.6;54294;]tcp;-;0.329962;0;0;REJ;-;-;0;SrR;4;160;2;80;-;]
0:[conn;1490477626.575902;C343Wf2D6sYxz73841;[10.192.72.72;53153;172.16.14.55;41487;]tcp;-;0.000002;0;0;S0;-;-;0;S;2;88;0;0;-;]
0:[conn;1490475359.857804;Cz73841KtIGB9tTWy5;[10.192.76.76;55106;172.16.14.55;9172;]tcp;-;0.000005;0;0;S0;-;-;0;S;2;88;0;0;-;]
0:[conn;1490401442.510101;CQDth738415NGCje41;[10.192.0.227;35269;10.10.1.164;2004;]tcp;-;0.000001;0;0;S0;-;-;0;S;2;88;0;0;-;]
0:[conn;1490388414.222041;C51Bhi2xI59vmQhALj;[10.10.4.21;55666;69.164.202.103;443;]tcp;ssl;10.735276;1056;71617;S1;-;-;0;ShADad;32;2349;55;73841;-;]
0:[conn;1490386633.461976;Cp4wwZpK73841CrF4;[10.192.0.227;56784;10.10.7.68;3269;]tcp;-;0.000005;0;0;S0;-;-;0;S;2;88;0;0;-;]
zapi -s conn-try6 get -workers 10 -t "73841"  0.07s user 0.04s system 0% cpu 3:36.27 total

**Comment by alfred-landrum** [comment]
We're not sure what caused this, but it could be related to the race that was addressed in https://github.com/brimsec/zq/pull/1766 . I'm taking the extra checks & errors from my branch in #1777, and applying just those to the code when mark first saw this (commit 78cc64c) and seeing if I can reproduce the problem.

**Comment by alfred-landrum** [comment]
No luck so far reproducing this - I tried the above commands & with the extra logging on an m5ad.12xlarge & a m5d.xlarge instance.

**Comment by alfred-landrum** [comment]
Closing, as I won't try to spend more time reproducing the problem. As stated above, my hypothesis is that was a symptom of the race that was fixed by #1766 .
