### ISSUE TITLE
SEGV when creating 14GB zar archive

### ISSUE THREAD

**Issue by marktwallace** [brimsec/zq#1759]
I hit another bug when attempting to create an archive similar to the 14GB conn.log I used for issue #1758 .
The archive for 1758 was created with -s 100GB, but for this time, I left off the -s parameter so it would default to 500GB chunks.

On Matt's advice, I set the -bufsize large so it would consistently create large chunks. Instead of finishing after 94 minutes, like 1758, it SEGV's after 84 minutes. I will try again with -bufsize 2GB.

Here is the stack trace:

[ec2-user@ip-172-31-19-39 ~]$ time zar import -bufsize 1000MB -R s3://zqd-demo-1/mark/zeek-logs/conn s3://brim-sampledata/wrccdc/zeek-logs/conn.log.gz
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa44e22]

goroutine 42 [running]:
github.com/brimsec/zq/proc/spill.(*MergeSort).Cleanup(0x0)
	/home/ec2-user/zq/proc/spill/merge.go:53 +0x22
panic(0xd2c400, 0x16e2010)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/brimsec/zq/proc/spill.(*MergeSort).Len(...)
	/home/ec2-user/zq/proc/spill/merge.go:119
github.com/brimsec/zq/proc/spill.(*MergeSort).Read(0x0, 0x0, 0x0, 0x0)
	/home/ec2-user/zq/proc/spill/merge.go:94 +0x26
github.com/brimsec/zq/zbuf.CopyWithContext(0x10b1820, 0xc0000c8b40, 0x109ade0, 0xc0009ce000, 0x109afa0, 0x0, 0x0, 0xc0006e2065)
	/home/ec2-user/zq/zbuf/zbuf.go:59 +0x58
github.com/brimsec/zq/ppl/archive.(*tsDirWriter).flush(0xc0fe4b21e0, 0x0, 0x0)
	/home/ec2-user/zq/ppl/archive/import.go:335 +0x341
github.com/brimsec/zq/ppl/archive.(*Writer).flushStaleWriters(0xc000594680, 0xc000063ec8, 0x2)
	/home/ec2-user/zq/ppl/archive/import.go:159 +0x30b
github.com/brimsec/zq/ppl/archive.(*Writer).flusher(0xc000594680, 0x0, 0x0)
	/home/ec2-user/zq/ppl/archive/import.go:135 +0x12f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0002b6ea0, 0xc000658620)
	/home/ec2-user/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/ec2-user/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66

real	84m5.390s
user	108m56.378s
sys	2m18.821s

**Comment by marktwallace** [comment]
I tried running the -bufsize 2GB, but the process could not allocates all the memory it requested. Not sure why, since the m5d.large ec2 instance had nearly 8GB available. (Maybe something about Golang and very large processes that I do not know yet.)

In any case, this failure is not the same as the SEGV in MergeSort above, and it is not a bug (I think). I'm just including the output here for record of the workarounds I tried.

[ec2-user@ip-172-31-19-39 zq]$ time zar import -bufsize 2GB -R s3://zqd-demo-1/mark/zeek-logs/conn-try5 s3://brim-sampledata/wrccdc/zeek-logs/conn.log.gz
fatal error: runtime: cannot allocate memory

runtime stack:
runtime.throw(0xe5cd70, 0x1f)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.persistentalloc1(0x4000, 0x0, 0x1c6aeb8, 0x2100055c4cb)
	/usr/local/go/src/runtime/malloc.go:1337 +0x2c3
...

**Comment by marktwallace** [comment]
On the 5th try, I was able to create the archive with the command below.
So 1 GB was "not enough" and I hit the bug reported above. 2 GB was "too much" and ran out of memory
on an 8 GB instance (which indicates that maybe -bufsize does not fully reflect the resource consumption).
However, 1.5 GB was "just right" and now I have a 14 GB archive for testing.

[ec2-user@ip-172-31-19-39 zq]$ time zar import -bufsize 1500MB -R s3://zqd-demo-1/mark/zeek-logs/conn-try5 s3://brim-sampledata/wrccdc/zeek-logs/conn.log.gz

real	88m48.464s
user	135m38.207s
sys	2m35.672s

**Comment by mattnibs** [comment]
> I left off the -s parameter so it would default to 500GB chunks.

The default is 500 KB. 500 GB would be immense for a default!

**Comment by mattnibs** [comment]
Looks like the tsdwriter doesn't have the mutex protection that it needs. Two concurrent threads (the write goroutine and the stale goroutine) are attempting to flush at the same time and one sets the spiller to nil before the other can get to it.

Some hubris on my part.
