### ISSUE TITLE
zql const declarations

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1781]
Add zql `const` declarations, presumably with syntax

`const x = y;` (where `y` can be any zql literal, such as `"foo"`, `1.0`, `1 (uint32)`, or `({orig_h:ip, orig_p:port, resp_h:ip, resp_p:port})`)

**Comment by henridf** [comment]
The immediate driver for this is #1782 , for which we need the ability to define const type values, but this is a general ZQL feature so not adding it to that epic.

**Comment by henridf** [comment]
(And if we can skip the trailing semi, as I think we can, then we probably should...)

**Comment by philrz** [comment]
This sounds like a duplicate of #2164, but I'll confirm.
