### ISSUE TITLE
Typed ingest

### ISSUE THREAD

**Issue by orochford** [brimsec/zq#1782]
To date, the data sources for Brim/zq have been "highly curated", starting with Zeek, and more recently Suricata. While we've had preliminary support for reading arbitrary sources such as NDJSON, importing it while restoring rich typing information has been a fairly complex process and in some ways has involved transforming the data to make it more Zeek-like.

**Comment by henridf** [comment]
The goal of this epic is to design and implement a replacement for our current "typed json" feature. Some rough requirements are:

-  Taking input json, classifying it,  and "applying" a zng schema corresponding to the classification result. This should include hierarchical classification and the ability to compose schemas.

In other words, generalize what the existing json types does. In addition:

- Enriching incoming records (for example, add _sourcetype=zeek )
- Renaming fields (for example, rename timestamp to ts)
- Validation

**Comment by philrz** [comment]
The originally envisioned concept of "Typed ingest" is now feature complete, thanks largely to the many issues @henridf closed that are linked to this Epic. The next phase for what's being done in this area is now tracked in #2342 where we plan to iterate on additional debug & work out the corner cases to make "shaping" into a more complete user-facing feature, ultimately revealed through a next-gen experience in the Brim app.
