### ISSUE TITLE
Shaping functions

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1785]
Per https://github.com/brimsec/zq/issues/1783#issuecomment-751790854 and https://github.com/brimsec/zq/issues/1783#issuecomment-754087671

**Comment by philrz** [comment]
For a walk through the shaping functions in action, the best place to look will be the configs that come out of #1871 and #2104 which will serve as reference examples, since the Brim app will ultimately become dependent on them.

**Comment by henridf** [comment]
done in #1984
