### ISSUE TITLE
Switched flowgraph

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1790]
Design and implement a "switch" ZQL construct. A sketch: 

```
... | switch (
    <boolean expression> => ... | ...;
    <boolean expression> => ... | ...;
    ...
    ) | ...
```

Each incoming record is evaluated successively against the list of `<boolean expression>` and is sent into the first RHS flowgraph (after the `=>` arrow) whose expression evaluated to true. The record is dropped if all expressions are false. Output order is the same as input order.

The immediate motivation for this is generic ingest, but this will surely be a broadly useful construct.

**Comment by henridf** [comment]
In a recent discussion on switch syntax, we roughly agreed that:

- switch looks like what is sketched out above (https://github.com/brimsec/zq/issues/1790#issue-761246129)
- the current "implicit split" would become explicit, e.g. `... | ( ..` would now be `... | split ( ...`
- for consistency with `switch`, `split` also uses fat arrows. 

For example:

```
split (
  => count_src=sum(count) by host=id.orig_h | sort host;
  => count_dst=sum(count) by host=id.resp_h | sort host;
) | join host count_dst


switch (
  _path=conn => reshape(zeek_conn_t);
  _path=http => reshape(zeek_http_t);
  true       => pass; // default case
) | ...
```

In another discussion there had been mention of removing the trailing semis. If there's no syntactical ambiguity that seems worthwhile. Let's see once the new expression syntax lands.

**Comment by mccanne** [comment]
Looks great!

**Comment by mccanne** [comment]
I just noticed for split, we don't need the semi-colon separator since nothing can come before the fat arrow.  Should we drop the semi-colon?  Or make it optional for consistency?  Or require it?

**Comment by henridf** [comment]
> I just noticed for split, we don't need the semi-colon separator since nothing can come before the fat arrow. Should we drop the semi-colon? Or make it optional for consistency? Or require it?

I think we should drop the semi-colon, since it is now redundant (there is no syntactical construct where it is needed).  This is unlike e.g. Go where the semi-colon _can_ be required and thus is part of the formal grammar.

**Comment by henridf** [comment]
Without trailing semicolons, the above proposed switch syntax had ambiguity (for example consider `switch ( _path=conn => a=b c=d e=f => put a=1 )`. @mccanne proposed introducing a `case` keyword and the linked PR does that.

```
switch (
  case _path=conn => reshape(zeek_conn_t)
  case _path=http => reshape(zeek_http_t)
  default => pass
) | ...
```

**Comment by philrz** [comment]
Verified in `zq` commit `1ac7787f`. Here's a simple example using the [zq-sample-data](https://github.com/brimsec/zq-sample-data) that shows the final syntax.

```
$ cat /tmp/switch.zs 
head 2 | switch (
  case name='TCP_ack_underflow_or_misorder' => put tldr='underflow'
  case name='truncated_header' => put tldr='truncated'
) | cut uid,name,tldr

$ zq -f table -I /tmp/switch.zs weird.log.gz 
UID               NAME                          TLDR
-                 truncated_header              truncated
C1zOivgBT6dBmknqk TCP_ack_underflow_or_misorder underflow
```

Thanks @henridf!
