### ISSUE TITLE
space time range not updated after pcap import start

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#1797]
In Brim 0.20 , when I drag a large pcap for import into Brim, the time range of the space is set at the very beginning:

![image](https://user-images.githubusercontent.com/704945/101959877-11e3d880-3bbb-11eb-8d29-d461a19841ae.png)

In master, though, that does not occur; the initial time range is much smaller, and doesn't update unless I manually select 'Whole Range' in the time picker:

![image](https://user-images.githubusercontent.com/704945/101960086-7c951400-3bbb-11eb-9831-9f7825c34137.png)

**Comment by philrz** [comment]
Verified in Brim commit `d6f4f77` which talks to `zqd` commit `315c0c7`.

I circled back to witness my own repro of this as of Brim commit `4bef0e7` that talks to `zqd` commit `8c60a42d`. Using the same test pcap as @alfred-landrum I saw slightly different erroneous times locked in at the beginning, but they were indeed quite wrong.

At the beginning:

![image.png](https://images.zenhubusercontent.com/5e40bbae92d04e424a90e56f/f3cb2597-b381-4564-8024-18df028c73db)

After selecting "Whole Space" in the time picker:

![image.png](https://images.zenhubusercontent.com/5e40bbae92d04e424a90e56f/444e052f-6cd9-4880-bc3c-23c6439a98f0)

Now with Brim commit `d6f4f77` which talks to `zqd` commit `315c0c7`, the very first entries shown in the time picker are set to the endpoints of what's observed in the pcap, as things used to be before the bug.

![image.png](https://images.zenhubusercontent.com/5e40bbae92d04e424a90e56f/9465877a-f5f0-4ff7-808b-81ee64529839)

Thanks @alfred-landrum!
