### ISSUE TITLE
use zson reader for ndjson input

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1810]
@henridf interestingly, I figured the zson parser would be slow as it does a parse of source input to AST, then does a semantic pass over the AST to resolve types (generating another tree data structure), then does a zcode build to produce the final zng record. Turns out zq is quite a bit faster at parsing zson than json. After thinking for a sec, I realize the go pattern of using hash tables to represent each JSON object could be the culprit here. Anyway, with a couple flags to the zson reader (i.e., do a column sort for a stable order, unflatten dotted names, treat all numbers as float64, ...), I think it would be fruitful to take this path for the reshaper work. p.s. I think the unflatten step can fit in really easily as part of the semantic pass.

**Comment by henridf** [comment]
We discussed this today and the idea of adding a "json compatibility" mode to the zson reader came up. With such a mode, zson would:
- normalize field order to respect json semantics (as the current ndjson reader does)
- parse all numeric fields to float64
This would avoid records that are of the same type in the json model ending up with different types in Z.

**Comment by mccanne** [comment]
In #2123, I haven't yet made `-i ndjson` use the zson reader but it will now be the default in auto-detection unless a json type config is present.  I think we should keep it this way until we add the json-strict mode described here.

**Comment by philrz** [comment]
Verified in `zq` commit `7ca6e7ec`.

As noted above, one of the ways to see the benefits of this is in a slight performance improvement. For instance, to read and count the [NDJSON zq-sample-data](https://github.com/brimsec/zq-sample-data/tree/master/zeek-ndjson) using the legacy NDJSON reader:

```
$ time zq -i ndjson -f table 'count()' *
COUNT
1462078

real	0m47.405s
user	1m20.418s
sys	0m3.130s
```

By using the auto-detect and hence letting the ZSON reader do the work, we see a slight improvement:

```
$ time zq -f table 'count()' *
COUNT
1462078

real	0m43.902s
user	1m3.133s
sys	0m2.128s
```

Thanks @mccanne!
