### ISSUE TITLE
compiler.Colset can't distinguish .a.b from .["a.b"]

### ISSUE THREAD

**Issue by nwt** [brimsec/zq#1875]
@mccanne pointed out to me that I broke `compiler.Colset`'s ability to distinguish `.a.b` (a top-level record named `a` with a field named `b`) from `.["a.b"]` (a top-level field named `a.b`) in #1845.

**Comment by henridf** [comment]
Maybe we can just get rid of `compiler.Colset`... it seems to have been added prematurely.

**Comment by henridf** [comment]
If Colset is used only by computeColumns, maybe we can just get rid of both as they're unused (looks like they were introduced prematurely).

**Comment by philrz** [comment]
In discussing this one with @mccanne he indicated the code related to this gone and so this issue is no longer relevant. He intends to add a final comment here and close it.

**Comment by nwt** [comment]
#1916 removed compiler.Colset.
