### ISSUE TITLE
Non-deterministic time-sorted aggregation

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#1912]
Repro is with `zqd` commit `4ec48f88`.

Consider the attached Zeek TSV log from the full 70 GB wrccdc data set. These the notorious `smb_mapping` events that include a count of 26 that lack a `ts` timestamp.

[smb_mapping.log.gz](https://github.com/brimsec/zq/files/5754689/smb_mapping.log.gz)

If I import it to a Space and repeatedly execute a time-sorted aggregation, I find the appearance of the row with the null timestamp can sometimes appear in a different location in the output order.

```
$ zapi -version
Version: v0.26.0-23-g4ec48f88

$ zapi new smb
smb: space created

$ zapi -s smb postpath smb_mapping.log.gz 
100.0% 1.14MB/1.14MB
posted 1.14MB in 196.802638ms

$ zapi -s smb get -t 'every 1w count()'
#0:record[ts:time,count:uint64]
0:[1521676800;44121;]
0:[-;26;]
0:[1490227200;2620;]

$ zapi -s smb get -t 'every 1w count()'
#0:record[ts:time,count:uint64]
0:[1521676800;44121;]
0:[1490227200;2620;]
0:[-;26;]
```

Back when I was documenting grouping, @henridf had reminded me of the default reverse-time-ordered nature when the data gets stored into a Space in `zqd`, therefore a user should be able to rely on that time ordering being maintained during a time-based aggregation and hence not have to include an explicit `sort` on `ts`. Those docs are captured at https://github.com/brimsec/zq/tree/master/zql/docs/grouping#note-undefined-order. The behavior observed above runs counter to what's described there, hence I'm treating this as a bug.

incidentally, this is currently affecting our ability to use the Rug automation for correctness tests at scale. With our legacy system we used to drop all incoming records that lacked a timestamp, hence we eliminated those same events from SQL-based reference results as well. However, since `zqd` now stores them, I went to re-allow them in the reference results, but then found the Z-side results now don't consistently match due to this bug. SQL doesn't have this problem since they have a defined treatment of `NULL` which can also be affected by using `ORDER BY ... NULLS FIRST` or `ORDER BY ... NULLS LAST`. Incidentally, we mimicked these options in our own `sort` processor (https://github.com/brimsec/zq/tree/master/zql/docs/processors#sort) but in this case I'm not invoking an implicit `sort`.

To up-level to the wider problem of matching to reference results, it goes without saying that there's other ways we could do this besides addressing the symptom above, e.g.

1. Including an implicit `sort` in the Z query
2. Changing the Z query to exclude the events with null `ts`
3. Have `zqd` start rejecting records with null timestamps like our legacy system used to do
4. Have `zqd` start adding an explicit timestamp at import time in place of the null one (epoch 0, wall clock time, the time of the previously-read event, ...)

etc. It seems like even if we pursued options like 3 & 4 above, it may not be a "one size fits all" answer and hence might require config options and considering the best default. Therefore I figured it makes sense to start from what we have today.

**Comment by philrz** [comment]
Note to self: To get our correctness tests running successfully, for now in https://github.com/brimsec/rug/pull/202 I've opted for the "include an implicit `sort` in the Z query" approach from the list above, for now. If/when this bug gets fixed and I can rely on the records with the null timestamps to appear at a consistent location in the aggregation output, I can circle back and update the test to simplify the Z.

**Comment by mattnibs** [comment]
@philrz it occurs to me that `every [duration]` is a special type of group by. If the input data is sorted (and in lake format it is) we want to release each time bin once the scanner has surpassed the bin's interval. As such timeless points should probably get lopped into their own timeless bin and `every [duration]` should have a deterministic sort.

If the input data is not sorted (and I don't remember how the system will know this) then it should behave exactly like a group by, which (correct me if I'm wrong) should be non-deterministic.

**Comment by mattnibs** [comment]
Ok so the sort proc has this behavior on sorted input where if order is ascending nil values are the max value. When the sorted input is descending, nil values are the min value. The groupby proc was not replicating this behavior:

Whether the input was sorted by ascending order or descending order, the groupby sort would set nil values to max. For ascending inputs this worked fine but for descending inputs,depending if the last batch consisted of both nil ts values and not-nil ts values this would result in the nil ts bin appearing to be released early. 

In descending order if null max is true then really the nil value bins should get released first. Because the sort proc that performs the sort on input for lakestores and filestores always writes nil values at the end, unless there is only one batch in the sort the nil bins get released arbitrarily.

**Comment by philrz** [comment]
Verified in `zqd` commit `aff6efb1`.

Repeating the repro many times, we see the output is consistently the same now.

```
$ zapi -s smb get -f tzng 'every 1w count()' | tee baseline
#0:record[ts:time,count:uint64]
0:[1521676800;44121;]
0:[1490227200;2620;]
0:[-;26;]

$ NUM=1; while true; do   zapi -s smb get -f tzng 'every 1w count()' > compared;   diff baseline compared;   if [ $? -eq 0 ]; then     echo "Same ($NUM)";   else echo "different ($NUM)"; fi; NUM=$(expr $NUM + 1); done
Same (1)
Same (2)
Same (3)
...
Same (616)
Same (617)
...
```

Thanks @mattnibs!
