### ISSUE TITLE
putting to `.` results in empty-named fields

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1932]
This adds a field with value `1` but with an empty name. 

```
$ echo '{ msg: "hello" }' | zq -f zson -i zson "put .=1" -
{
    msg: "hello",
    : 1
} (=0)
```

This should probably be a compile-time error (although if/when we support top-level zng.Values, it might no longer be an error and just output the value `1`).

**Comment by henridf** [comment]
> This should probably be a compile-time error

That said if the RHS is a record, it seems like you'd expect the record's fields to be lifted into the root? For example, on a zeek record, `put .=id` would result in `orig_h, orig_p, resp_h, resp_p` all appearing at the root.

**Comment by henridf** [comment]
> For example, on a zeek record, put .=id would result in orig_h, orig_p, resp_h, resp_p all appearing at the root.

More specifically, they will be the only fields at the root. 
For example, `echo '{"a": 1, "r2": {"b": 1}}' | zq -i zson -t "put .=r2"` should produce `{"b": 1}`.  This is consistent with `put`ing to a non-root record field.

**Comment by philrz** [comment]
Verified in `zq` commit `7d38048c`.

Revisiting the examples cited above, we see that the first one does produce an error as desired.

```
$ echo '{ msg: "hello" }' | zq -f zson -i zson "put .=1" -
put .=x: cannot put a non-record to .
{
    msg: "hello"
} (=0)
```

And for when the RHS is a record, its contents become the only fields at the root, as desired. Using the Zeek [zq-sample-data](https://github.com/brimsec/zq-sample-data):

```
$ zq -f zson 'head 1 | put .=id' conn.log.gz
{
    orig_h: 10.164.94.120,
    orig_p: 39681 (port=(uint16)),
    resp_h: 10.47.3.155,
    resp_p: 3389 (port)
} (=0)
```

Thanks @henridf!
