### ISSUE TITLE
fix type context bug in fuse proc and csv writer

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1953]
While fixing #1942, I noticed that the fuse proc and csv writer create new type contexts, which violates the comment in the flattener.  This creates mixed type-context values, but since nothing downstream currently requires the type-context to be self-contained, the code works. 

We should fix fuse proc and csv writer to take a zctx.  This would be most easily addressed by changing detector.Lookup() to take a zctx that can be passed to writers that require them.

**Comment by henridf** [comment]
I ran into this bug while working on fuse, and noticed it because the shaper (now used by fuse) creates typerecords. By chance or design, it still works, but this should be fixed.
