### ISSUE TITLE
fuse doesn't recurse into nested records

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1959]
`fuse` currently only fuses the top-level of a record.

 As an example, the following three records have different record types, and are fused  into one type:

```
$ cat input.zson
{"left": 1, "right": 2}
{"right": 1, "left": 2}
{"left": 2}
$ zq -i zson -t 'fuse' input.zson 
#0:record[left:float64,right:float64]
0:[1;2;]
0:[4;3;]
0:[5;-;]
```

However, if the same records are nested as below, they are no longer fused into one type, because fusing does not recurse into the nested record as it should. 

```
$ cat input.zson 
{"top": {"left": 1, "right": 2}}
{"top": {"right": 3, "left": 4}}
{"top": {"left": 5}}
$ zq -i zson -t 'fuse' input.zson 
#0:record[top:record[left:int64,right:int64],top_2:record[right:int64,left:int64],top_3:record[left:int64]]
0:[[1;2;]-;-;]
0:[-;[3;4;]-;]
0:[-;-;[5;]]
```

The expected output with a properly recursive fuse would be:

```
$ zq -i zson -t 'fuse' input.zson 
#0:record[top:record[left:int64,right:int64]]
0:[[1;2;]]
0:[[4;3;]]
0:[[5;-;]]
```

**Comment by philrz** [comment]
Verified in `zq` commit `8e4dfe45`.

The output for the lower example shown above now gives the expected output that fuses everything under one schema.

```
$ cat input-nested.zson 
{"top": {"left": 1, "right": 2}}
{"top": {"right": 3, "left": 4}}
{"top": {"left": 5}}

$ zq -i zson -t 'fuse' input-nested.zson 
#0:record[top:record[left:int64,right:int64]]
0:[[1;2;]]
0:[[4;3;]]
0:[[5;-;]]
```

Thanks @henridf!
