### ISSUE TITLE
Add shape aggregator based on fuse

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1965]
For data shape exploration, it is useful to be able to view the union of type descriptors for a set of records.  For example, when coming up with the json type schema for suricata logs, I wrote hacky one-off scripts to do the equivalent of 
 what `fuse (typeof(.)) by alert.signature, alert.category`. Maybe the aggregator will be called `shape` rather than `fuse`.

@mccanne prototype this on a branch, but it had bug https://github.com/brimsec/zq/issues/1959 and stayed unmerged. Once we fix #1959, the aggregator should follow easily.

**Comment by philrz** [comment]
Verified in `zq` commit `7ca6e7ec`.

@henridf tipped me off to a good real-world use case for this aggregator. At the moment, Brim applies a single unifying schema to all Suricata alerts that are generated from imported pcaps. However, we know from observation that certain categories of alert have unique sets of fields. If you wanted to see the unique schemas by category (such as if you wanted to create a shaper config that stored each with its minimal schema), you could do this with an EVE JSON:

```
$ zq -version
Version: v0.29.0-41-g7ca6e7ec

$ zq -f zson 'fuse(alert) by alert.category' eve.json 
{
    alert: {
        category: "Not Suspicious Traffic"
    },
    fuse: ({action:string,gid:int64,signature_id:int64,rev:int64,signature:string,category:string,severity:int64,metadata:{updated_at:[string],former_category:[string],created_at:[string]}})
}
{
    alert: {
        category: "Generic Protocol Command Decode"
    },
    fuse: ({action:string,gid:int64,signature_id:int64,rev:int64,signature:string,category:string,severity:int64})
}
{
    alert: {
        category: "Attempted Administrator Privilege Gain"
    },
    fuse: ({action:string,gid:int64,signature_id:int64,rev:int64,signature:string,category:string,severity:int64,metadata:{updated_at:[string],signature_severity:[string],performance_impact:[string],former_category:[string],deployment:[string],created_at:[string],attack_target:[string],affected_product:[string]}})
}
{
    alert: {
        category: "Unknown Traffic"
    },
    fuse: ({action:string,gid:int64,signature_id:int64,rev:int64,signature:string,category:string,severity:int64,metadata:{updated_at:[string],former_category:[string],created_at:[string]}})
}
{
    alert: {
        category: "Potentially Bad Traffic"
    },
    fuse: ({action:string,gid:int64,signature_id:int64,rev:int64,signature:string,category:string,severity:int64,metadata:{updated_at:[string],signature_severity:[string],former_category:[string],deployment:[string],created_at:[string],attack_target:[string],affected_product:[string]}})
}
{
    alert: {
        category: "Misc activity"
    },
    fuse: ({action:string,gid:int64,signature_id:int64,rev:int64,signature:string,category:string,severity:int64,metadata:{updated_at:[string],former_category:[string],created_at:[string]}})
}
```

Thanks @henridf!
