### ISSUE TITLE
chunk metadata file with incorrect types

### ISSUE THREAD

**Issue by marktwallace** [brimsec/zq#1977]
This occurs on master branch today. 

The commands to produce the error are:

$ zapi new -k archivestore -d s3://brim-scratch/mark/sp-m1 -thresh 5MB sp-m1
...
$ zapi -s sp-m1 post s3://brim-scratch/mark/conn.log.gz
...
$ zapi -s sp-m1 get -workers 2 -t "count()"
incompatible type translation: zng type int64 go type nano.Ts go kind int64

I have only tried this case with a remote zqd with parallel workers, so I am not sure it is also occurs for a local zqd.

The following script (adapted from ./k8s/demo.sh) is what I used to reproduce it:

make install
make helm-uninstall
make docker-push-ecr

make helm-install-postgres PG_PERSIST=false
kubectl wait --for=condition=Ready --timeout=60s pods/postgres-postgresql-0
make helm-install-recruiter
make helm-install-root
make helm-install-worker

sleep 15
./k8s/zqd-port.sh

zapi new -k archivestore -d s3://brim-scratch/mark/sp-m1 -thresh 5MB sp-m1
zapi -s sp-m1 post s3://brim-scratch/mark/conn.log.gz

zapi -s sp-m1 get -workers 2 -t "count()"
zapi -s sp-m1 get -workers 2 -t "39161"

**Comment by alfred-landrum** [comment]
Using mark's existing data, I can see this locally by using zar/zq against the archive. I added a more descriptive error in the chunk metadata read path (which I'll put up as a PR), and once I identified the file in question, I can see the types are not waht I'd expect:

```
12:31 $ zq -t s3://brim-scratch/mark/sp-m1/zd/20180324/m-1l1BMWDjnLMxwaYIfyvoq84KxSF.zng
#0:record[First:int64,Last:int64,RecordCount:uint64,Masks:array[array[uint8]],Size:int64]
0:[1521912137482825000;1521911993784818001;121315;[[12;82;211;105;115;168;87;28;211;55;22;249;133;118;134;37;8;189;166;204;][12;82;211;105;158;114;174;9;0;24;58;195;227;227;253;25;129;11;31;120;][12;82;211;102;152;85;189;148;71;87;185;250;16;136;135;193;109;4;143;100;][12;82;211;99;67;208;87;78;214;124;112;153;252;232;158;89;228;84;50;71;][12;82;211;96;244;158;202;128;30;47;156;240;216;82;45;199;82;171;54;104;][12;82;211;94;197;27;119;173;27;87;163;236;48;98;6;241;170;21;124;4;][12;82;211;90;94;29;60;113;5;116;77;226;120;142;161;172;133;226;19;228;][12;82;211;86;117;38;227;53;28;154;175;84;204;188;60;118;130;129;75;42;][12;82;211;82;102;30;118;178;165;19;235;114;124;173;107;83;30;239;150;182;]]5006653;]
```

Compare the types for First and Last with another file in the same directory that have the expected time type:
```
12:31 $ zq -t s3://brim-scratch/mark/sp-m1/zd/20180324/m-1n60zErlENEN4unEvvYqNMbEGL6.zng
#0:record[First:time,Last:time,RecordCount:uint64,Masks:array[array[uint8]],Size:int64]
0:[1521912036.11726;1521911720.60938;121941;-;5022068;]
```

**Comment by alfred-landrum** [comment]
Ok, I don't think this is a current bug: looking at the file times in Mark's S3 location, all of the metadata files that have 'int64' as a type are from `2020-11-30 08:44:28`. That predates the support to marshal a nano.Ts as a zng time ( https://github.com/brimsec/zq/pull/1743 ), so I suspect what happened is that this location was used to store data in november, and now that we're trying to use it again, the unmarshalling code is complaining.

**Comment by alfred-landrum** [comment]
I put up https://github.com/brimsec/zq/pull/1979 so that the metadata read error would report its path:
```
14:08 $ zar ls
failed to read chunk metadata from s3://brim-scratch/mark/sp-m1/zd/20180324/m-1l1BMWDjnLMxwaYIfyvoq84KxSF.zng: incompatible type translation: zng type int64 go type nano.Ts go kind int64
```

**Comment by marktwallace** [comment]
The improved error message will make is easier to diagnose this if it happens again.

I fixed the test in my branch by adding a line:
aws s3 rm --recursive s3://brim-scratch/mark/sp-m1/zd
To clear out the older data. I misunderstood the behavior of zapi post, and assumed that the more recent runs would overwrite the previously imported archive.

**Comment by alfred-landrum** [comment]
> The improved error message will make it easier to diagnose this if it happens again.

agreed, I'm glad you reported this!

> I fixed the test in my branch by adding a line:
> aws s3 rm --recursive s3://brim-scratch/mark/sp-m1/zd
> To clear out the older data. I misunderstood the behavior of zapi post, and assumed that the more recent runs would overwrite the previously imported archive.

@marktwallace : fyi, you should remove all of the contents of the sp-m1 "folder", as there's also the 'zar.json' file, the 'indexdefs', etc. entries in addition to 'zd'.
