### ISSUE TITLE
proc.Function.Apply drops batch upon evaluation error

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1982]
With `put`, if an expression results in an error, the corresponding record is dropped, a warning is output, and processing continues:

```
$ echo '{"stringip": "1.bad"} {"stringip": "1.1.1.1"}' | zq -t -i zson "put ip=stringip:ip | cut ip" -
bad cast
#0:record[ip:ip]
0:[1.1.1.1;]
```
but with `cut` (which uses proc.applier), the entire batch is dropped:

```
$ echo '{"stringip": "1.bad"} {"stringip": "1.1.1.1"}' | zq -i zson -t "cut ip=stringip:ip " -
bad cast
```

**Comment by nwt** [comment]
For the record (ha!),`put` doesn't drop the record. You can see this if you remove `| cut ip` from the first example, which was `put ip=stringip:ip | cut ip`.
```
$ echo '{"stringip": "1.bad"} {"stringip": "1.1.1.1"}' | ./dist/zq -t -i zson "put ip=stringip:ip" -
bad cast
#0:record[stringip:string]
0:[1.bad;]
#1:record[stringip:string,ip:ip]
1:[1.1.1.1;1.1.1.1;]
```
