### ISSUE TITLE
reduce source wait time for archive queries

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#2017]
A possible reason we hit #1997 was that we were waiting a longer than expected time for a source to be created and pushed onto the source channel in `spanMultiSource.SendSources`, due the time needed to perform the tsDir walking operation. That involves performing list operations against S3 and reading chunk metadata files to create the list of files to read for a query. We already have caching work in progress that will help with the chunk metadata file access, and we have plans to work on caching the directory lookup operations as well.

This issue tracks two additional ways we can reduce the wait time:
* we can use channel buffering or some similar technique to generate the sources ahead of time, before a worker needs to wait on the source channel. I think that just adding a buffer capacity to the `chan Source` is not sufficient, since a Source is a single file in a tsDir, and I think we should try to 'readahead' an entire tsDir's worth of Chunks.
* We should also be able to parallelize most of the work in `tsDirVisit`, most easily the part that reads the metadata files to create the Chunk structs, and with a little more care the reading of the tsDir entries, given the ordering guarantee.

**Comment by alfred-landrum** [comment]
I added the buffering I mentioned above in #2019, and am handing over to @mattnibs to handle the tsDirVisit parallelization.

**Comment by philrz** [comment]
Verified in `zar` commit `1ac7787f`.

As described in the linked PR, a decent test data set is the oft-cited "corelight" data set, which is first imported from my laptop into an archive on S3.

```
$ zq * | zar import -R s3://phil-scratch-us-east-2/archive -s 25MB -
```

Going back to `zq` commit `10c789a2` that comes right before the changes in the linked PR, we see it consistently takes 11+ seconds to complete a `zar stat` of the archive.

```
$ zar -version
Version: v0.29.0-53-g10c789a2

$ time zar stat -R s3://phil-scratch-us-east-2/archive > /dev/null
real	0m11.415s
user	0m0.454s
sys	0m0.312s

$ time zar stat -R s3://phil-scratch-us-east-2/archive > /dev/null
real	0m11.640s
user	0m0.363s
sys	0m0.244s

$ time zar stat -R s3://phil-scratch-us-east-2/archive > /dev/null
real	0m11.712s
user	0m0.377s
sys	0m0.240s
```

But at `zar` commit `1ac7787f`, the same operation is more than 2x faster.

```
$ zar -version
Version: v0.29.0-59-g1ac7787f

$ time zar stat -R s3://phil-scratch-us-east-2/archive > /dev/null
real	0m4.942s
user	0m0.426s
sys	0m0.212s

$ time zar stat -R s3://phil-scratch-us-east-2/archive > /dev/null
real	0m4.638s
user	0m0.507s
sys	0m0.288s

$ time zar stat -R s3://phil-scratch-us-east-2/archive > /dev/null
real	0m4.652s
user	0m0.522s
sys	0m0.298s
```

Thanks @mattnibs!
