### ISSUE TITLE
ip in subnet

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#2045]
You should be able to use the `in` operator with IP addresses and subnets.
e.g.,
```
10.1.1.2 in 10.0.0.0/8
```
should be true just as this is currently true:
```
10.1.1.2 in [ 10.1.1.2, 10.1.1.3 ]
```
(the array literal syntax is not yet implemented but if this were a value in a zng record it should currently work)

though it seems this should be false...

```
10.1.1.2 in [ 10.0.0.0/8, 11.0.0.0/8 ] 
```
while this is true 
```
10.0.0.0/8 in [ 10.0.0.0/8, 11.0.0.0/8 ] 
```

If you want to check if an address is in a list of subnets then you would use 
```
[ 10.0.0.0/8, 11.0.0.0/8 ].map(10.1.1.2 in $)
```
(this syntax is coming soon)

**Comment by henridf** [comment]
> [ 10.0.0.0/8, 11.0.0.0/8 ].map(10.1.1.2 in $)

I suppose this would return a map `[true, false]`... will there also be something like `[ ].reduce(..)` ?

**Comment by philrz** [comment]
Verified in `zq` commit `03076fb7`.

Here's a simple example that uses this to populate a boolean field that captures whether an IP address stored in one field is within the CIDR net stored in another field.

```
$ cat within.zson 
{
    subnet: 192.168.1.0/24,
    addr: 192.168.1.5
} (=0)
{
    subnet: 192.168.1.0/24,
    addr: 192.168.2.5
} (0)

$ zq -f table -i zson 'put within=addr in subnet' within.zson 
SUBNET         ADDR        WITHIN
192.168.1.0/24 192.168.1.5 T
192.168.1.0/24 192.168.2.5 F
```

Thanks @mccanne!
