### ISSUE TITLE
Unexpected output format of nulls casted to strings in ZSON

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#2065]
Repro is with `zq` commit `2294ca24`.

Based on my understanding of the ZSON spec, this representation of a `null` value of type `string` looks correct.

```
$ echo '{"foo": null}' | zq -f zson -
{
    foo: null (string)
} (=0)
```

However, if I use `put` to create an additional `null` field while using casting to assign `string` as its explicit type, it's rendered as a hyphen.

```
$ echo '{"foo": null}' | zq -f zson 'put bar=null:string' -
{
    foo: null (string),
    bar: "-"
} (=0)
```

If I grab the null value from the named field and apply the cast (which is unnecessary here, but let's say I wanted to be sure), it shows up as an empty string.

```
$ echo '{"foo": null}' | zq -f zson 'put bar=foo:string' -
{
    foo: null (string),
    bar: ""
} (=0)
```

**Comment by mccanne** [comment]
This is a generic problem in the casting logic not specific to ZSON.

PR up in a sec.

**Comment by philrz** [comment]
Verified in `zq` commit `e2814fca`.

Revisiting the two repro examples, now they both show the correct expected output.

```
$ echo '{"foo": null}' | zq -f zson 'put bar=null:string' -
{
    foo: null (string),
    bar: null (string)
} (=0)

$ echo '{"foo": null}' | zq -f zson 'put bar=foo:string' -
{
    foo: null (string),
    bar: null (string)
} (=0)
```

Thanks @mccanne!
