### ISSUE TITLE
Stripping subdomains out of DNS request queries

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#2092]
A community user asked on [Slack](https://brimsec.slack.com/archives/CTT24051C/p1612721562014800):

> Is there anyway to manipulate the query string with zql? I am trying to strip the subdomains out of DNS requests queries
> 
> I am trying to reproduce this command inside of brim:
> ```
> cat dns*.log | zeek-cut query| sort | uniq | rev | cut -d . -f 1-2 | rev | sort | uniq -c | sort -rn
> ```

We have existing Z issues that, when addressed, should combine to make this possible.

**Comment by mccanne** [comment]
I have this working on the `slice` branch now (with the bug fix PR that is pending)...
```
by query=cut(query):string | cut join(split(query,".")[0:-1],".")
```
I think this does what the above unix filter is intended to do.

There's a bug in split I think that requires the string cast.  Need to fix this...

**Comment by mccanne** [comment]
Here's a shorter version...
```
by name=join(split(query:string,".")[0:-1],".")
```

**Comment by philrz** [comment]
This is now working as of `zq` commit `bdbef8b2`. Here's an example we [just shared with the original community user back on Slack](https://brimsec.slack.com/archives/CTT24051C/p1613060867024100?thread_ts=1612721809.014900&cid=CTT24051C) that uses the [zq-sample-data](https://github.com/brimsec/zq-sample-data):

```
$ zq -f table 'cut query | sort | uniq | count() by portion=join(split(query,".")[-2:],".") | sort -r | head 5' dns.log.gz
PORTION          COUNT
in-addr.arpa     239
steamcontent.com 67
google.com       51
microsoft.com    39
akamaiedge.net   29
```

Which compares to the user's original:

```
$ gzcat dns.log.gz | zeek-cut query| sort | uniq | rev | cut -d . -f 1-2 | rev | sort | uniq -c | sort -rn | head -5
 239 in-addr.arpa
  67 steamcontent.com
  51 google.com
  39 microsoft.com
  29 akamaiedge.net
```
