### ISSUE TITLE
make slice more efficient

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#2099]
This slice expression currently copies the zng.Values of the array into a second buffer.  This code could be a big more efficient by simply identify the slice boundary in the input zcode.Bytes and using the byte slice pointing into this buffer for the output value.

**Comment by philrz** [comment]
Verified in `zq` commit `bdbef8b2`.

Here's an example in the context of the use case described in #2092:

```
$ echo '{"query": ["www", "brimsecurity", "com"]}' | zq -f ndjson 'put portion=query[-2:]' -
{"portion":["brimsecurity","com"],"query":["www","brimsecurity","com"]}
```

Those needing a general overview of what's possible with slices can hopefully make sense of the [Go examples](https://tour.golang.org/moretypes/7).

Support for slicing in other Z data types like strings and bytes is still an open topic tracked in #1421.

Thanks @mccanne!
