### ISSUE TITLE
type values need to be checked

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#2127]
Type values need to be checked when parsed by tzngio.  Right now, bad type values can get in.  They should be checked by looking them up using the zson parser.

```
zq -f zson in.tzng
```

in.tzng:

```
#0:record[t:type]
0:[;]
```

The zson generated from this is illegal and can't be parsed because an empty string gets put into the zcode.Bytes of `t`

**Comment by philrz** [comment]
This is being closed because it's obsolete, given the push to phase out TZNG in favor of ZSON.
