### ISSUE TITLE
panic when putting non-record to .

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#2135]
$ zq -t "put .=key" input.tzng 
put .=x: cannot put a non-record to .
panic: put: unexpected step 0
goroutine 36 [running]:
runtime/debug.Stack(0xc0003a9ae8, 0xc0003a9ab8, 0x15a2869)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/brimsec/zq/zqe.RecoverError(0x17f3a60, 0xc000386180, 0xc000386180, 0x17f2520)
        /Users/henridf/work/brim/zq/zqe/error.go:163 +0x26
github.com/brimsec/zq/driver.(*mux).safeGet.func1(0xc0003a9f70)
        /Users/henridf/work/brim/zq/driver/mux.go:49 +0x48
panic(0x17f3a60, 0xc000386180)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/brimsec/zq/proc/put.step.build(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0003ac101, 0xd, 0xf, 0xc00038e0a8, ...)
        /Users/henridf/work/brim/zq/proc/put/put.go:126 +0x33f
github.com/brimsec/zq/proc/put.(*Proc).put(0xc00038e090, 0xc0003940f0, 0xc0003940f0, 0x0, 0x0)
        /Users/henridf/work/brim/zq/proc/put/put.go:355 +0x185
github.com/brimsec/zq/proc/put.(*Proc).Pull(0xc00038e090, 0x0, 0x0, 0x0, 0x0)
        /Users/henridf/work/brim/zq/proc/put/put.go:369 +0x15f
github.com/brimsec/zq/driver.(*mux).safeGet(0xc0003840e0, 0x0, 0x0, 0x0, 0x0)
        /Users/henridf/work/brim/zq/driver/mux.go:51 +0x6c
github.com/brimsec/zq/driver.(*mux).run(0xc0003840e0)
        /Users/henridf/work/brim/zq/driver/mux.go:64 +0x32
created by github.com/brimsec/zq/driver.(*muxOutput).Pull.func1
        /Users/henridf/work/brim/zq/driver/mux.go:98 +0x5d

**Comment by philrz** [comment]
I've partially verified this in `zq` commit `9506d27`.

The attached PR describes how "putting a non-record to `.` is [now] a fatal error (similar to `cut` behavior)". Indeed, I can see this change by using the test file from the attached PR. As of `zq` commit `68ecb8b5` that came right before the change in the linked linked PR, there was an error message and the record was still output.

```
$ cat a.tzng 
#0:record[a:int32]
0:[1;]

$ zq -version
Version: v0.29.0-27-g68ecb8b5

$ zq -t 'put .=a' a.tzng 
put .=x: cannot put a non-record to .
#0:record[a:int32]
0:[1;]
```

Then at  `zq` commit `9506d27` that's associated with the linked PR, we see the error, but no output, which is a reflection of the intended behavior of treating it as a fatal error (per the linked PR: "making such errors be non-fatal is #1429")

```
$ zq -t 'put .=a' a.tzng 
put .=x: cannot put a non-record to .
```

However, what I can't seem to repro/verify is the panic. The opening text of this issue didn't happen to mention a commit or point to specific test data. As shown above, the test data from the linked PR doesn't produce a panic when run against a `zq` commit that pre-dates the fix, and indeed I tried with that test data and several other commits going back to the last tagged GA release `v0.29.0` and never saw a panic, so I guess there was something unique to the original repro.
