### ISSUE TITLE
add constants to Z (and constant types)

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#2164]

**Comment by philrz** [comment]
Verified in `zq` commit `1ac7787f`.

It's expected that constants will often be used in conjunction with the recently-added `-I` option. A simple example:

```
$ cat myconsts.zs 
const PI=3.14159

$ echo '{"radius": 5}' | zq -f table -I myconsts.zs 'put circ=PI*radius*2' -
RADIUS CIRC
5      31.4159
```

Thanks @mccanne!
