### ISSUE TITLE
support complex expressions like `put x={a:1+3, b:len(foo)}`

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#2183]
We should add support for complex expressions for records, arrays, sets, maps, etc.  We could start with records and arrays like javascript. 

The syntax for records is 
```
{ <field> : <expr>, <field> : <expr> , ... }
```
The syntax for arrays is 
```
[ <expr>, <expr> , ... ]
```
etc

The runtme would have new expression ast nodes and new expr Evaluators that would evaluate each expression, build the zcode, and look up the zng.Type to form the zng.Value.

This is not particularly difficult at this point given all the progress on the software architecture.

**Comment by philrz** [comment]
Verified in `zq` commit 45ac6b4.

Cooking up an example like the one in the issue title:

```
$ echo '{"foo": [2,4,6]}' | zq -z 'put x={a:1+3, b:len(foo)}' -
{foo:[2,4,6],x:{a:4,b:3}}
```

The linked PR has many advanced examples in its tests, but here's some examples of simple use of literals for matching.

```
$ echo '{"foo": [2,4,6]}' | zq -z 'foo=[2,4,6]' - 
{foo:[2,4,6]}

$ echo '{"foo": [2,4,6]}' | zq -z 'foo=[2,4]' -
[no output, since it was not an exact match]

$ echo '{"nested": {"foo": "bar", "num": 123 }}' | zq -Z 'nested={foo: "bar", num: 123}' -
{
    nested: {
        foo: "bar",
        num: 123
    }
}

$ echo '{"nested": {"foo": "bar", "num": 123 }}' | zq -Z 'nested={foo: "bar", num: 456}' -
[no output, since it was not an exact match]
```

Previously (such as at `zq` commit ec3250b) these were all just parse errors.

```
$ zq -version
Version: v0.29.0-160-gec3250b8

$ echo '{"foo": [2,4,6]}' | zq -z 'put x={a:1+3, b:len(foo)}' -
zq: parse error: error parsing Z at column 10:
put x={a:1+3, b:len(foo)}
     === ^ ===

$ echo '{"foo": [2,4,6]}' | zq -z 'foo=[2,4,6]' - 
zq: parse error: error parsing Z at column 6:
foo=[2,4,6]
 === ^ ===

$ echo '{"nested": {"foo": "bar", "num": 123 }}' | zq -Z 'nested={foo: "bar", num: 123}' -
zq: parse error: error parsing Z at column 14:
nested={foo: "bar", num: 123}
         === ^ ===
```

Thanks @mccanne!
