### ISSUE TITLE
resilient typedefs

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#2202]
Currently, it is an error in the zson/zng spec and code to redefine a type name.   This should be relaxed though discouraged so that type conflicts can be accommodated and the ZSON stream remains valid.  A Z query will continue to operate just fine with a changed type stream... it just might not do what the user expects.  The enforcement of a type name scheme in which type name changes are rejected is left outside the scope of the Z data model, type system, and specifications.

**Comment by philrz** [comment]
Closing as a duplicate of #1568.
