### ISSUE TITLE
zq erroring on zeek named log files

### ISSUE THREAD

**Issue by robertstrom** [brimsec/zq#2234]
Hello,

I am just getting started with playing around with zq and I believe I am running into an error that I don't believe I should be seeing.

Below is a sample of the same command run against a zeek named file with this name http.06:28:42-07:00:00.log.gz 

When I run the command based on one of your examples

zq -f tzng 'count() by host | sort count,host' http.06\:28\:42-07\:00\:00.log.gz

It errors as shown below

If I change the file name from the original file name to http_logs.log.gz and then run the same command it works.

`rstrom@ubuntu-arm-zeek:~/zeek_logs$` `zq -f tzng 'count() by host | sort count,host' http.06\:28\:42-07\:00\:00.log.gz`
http.06:28:42-07:00:00.log.gz: unknown scheme: "http.06"
`rstrom@ubuntu-arm-zeek:~/zeek_logs$` `cp http.06\:28\:42-07\:00\:00.log.gz http_logs.log.gz`
`rstrom@ubuntu-arm-zeek:~/zeek_logs$` `zq -f tzng 'count() by host | sort count,host' http_logs.log.gz` 
#0:record[host:bstring,count:uint64]
0:[d.joinhoney.com;1;]
0:[edge.microsoft.com;1;]
0:[enterprise.activity.windows.com;1;]
0:[fls-na.amazon.com;1;]
0:[ncsi.qnap.com;1;]
0:[ocsp.apple.com;1;]
0:[plex.tv;1;]
0:[self.events.data.microsoft.com;1;]
0:[storage.googleapis.com;1;]
0:[storage.live.com;1;]
0:[www.bing.com;1;]
0:[www.msftconnecttest.com;1;]
0:[a.fc.namequery.com;2;]
0:[pac.zscalertwo.net;2;]
0:[settings-win.data.microsoft.com;2;]
0:[unitedstates.cp.wd.microsoft.com;2;]
0:[192.168.0.7;3;]
0:[192.168.0.75;3;]
0:[192.168.0.99;3;]
0:[my-epmlb.aternity.com;3;]

This error makes it pretty hard to run commands like this one of your examples

zq -f table '/www.google(ad|tag)services.com/' *.log.gz

rstrom@ubuntu-arm-zeek:~/zeek_logs$ zq -f table '/www.google(ad|tag)services.com/' *.log.gz
conn.06:04:13-07:00:00.log.gz: unknown scheme: "conn.06"

I have tried putting single quotes around the file names. I have tried putting double quotes around the file names. Neither of these seem to solve the problem.

Please advise.

Thanks,

Robert

**Comment by alfred-landrum** [comment]
Hi @robertstrom : Thanks for reporting this, it's a bug in how we examine input paths & attempt to determine if they are file paths or urls. We'll work on addressing this.

In the meantime, a workaround is to specify the paths as `file:///...` urls:

```
$ ls -l
total 540104
-rw-r--r--  1 alfred  staff  276532334 Feb 26 07:54 dns.06:28:42-07:00:00.log.gz
$ zq -z "count()" dns.06\:28\:42-07\:00\:00.log.gz
dns.06:28:42-07:00:00.log.gz: unknown scheme: "dns.06"

# Specify a single file as 'file:///' url with an absolute path:
$ zq -z "count()" file:///Users/alfred/tmp/t/dns.06\:28\:42-07\:00\:00.log.gz
{count:7357592 (uint64)} (=0)

# Or make globbing work:
$ zq -z "count()" $(for i in *.log.gz ; do echo file:///$(pwd)/$i ; done)
{count:7357592 (uint64)} (=0)
```

**Comment by philrz** [comment]
Verified in `zq` commit 8aade97.

Just to briefly revisit the repro, circling back to commit 12233ad that was right before the fix in the linked PR, I could trigger the issue by renaming a file from the [zq-sample-data](https://github.com/brimsec/zq-sample-data) to the filename in the original bug report.

```
$ cp ~/work/zq-sample-data/zeek-default/http.log.gz ./http.06:28:42-07:00:00.log.gz

$ zq -version
Version: v0.29.0-83-g12233adf

$ zq -f tzng 'count() by host | sort count,host' http.06:28:42-07:00:00.log.gz
http.06:28:42-07:00:00.log.gz: unknown scheme: "http.06"
```

Repeating the same now at `zq` commit 8aade97:

```
$ zq -version
Version: v0.29.0-84-g8aade975
13:32:38-phil@PhilMac:~/work/zq-2234$ zq -f tzng 'count() by host | sort count,host' http.06:28:42-07:00:00.log.gz
#0:record[host:bstring,count:uint64]
0:[0988253c66242502070643933dd49e88.clo.footprintdns.com;1;]
0:[10.47.21.1;1;]
0:[10.47.21.80/..;1;]
...
```

Thanks @mattnibs!

**Comment by robertstrom** [comment]
I see it. I will update and test as soon as I can.

Thanks for the fix. Much appreciated!

Robert
