### ISSUE TITLE
Add unflatten Z function

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#2239]
Just like we moved shaping functionality from ad hoc sideshows (types.json) to Z, we should add `unflatten()` to Z so that it can be done as part of a Z shaper script rather than in readers.

---
### Side commentary from @philrz

From a user-facing perspective, "unflatten" in this context refers to what we've traditionally done with turning dot-separated field names back into nested records, due to our Zeek-centric roots. This behavior is still currently the default with explicit `-i ndjson`:

```
$ zq -version
Version: v0.29.0-71-g5cd41763

$ echo '{"a.b": 1}' | zq -f zson -i ndjson -
{
    a: {
        b: 1.
    }
}
```

However, in the recently-added NDJSON ingest that's done via auto-detect, it's not currently the default:

```
$ echo '{"a.b": 1}' | zq -f zson -
{
    "a.b": 1
}
```

**Comment by philrz** [comment]
Verified in `zq` commit f93774d.

What's stated above is still true about _not_ unflattening by default in auto-detect mode:

```
$ zq -version
Version: v0.29.0-94-gf93774d0

$ echo '{"a.b": 1}' | zq -f zson -
{
    "a.b": 1
}
```

However, this can be achieved via the newly-added `unflatten()` function.

```
$ echo '{"a.b": 1}' | zq -f zson 'put .=unflatten()' -
{
    a: {
        b: 1
    }
}
```

Thanks @henridf!
