### ISSUE TITLE
consts not carried into kernel.Filter

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#2261]
This fails because the const is not carried into the filter AST in kernel.Filter.
```
zql: const t = {a:string} ; is(t)

input: |
  {a:"hello"}
  {a:2}
  {a:"world"}
output: |
  {a:"hello"}
  {a:"world"}
```

**Comment by philrz** [comment]
Verified in `zq` commit f93774d.

Revisiting the original repro steps, at `zq` commit 6dab8a0 that was right before the changes in the linked PR, indeed, it failed, showing no output.

```
$ cat input.zson 
{a:"hello"}
{a:2}
{a:"world"}

$ zq -version
Version: v0.29.0-88-g6dab8a0e

$ zq -z 'const t = {a:string} ; is(t)' input.zson 
[no output]
```

Now at `zq` commit `f93774d0`, it returns the records where `a` is a string.

```
$ zq -version
Version: v0.29.0-94-gf93774d0

$ zq -z 'const t = {a:string} ; is(t)' input.zson 
{a:"hello"}
{a:"world"}
```

Thanks @mccanne!
