### ISSUE TITLE
Configure cloudwatch for EKS application logs

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#2274]
We need a centralized persistent storage & searching for our EKS application logs. Of course, the best long term solution is to use zqd & Brim, but we need an initial solution while we're getting the cloud service running. Cloudwatch seems like the best short to mid term solution for our EKS based cluster. And, Cloudwatch supports exporting to S3, so once we're ready, we can begin ingesting the logs from S3 into a Brim viewable space.

**Comment by mattnibs** [comment]
This helm chart looks promising.
