### ISSUE TITLE
shaper with map literals

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#2321]
We should maybe do something like this...
```
type conn_type = { _path: string, ...}
const typemap = { conn: conn_type, 
                  dns: dns_type, ...}

switch (
  case _path in typemap => put . = shape(typemap[_path])
  default => // drop or add error message etc
)
```

**Comment by philrz** [comment]
This is effectively verified via the changes in #2448 that simplifies the Zeek reference shaper at https://github.com/brimdata/zq/blob/main/zeek/shaper.zed to use the approach with map literals.

Thanks @mccanne!
