### ISSUE TITLE
proper support for RFC-3339 durations

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#2357]
Golang's time.Duration does not support days, weeks, months etc.  We need to either implement our own parser or find a library that support RFC-3339.

**Comment by mccanne** [comment]
We decided to follow Prometheseus duration syntax instead of RFC-3339 but extend it with us and ns.

**Comment by philrz** [comment]
Verified in `zq` commit c8c8456.

The changes in #2396 updated the table in the docs at [https://github.com/brimsec/zq/tree/master/zql/docs/grouping#time-grouping---every](https://github.com/brimsec/zq/tree/master/zql/docs/grouping#time-grouping---every) with the full new set of valid duration units. Per the docs examples, here's a sampling of a couple of them at work with the [zq-sample-data](https://github.com/brimsec/zq-sample-data):

```
$ zq -f table 'every 0.5m count() | sort -r count' *.log.gz
TS                   COUNT
2018-03-24T17:19:00Z 73512
2018-03-24T17:16:30Z 59701
2018-03-24T17:20:00Z 51229
2018-03-24T17:18:30Z 50949
...

$ zq -f table 'every 1m30s max(id.resp_p) | sort -r ts' conn.log.gz
TS                   MAX
2018-03-24T17:36:00Z 60008
2018-03-24T17:34:30Z 60008
2018-03-24T17:33:00Z 65389
2018-03-24T17:31:30Z 62357
...
```

Thanks @mccanne!
