### ISSUE TITLE
Optimize searches based on time using a time index

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#498]
@mccanne ​has a branch that implements the scanning part of this.  This depends on the work in https://github.com/brimsec/zq/issues/499.

**Comment by alfred-landrum** [comment]
For the scope of this issue, we want to speed up the single bzng file search that exists in Brim right now. In the future (possibly very near future), we're going to work through how this would expand for multi-file spaces, as we're prototyping with zar now.

**Comment by aswan** [comment]
Fixed in #579.  Note that this isn't yet used by zqd, filed #595 as a follow-up to integrate it into zqd.
