### ISSUE TITLE
Case-insensitive searches

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#509]
The `zq` engine (and hence the searches performed in the Brim app that rely on it) has up until now treated all searches as case sensitive. So for example:

```
$ cat hostnames.ndjson 
{"hostname": "Facebook.com"}
{"hostname": "facebook.com"}

$ zq -f table "facebook" hostnames.ndjson 
HOSTNAME
facebook.com
```

We recognize that most search tools users are already familiar with are case-insensitive by default, so this issue captures our intent to change our behavior to match that expectation.

Once we flip the default behavior,  we should likely offer a way that users can specify if they want some portion of their search to still be matched in a case-sensitive way.

Whatever approach we offer users to do that should be designed to accommodate a related enhancement we may add in the future (doesn't have to be now, as the demand for it has not been as strong): Case-insensitive aggregations. Revisiting the example above:

```
$ zq -f table "count() by hostname" hostnames.ndjson 
HOSTNAME     COUNT
Facebook.com 1
facebook.com 1
```

We may want to similarly flip the default behavior to get a count of 2 here, and hopefully the syntax we come up to invoke case-sensitivity in the search context could be repurposed here when that becomes a priority.

**Comment by philrz** [comment]
Note: @mikesbrown needs to be kept in the loop on this one so he can make early plans for how it's going to affect testing. One specific he pointed out:

> Will enums be case insensitive? While they are different Zeek types from strings, a user of our system doesn’t seem to currently interact with in a sort of enum-way.

**Comment by aswan** [comment]
Just throwing out some thoughts:
Making the default search behavior be case insensitive seems like a no-brainer.  For case-sensitive searches, I think we could either make strings in quotes be case-sensitive (so a search for `facebook.com` would match `Facebook.COM` but a search for `"facebook.com"` would not).  Or we could just forget case-sensitive searches and have people use something more specific like a wildcard field match to get case-sensitivity.

For direct comparisons, we're talk about adding a new operator such as `=~` for doing pattern matching (e.g., `field =~ /regexp/`) we could have `string1 = string2` be case sensitive and `string1 =~ string2` be case insensitive.

As for groupbys, if we changed the grouping clause to be an arbitrary expression then we could do something like `count() by Strings.tolower(host)`.  Incidentally that would enable other unrelated things like `count() by len(vector)`  That would work for case insensitive grouping but its not very ergonomic.

Thoughts and other suggestions welcome...

**Comment by aswan** [comment]
We have #534 for the `=~` operator and #535 for groupby.  I'm going to narrow this to just make searches case insensitive.

**Comment by philrz** [comment]
Verified in `zq` commit `87135a9`.

Revisiting the original search example, now a bare search matches both hostnames.

```
# zq -f table 'facebook' hostnames.ndjson 
HOSTNAME
Facebook.com
facebook.com
```

Quoted searches are also treated this way at the moment, which seems fine.

```
# zq -f table '"facebook.COM"' hostnames.ndjson
HOSTNAME
Facebook.com
facebook.com
```

Searches against named fields are still case-sensitive, which also seems fine.

```
# zq -f table 'hostname=facebook.com' hostnames.ndjson
HOSTNAME
facebook.com
```

Per @aswan's comments above, we have  #534 tracking variations on this behavior involving the proposed `=~` operator with named fields and #535 that would provide a way to affect case sensitivity in group-by operations.

Thanks @aswan!
