### ISSUE TITLE
Bare searches should match on field names

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#511]
Currently bare searches match on field values, but not field names. For example:

```
$ echo '{"foo": "bar"}' | zq "bar" -
#0:record[foo:string]
0:[bar;]

$ echo '{"foo": "bar"}' | zq "foo" -
[no output]
```

Other search tools that users are accustomed to using would often match in the second case as well. To meet user expectations, we should do the same.

It seems like once we do this, we already have a syntax for users to express a desire to match _only_ on field values. In this example it would be:

```
$ echo '{"foo": "bar"}' | zq "*=bar" -
#0:record[foo:string]
0:[bar;]
```

**Comment by aswan** [comment]
In the case where the search term matches a field name, should we emit every record that has that named field?  That could be extremely large...
I guess we should start by doing that and can refine later if its a problem.

**Comment by philrz** [comment]
@aswan: Yes, we should just emit them all for now. We've generally adopted the stance that we should let bare searches return anything that _might_ be perceived as a match, and once the user sees what the hits are, it will help them make up their mind how to further narrow it on a subsequent search.

For instance, one user who floated this topic had typed "RDP" in all caps as a search term because they were looking for events involving Windows Remote Desktop traffic, hence expecting the Zeek events of the `_path=rdp` variety to show up in the output. Their search for "RDP" matched none of those, but did get the much-less-interesting hits where the capital letters "RDP" appeared in the middle of `uid` values. If we'd returned all the `_path=rdp` ones as well it may have inspired them to, say, right-click in the app and pick "Filter = value" and end up with just the ones they originally had in mind.

**Comment by philrz** [comment]
Re-opening this one. When verifying the functionality I noticed that the implementation matches on whole field names but doesn't not on substrings (nor is it currently case-insensitive, which we're also going to be doing for "bare searches"). I spoke to @aswan about adjusting this to be in-line with our general approach of "return the most" on bare searches, and he's cool with making that change. Thanks @aswan!

**Comment by philrz** [comment]
Verified in `zq` commit `4895043`.

Revisiting the original example, now we match on the field name:

```
# echo '{"foo": "bar"}' | zq "foo" -
#0:record[foo:string]
0:[bar;]
```

The same is true if it's a substring of  the field name:

```
# echo '{"foo": "bar"}' | zq "fo" -
#0:record[foo:string]
0:[bar;]
```

And it's also case-insensitive:

```
# echo '{"foo": "bar"}' | zq "FO" -
#0:record[foo:string]
0:[bar;]
```

Thanks @aswan!
