### ISSUE TITLE
Deadlock in flowgraph with split/merge

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#515]
This hangs: ` zq "(count(); filter *) | head 1" conn.log `

**Comment by aswan** [comment]
The fix here took care of reducer and groupby, but there are still other procs that don't match calls to their Pull() methods with calls to their parent's Pull() method.  We could fix this by having procs implement a method called process() or something that always takes a zbuf.Batch and returns a zbuf.Batch, and moving Pull() into a shared place where individual procs don't override it.

Alternatively, @nwt proposed removing the time-ordering logic in merge.

To be discussed further...

**Comment by aswan** [comment]
The follow-up in #667 took care of this
