### ISSUE TITLE
add compression type code and framing support

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#521]
In bzng reader and writer, add support for in-line compressed data, by using a type code to indicate a compressed section:
`<comp-type-code><comp-kind><uvarint-len><len bytes of compressed zng data>`

**Comment by alfred-landrum** [comment]
I'm moving this under the boyer-moore epic https://github.com/brimsec/zq/issues/682 , as this should be implemented alongside that work.

**Comment by philrz** [comment]
Verified in `zq` commit `253c336`.

After this support was added, that newer `zq` was used to regenerate the ZNG [zq-sample-data](https://github.com/brimsec/zq-sample-data) in this new compressed format (https://github.com/brimsec/zq-sample-data/pull/13), with the prior uncompressed ZNG moved to a separate directory in the sample data repo. The byte counts showing the benefits of the compression:

```
~/work/zq-sample-data$ gzcat zng/* | wc -c
 74663004

~/work/zq-sample-data$ gzcat zng-uncompressed/* | wc -c
 175949386
```

So, for this particular data, that's 2.35x compression.

Also, the [`zq` performance numbers](https://github.com/brimsec/zq/blob/master/performance/README.md) were updated, showing that even with compression enabled, the read/write performance of ZNG is roughly the same as it was before (#1064).

Thanks @nwt!
