### ISSUE TITLE
Let groupby use arbitrary expressions

### ISSUE THREAD

**Issue by aswan** [brimsec/zq#535]
The `by ...` clause in a groupby proc is currently a list of field names.  We should generalize this to allow an arbitrary expression.  This would enable lots of things that can't be easily expressed right now, such as
```
count() by len(someset)
count() by String.tolower(something)
count() by 1000*Math.round(bytes/1000)
```

**Comment by henridf** [comment]
not arguing against the feature, but we can currently do these with `put`, correct?

`put s=String.tolower(something) count() by s`

**Comment by aswan** [comment]
Yes, that's a way to get the same effect, this would be streamlining this scenario a bit.

**Comment by aswan** [comment]
One little design question here is what to name the key fields in output records.  e.g., in the original examples, each output record would have a computer field named `count` but it also needs a field for the key and that field needs a name.  Its hard to formulate a general rule that produces something sensible, we could make it mandatory for the query author to specify a name using syntax such as
```
count() by setlen=len(someset)
count() by something=String.tolower(something)
count() by rounded_bytes=1000*Math.round(bytes/1000)
```

**Comment by henridf** [comment]
This syntax looks fine to me, although I'll note that adding assignment syntax to group by it brings us one step closer to the `put | reduce` pattern... e.g. 
`count() by something=String.tolower(something)`
vs
`put something=String.tolower(something) | count() by something`

I guess what I'm suggesting is that given the existing alternative with put, this feels almost like syntactic sugar that would be great to have at some point but doesn't seem like a near-term necessity...

**Comment by aswan** [comment]
> I guess what I'm suggesting is that given the existing alternative with put, this feels almost like syntactic sugar that would be great to have at some point but doesn't seem like a near-term necessity...

*shrug*, its in the backlog suggesting somebody thought it was important.

**Comment by philrz** [comment]
We learned that after #840 was merged, it broke some Brim app tests, so the changes were reverted in #859. Therefore I'm re-opening this one while that's being resolved.

**Comment by philrz** [comment]
Verified in `zq` commit `18b9719`.

Per the comment thread above, the final syntax includes a leading specification of what to name the newly-generated field in the output records. Revisiting examples similar to the ones that kicked off the issue:

```
$ zq -f table "count() by num_uids=len(uids)" dhcp.log 
NUM_UIDS COUNT
1        233
2        6912

$ zq -f table "count() by bigproto=String.toUpper(proto)" conn.log
BIGPROTO COUNT
TCP      176937
UDP      310643
ICMP     8172

$ zq -f table "count() by byte_bucket=1000*Math.round(orig_bytes/1000) | sort -r" conn.log 
BYTE_BUCKET COUNT
7272000     2
5322000     1
5086000     1
...
2000        18857
1000        26278
0           362214
-           71347
```

Thanks @henridf!
