### ISSUE TITLE
Fix pcap search endpoint not found

### ISSUE THREAD

**Issue by mattnibs** [brimsec/zq#550]
There's some buggy behavior around how zqd handles searches that do not produce any results:
- The 404 response that the handler tries to write is never received because a 200 response already has been sent
- It also attempts to write a string error message that doesn't match the pcap content-type header that has already been sent.
- The pcap SearchReader will write also stream back section headers for each pcap on searches that return zero packets.

We should reformat the pcap.SearchReader to peek through the pcap file being searched to check if there are any results to the search, before the content type headers are written and data is copied to the response writer.

**Comment by alfred-landrum** [comment]
I think the point about filtering out section headers deserves an issue on its own. I think @mccanne left a comment in the code saying that we should eventually filter those out, as may send them even when other sections have matching packets.

**Comment by mattnibs** [comment]
@alfred-landrum sure
