### ISSUE TITLE
Zeek reader trims whitespace too aggressively

### ISSUE THREAD

**Issue by aswan** [brimsec/zq#552]
The code here trims any trailing whitespace: https://github.com/brimsec/zq/blob/master/zio/zeekio/reader.go#L46

A log in which the last column is a string type and there's a value that just consists of whitespace is valid but we fail to read it.  @philrz came across an example in the wild that looks like this:
```
#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	unknown_mime_type_discovery
#open	2020-04-10-18-15-32
#fields	ts	fid	bof
#types	time	string	string
1425634708.454143	FTBt2P3wJBdHGKpZwc	 
```
Its not visible in the text display but after the uid on the last line is a tab character and space character.

**Comment by philrz** [comment]
Here's a log file as attachment that contains this, for ease of verification when we have a fix:

[unknown_mime_type_discovery.log](https://github.com/brimsec/zq/files/4465027/unknown_mime_type_discovery.log)

**Comment by philrz** [comment]
Verified in `zq` commit `4895043`.

Just to briefly revisit the symptom using the attached test data, this is how it looked as of `zq` commit `8ed4a03`:

```
# q -i zeek unknown_mime_type_discovery.log 
too few values
```

Now with `zq` commit `4895043`:

```
zq -i zeek unknown_mime_type_discovery.log 
#0:record[_path:string,ts:time,fid:bstring,bof:bstring]
0:[unknown_mime_type_discovery;1425634708.454143;FTBt2P3wJBdHGKpZwc; ;]
0:[unknown_mime_type_discovery;1425634709.279048;FkyH2ivxvSBAv1iV9;\x0d\x0a;]
```

Thanks @aswan!
