### ISSUE TITLE
Error make install zq.

### ISSUE THREAD

**Issue by suricatalfon** [brimsec/zq#581]
Hello,

echo $GOPATH 
/home/xxx/go

$ make install or sudo make install 

cmd/pcap/main.go:7:2: cannot find package "github.com/brimsec/zq/cmd/pcap/cut" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/pcap/cut (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/pcap/cut (from $GOPATH)
cmd/pcap/main.go:8:2: cannot find package "github.com/brimsec/zq/cmd/pcap/index" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/pcap/index (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/pcap/index (from $GOPATH)
cmd/pcap/main.go:9:2: cannot find package "github.com/brimsec/zq/cmd/pcap/root" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/pcap/root (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/pcap/root (from $GOPATH)
cmd/pcap/main.go:10:2: cannot find package "github.com/brimsec/zq/cmd/pcap/slice" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/pcap/slice (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/pcap/slice (from $GOPATH)
cmd/pcap/main.go:11:2: cannot find package "github.com/brimsec/zq/cmd/pcap/ts" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/pcap/ts (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/pcap/ts (from $GOPATH)
cmd/pcap/cut/command.go:14:2: cannot find package "github.com/brimsec/zq/pcap/pcapio" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/pcap/pcapio (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/pcap/pcapio (from $GOPATH)
cmd/pcap/cut/command.go:15:2: cannot find package "github.com/mccanne/charm" in any of:
	/usr/lib/go-1.10/src/github.com/mccanne/charm (from $GOROOT)
	/home/xxx/go/src/github.com/mccanne/charm (from $GOPATH)
cmd/pcap/index/command.go:12:2: cannot find package "github.com/brimsec/zq/pcap" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/pcap (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/pcap (from $GOPATH)
cmd/pcap/slice/command.go:15:2: cannot find package "github.com/brimsec/zq/pkg/nano" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/pkg/nano (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/pkg/nano (from $GOPATH)
cmd/zar/main.go:7:2: cannot find package "github.com/brimsec/zq/cmd/zar/chop" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/zar/chop (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/zar/chop (from $GOPATH)
cmd/zar/main.go:8:2: cannot find package "github.com/brimsec/zq/cmd/zar/find" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/zar/find (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/zar/find (from $GOPATH)
cmd/zar/main.go:9:2: cannot find package "github.com/brimsec/zq/cmd/zar/index" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/zar/index (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/zar/index (from $GOPATH)
cmd/zar/main.go:10:2: cannot find package "github.com/brimsec/zq/cmd/zar/root" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/zar/root (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/zar/root (from $GOPATH)
cmd/zar/chop/command.go:12:2: cannot find package "github.com/brimsec/zq/pkg/bufwriter" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/pkg/bufwriter (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/pkg/bufwriter (from $GOPATH)
cmd/zar/chop/command.go:14:2: cannot find package "github.com/brimsec/zq/zbuf" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/zbuf (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/zbuf (from $GOPATH)
cmd/zar/chop/command.go:15:2: cannot find package "github.com/brimsec/zq/zio" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/zio (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/zio (from $GOPATH)
cmd/zar/chop/command.go:16:2: cannot find package "github.com/brimsec/zq/zio/bzngio" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/zio/bzngio (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/zio/bzngio (from $GOPATH)
cmd/zar/chop/command.go:17:2: cannot find package "github.com/brimsec/zq/zng/resolver" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/zng/resolver (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/zng/resolver (from $GOPATH)
cmd/zar/find/command.go:9:2: cannot find package "github.com/brimsec/zq/archive" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/archive (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/archive (from $GOPATH)
cmd/zdx/main.go:9:2: cannot find package "github.com/brimsec/zq/cmd/zdx/create" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/zdx/create (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/zdx/create (from $GOPATH)
cmd/zdx/main.go:10:2: cannot find package "github.com/brimsec/zq/cmd/zdx/dump" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/zdx/dump (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/zdx/dump (from $GOPATH)
cmd/zdx/main.go:11:2: cannot find package "github.com/brimsec/zq/cmd/zdx/lookup" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/zdx/lookup (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/zdx/lookup (from $GOPATH)
cmd/zdx/main.go:12:2: cannot find package "github.com/brimsec/zq/cmd/zdx/merge" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/zdx/merge (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/zdx/merge (from $GOPATH)
cmd/zdx/main.go:13:2: cannot find package "github.com/brimsec/zq/cmd/zdx/root" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/zdx/root (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/zdx/root (from $GOPATH)
cmd/zdx/create/command.go:9:2: cannot find package "github.com/brimsec/zq/zdx" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/zdx (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/zdx (from $GOPATH)
cmd/zq/zq.go:14:2: cannot find package "github.com/brimsec/zq/ast" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/ast (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/ast (from $GOPATH)
cmd/zq/zq.go:15:2: cannot find package "github.com/brimsec/zq/driver" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/driver (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/driver (from $GOPATH)
cmd/zq/zq.go:16:2: cannot find package "github.com/brimsec/zq/emitter" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/emitter (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/emitter (from $GOPATH)
cmd/zq/zq.go:18:2: cannot find package "github.com/brimsec/zq/scanner" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/scanner (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/scanner (from $GOPATH)
cmd/zq/zq.go:21:2: cannot find package "github.com/brimsec/zq/zio/detector" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/zio/detector (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/zio/detector (from $GOPATH)
cmd/zq/zq.go:22:2: cannot find package "github.com/brimsec/zq/zio/ndjsonio" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/zio/ndjsonio (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/zio/ndjsonio (from $GOPATH)
cmd/zq/zq.go:24:2: cannot find package "github.com/brimsec/zq/zqd/ingest" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/zqd/ingest (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/zqd/ingest (from $GOPATH)
cmd/zq/zq.go:25:2: cannot find package "github.com/brimsec/zq/zql" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/zql (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/zql (from $GOPATH)
cmd/zq/zq.go:27:2: cannot find package "go.uber.org/zap" in any of:
	/usr/lib/go-1.10/src/go.uber.org/zap (from $GOROOT)
	/home/xxx/go/src/go.uber.org/zap (from $GOPATH)
cmd/zqd/main.go:7:2: cannot find package "github.com/brimsec/zq/cmd/zqd/listen" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/zqd/listen (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/zqd/listen (from $GOPATH)
cmd/zqd/main.go:8:2: cannot find package "github.com/brimsec/zq/cmd/zqd/root" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/zqd/root (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/zqd/root (from $GOPATH)
cmd/zqd/main.go:9:2: cannot find package "github.com/brimsec/zq/zqd" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/zqd (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/zqd (from $GOPATH)
cmd/zqd/listen/command.go:14:2: cannot find package "github.com/brimsec/zq/cmd/zqd/logger" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/cmd/zqd/logger (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/cmd/zqd/logger (from $GOPATH)
cmd/zqd/listen/command.go:16:2: cannot find package "github.com/brimsec/zq/pkg/httpd" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/pkg/httpd (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/pkg/httpd (from $GOPATH)
cmd/zqd/listen/command.go:18:2: cannot find package "github.com/brimsec/zq/zqd/zeek" in any of:
	/usr/lib/go-1.10/src/github.com/brimsec/zq/zqd/zeek (from $GOROOT)
	/home/xxx/go/src/github.com/brimsec/zq/zqd/zeek (from $GOPATH)
cmd/zqd/listen/command.go:21:2: cannot find package "gopkg.in/yaml.v3" in any of:
	/usr/lib/go-1.10/src/gopkg.in/yaml.v3 (from $GOROOT)
	/home/xxx/go/src/gopkg.in/yaml.v3 (from $GOPATH)
cmd/zqd/logger/waterfall.go:4:2: cannot find package "go.uber.org/multierr" in any of:
	/usr/lib/go-1.10/src/go.uber.org/multierr (from $GOROOT)
	/home/xxx/go/src/go.uber.org/multierr (from $GOPATH)
cmd/zqd/logger/file.go:9:2: cannot find package "go.uber.org/zap/zapcore" in any of:
	/usr/lib/go-1.10/src/go.uber.org/zap/zapcore (from $GOROOT)
	/home/xxx/go/src/go.uber.org/zap/zapcore (from $GOPATH)
cmd/zqd/logger/file.go:10:2: cannot find package "gopkg.in/natefinch/lumberjack.v2" in any of:
	/usr/lib/go-1.10/src/gopkg.in/natefinch/lumberjack.v2 (from $GOROOT)
	/home/xxx/go/src/gopkg.in/natefinch/lumberjack.v2 (from $GOPATH)
make: *** [install] Error 1

Best Regard,

**Comment by aswan** [comment]
Hi, thanks for taking time to report your build errors.  From the output above, it looks like you're using go version 1.10, you need at least 1.13 to build zq.  Please try updating your go installation and re-building.

**Comment by suricatalfon** [comment]
Hello,  aswan
zq -version
Version: v0.10.0-8-g4895043

Tanks,

**Comment by aswan** [comment]
@suricatalfon I'm not sure I understand your comment, that's a very recent revision of zq, are you reporting that you were able to build successfully with a recent version of go?
