### ISSUE TITLE
json reader: Support multiple typed arrays

### ISSUE THREAD

**Issue by mattnibs** [brimsec/zq#64]
The json parser returns an error when parsing a json array with multiple types, e.g.:
```json
{ "arr1": [1, "mystring", { "string1": "value1"} ] } 
```

It would be great if this would work- either through some kind of type coercion rules, or maybe the a type `vector[any]`.

**Comment by aswan** [comment]
> It would be great if this would work- either through some kind of type coercion rules, or maybe the a type vector[any].

Not sure I understand, `any` isn't a thing in the zson/zeek type sysytem, are you proposing that it be added?

**Comment by mattnibs** [comment]
Yes. `zeek` has a type `any` for "bypassing strong typing": https://docs.zeek.org/en/stable/script-reference/types.html#type-any

**Comment by aswan** [comment]
I wasn't clear, by the zson/zeek type system I mean zq/pkg/zeeek and the zql runtime.  Is the proposal in this issue to add an `any` type to that system?

**Comment by mattnibs** [comment]
The issue is more about determining a long term solution for handling JSON arrays w/ multiple types as an input. We currently just throw an error if this happens. In my comment I was enumerating a couple of solutions that made sense to me. The idea of supporting `vector[any]` (and therefore we would have to support type `any`) made sense to me-but w/out thinking through how this would effect the entire system. For instance I'm not sure how `vector[any]` would be represented in zson output (or if that would even make sense). Zeek for instance supports `any` in its runtime but this value cannot be exported through its logging framework.

**Comment by alfred-landrum** [comment]
Closing, as multiply typed arrays are now implemented via the union type.
