### ISSUE TITLE
replace zdx.MemTable usage with key sorter than can spill to disk

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#646]
`zdx.MemTable` is used to build the sorted list of keys that are the bulk of the zdx bundle. It keeps all keys in memory (as the name implies). We should replace it with some alternative structure or method that can spill & sort to disk. A good solution would likely utilize re-use the work to make `sort` spill to disk in https://github.com/brimsec/zq/pull/527 .

**Comment by henridf** [comment]
I started looking into and the direct route via reusing `sort` seems straightforward, but it given index builder is basically building a big group-by table, it would be even better if we could just use that instead, given that we've talked about making group-by capable of spilling to disk too. 

Of course that's more work so if the feature itself is time-sensitive, then we should go ahead with the approach described here using sort.

**Comment by mccanne** [comment]
I think we should approach this one more holistically.  If you look through the zar README, the key steps are here:
```
zar zq -o keys.zng "_path=conn | sum(resp_bytes) as resp_bytes by id.resp_h,id.orig_h | sort id.resp_h,id.orig_h" _
zar zdx -o custom2 -k id.resp_h,id.orig_h keys.zng
```
It would be nice to just re-use this zql machinery in the zar index path and get rid of zdx.MemTable completely.  If the zql group-by could spill, then we don't need to re-create zdx.Memtable spillling.  The "zar zdx" pass could take input from a scanner/combiner on the spilled files.

**Comment by henridf** [comment]
I created a separate issue for the "re-use zql machinery" work that @mccanne describes in the comment above. That leaves the work of converting groupby to be spill-able - @alfred-landrum we can repurpose this issue for that, or close it and open a new one.

**Comment by alfred-landrum** [comment]
Let's close this one and have a new issue just for the spillable groupby,
and make brimsec/zq#798 depend on the new issue.

**Comment by henridf** [comment]
Ok. (But #798 doesn't need to depend on the new issue.)

**Comment by henridf** [comment]
Superseded by #800 and #798
