### ISSUE TITLE
Don't allow duplicate field names in reducer/groupby

### ISSUE THREAD

**Issue by aswan** [brimsec/zq#652]
This simple query produces invalid output (two identically named columns)
```
(~/src/zq)$ go run ./cmd/zq 'count(uid), count(id.orig_h)' conn.log 
#0:record[count:uint64,count:uint64]
0:[92;92;]
```

A similar issue was fixed for cut in #165, but the logic there is inside ColumnBuilder which isn't used for reducer.  groupby uses ColumnBuilder but only to build the keys portion of output records.  We should fix this for the reducer and groupby procs...

**Comment by philrz** [comment]
Verified in `zq` commit `269101b`. Now the original repro step gives an error message.

```
# zq -t 'count(uid), count(id.orig_h)' conn.log
duplicate field count
```
