### ISSUE TITLE
support field rename with cut proc

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#665]
Add support to the cut proc to rename the fields it allows. So an expression like:
` ... | cut x=a, b ` would have columns x & b.

**Comment by alfred-landrum** [comment]
@aswan : I think we should just overwrite, without a warning.

**Comment by philrz** [comment]
FWIW, I'm acting as a `zq` user today and found myself wanting this functionality. :)

**Comment by henridf** [comment]
@philrz how about `cut a, b | rename a=x` ? :) 

(My hidden public agenda is to promote a standalone rename proc as a first step :) )

**Comment by philrz** [comment]
@henridf: Yes, an explicit `rename` processor seems justified, even if just because it will stand out to a user browsing the docs with the goal of renaming fields.

**Comment by philrz** [comment]
Verified in `zq` commit `6f1fa7d`.

Similar to the example that was added in the docs, here's a `cut` of the `ts` field while renaming the field to `time`:

```
$ zq -f table 'cut time=ts' conn.log.gz
TIME
1521911721.255387
1521911721.411148
1521911721.926018
...
```

Also, per the comments above, if the rename is to a named field that already exists, we overwrite the original field without warning. While it's unlikely a user would want to do this, if you wanted to see just the contents of the `history` field but call it `uid`:

```
$ zq -f table 'cut uid=history' conn.log.gz | head
UID
ShADTdtr
Sr
Sr
...
```

Thanks @henridf!
