### ISSUE TITLE
support multiple assignments in put

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#666]
Add support for multiple assignment expressions in put. For example,
" ... | put a=1, b=1+2 " would include a=1,b=3 in all resulting records.

**Comment by philrz** [comment]
Verified in `zq` commit `a1d0967`. Using the original proposed example:

```
$ echo '{"foo": "bar"}' | zq -t "put a=1,b=1+2" -
#0:record[foo:string,a:int64,b:int64]
0:[bar;1;3;]
```

Thanks @aswan!
