### ISSUE TITLE
boyer-moore string search

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#682]
We should be able to implement boyer moore string searching, optimized to run against the raw zbytes of a zng stream, so that we minimize the amount of record parsing and and io buffer allocation. There's a connection with implementing zng compression support, as a compressed batch of records gives an easy way to identify record boundaries.

**Comment by philrz** [comment]
Note to self: When this Epic is closed, it's probably worth cutting another set of the zq "perf" numbers so we can quantify the observable benefits from this.
