### ISSUE TITLE
support s3 data locations in zq

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#704]
zq should support reading from and writing to locations in S3 object stores, including AWS S3 & minio. s3 locations should be recognized via `s3://<bucket>/...` style urls. zq should honor any relevant config a user may have set via `aws configure`, like access keys.

We'll want to have tests that verify the s3 operations; one option is to use minio, using a pattern suggested here: https://github.com/minio/minio/issues/5146#issuecomment-342271686 , but there may be better options.

**Comment by aswan** [comment]
I haven't delved deeply into this but given that the motivation here is to build something that works in conjunction with parquet (#703), note that the parquet-go library has a companion library that handles reading from (among other places) s3: https://github.com/xitongsys/parquet-go-source
Ideally we could handle s3 and parquet independently and everything would just work and come together nicely, but maybe there's a more expedient solution for the particular case of parquet-on-s3 here.

**Comment by alfred-landrum** [comment]
I'd noticed parquet-go-source since it's a dep of parquet-go and I agree, it could be a backup plan for parquet-on-s3 support. As you say though, they should be independent, and we'll want to support all our formats in S3.

**Comment by henridf** [comment]
> and we'll want to support all our formats in S3.

And conversely, we'll want to be able to read parquet from local files, which further argues for independence between format and storage access.

**Comment by henridf** [comment]
It looks like the two primary candidate client libraries are the [minio](https://docs.min.io/docs/golang-client-api-reference) one and the [aws](https://godoc.org/github.com/aws/aws-sdk-go/service/s3) one. I will take a look to see how they compare.

**Comment by henridf** [comment]
Ok for the record, here's the current/tentative plan after discussion with @aswan and @alfred-landrum: For s3 inputs, zio/detector can use [parquet-go-source](https://github.com/xitongsys/parquet-go-source) to build a s3 ParquetFile (https://github.com/xitongsys/parquet-go/blob/master/source/source.go#L9) and pass it to all readers, since the ParquetFile interface includes io.Reader. 
The s3 ParquetFile implementation is a wrapper around the aws s3 client, the main addition on the read path is the implementation of io.Seeker.

Possibly we'll later need to implement our own wrapper around an s3 client, but this is a good way to get going.

**Comment by philrz** [comment]
Verified in `zq` commit `64d5e4a`.

I'd created an S3 bucket, populated it with some ZNG files, and done the standard `aws configure` on my Mac. Initially I had some struggles with the Region config:

```
$ zq -t "count() by _path" s3://wheel-demo/conn.zng.gz s3://wheel-demo/dns.zng.gz s3://wheel-demo/http.zng.gz
s3://wheel-demo/conn.zng.gz: format detection error
	tzng: line 1: MissingRegion: could not find region configuration
	zeek: line 1: MissingRegion: could not find region configuration
	ndjson: MissingRegion: could not find region configuration
	zjson: line 1: MissingRegion: could not find region configuration
	zng: MissingRegion: could not find region configuration
```

However, doing a web search on the error message I found my way to https://docs.aws.amazon.com/ja_jp/sdk-for-go/v1/developer-guide/configuring-sdk.html which seems to show that the Go library will find the credentials in `~/.aws/credentials` automatically but won't do the same with the region info in `~/.aws/config` unless I set the environment variable `AWS_SDK_LOAD_CONFIG=true`. Sure enough, that does the trick.

```
$ export AWS_SDK_LOAD_CONFIG=true
$ zq -t "count() by _path" s3://wheel-demo/conn.zng.gz s3://wheel-demo/dns.zng.gz s3://wheel-demo/http.zng.gz
#0:record[_path:string,count:uint64]
0:[dns;53615;]
0:[conn;1021952;]
0:[http;144034;]
```

@henridf also set my expectations that reading of Parquet format is not there yet with S3, but he'll be working on it soon.

Thanks @henridf!
