### ISSUE TITLE
Cleaner `zar zq` output on stdout with text formats

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#759]
The zar README brings the reader to this `zar zq` query:

```sh
$ zar zq "count()" _ | zq -f table -
COUNT
222617
223815
218575
...
```

at which point, one might recall that zar zq supportsd different output formats, and directly try:

```sh
$ zar zq -f table "count()" _ 
COUNT
222617
COUNT
223815
COUNT
218575
...
```

which gives correct results, but with extra headers that are a little surprising. This is not a bug, but would likely be unexpected to someone without deep familiarity with the inner workings of zq and zar (as a README reader might be).

This can be addressed as suggested by @mccanne:

> A fix could be for stdout to merge the zng sub-streams that are created during the walk into one type context  and have a single writer instance for stdout.

**Comment by philrz** [comment]
Verified in `zq` commit `97f6edf`.

Per linked PR #818, the originally cited issue has been addressed by removing the `-f` option such that the user would need to use a post-pipe `zq` to perform alternate formatting.
