### ISSUE TITLE
improve reported ingest errors for invalid zeekrunner

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#767]
@jameskerr provided some screenshots of the errors that would be displayed if a user specifies a missing or invalid zeekrunner:
https://github.com/brimsec/brim/pull/771#discussion_r424093848

For these cases, we should improve those errors so that they are more helpful.

**Comment by philrz** [comment]
Verified in Brim commit `22604c1`.

I've reproduced the same kinds of errors as shown in the linked PR. The first was by pointing to a valid `zeekrunner` location, but then deleting it before trying to process a pcap.

![image](https://user-images.githubusercontent.com/5934157/82345224-e04eba00-99a9-11ea-99a8-32b72330a457.png)

In the second I had the `zeekrunner` in place, but did a `chmod gou-x` so it would not be executable.

![image](https://user-images.githubusercontent.com/5934157/82345327-feb4b580-99a9-11ea-88cb-ac78a38f8fc9.png)

Thanks @alfred-landrum!
