### ISSUE TITLE
Mention Parquet among supported input formats

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#769]
`zq` as of commit `64d5e4a` includes support for reading input files of Parquet format, but it's not yet mentioned in the supported list of formats in `zq help`.

```
$ zq help 2>&1 | grep "input data"
    -i format of input data [auto,zng,ndjson,zeek,zjson,tzng] (default "auto")
```

I checked with @aswan and he confirmed this was an oversight, so opening this as a reminder to circle back and add it.

**Comment by philrz** [comment]
Verified in `zq` commit `a1d0967`. Much like [Prego spaghetti sauce in the 80's](https://www.youtube.com/watch?v=2J87QekxQVI), it's in there.

```
$ zq help 2>&1 | grep "input data"
    -i format of input data [auto,zng,ndjson,zeek,zjson,tzng,parquet] (default "auto")
```

**Comment by henridf** [comment]
and in there!

```sh
$ zq -t  zio/detector/testdata/dns.parquet 
zio/detector/testdata/dns.parquet: format detection error
	tzng: line 1: bad format
	zeek: line 1: bad types/fields definition in zeek header
	ndjson: line 1: Unknown value type
	zjson: line 1: invalid character 'P' looking for beginning of value
	zng: zng descriptor out of range
	parquet: auto-detection not supported
```

**Comment by aswan** [comment]
If we're referencing 80's food commercials, we can't leave out https://www.youtube.com/watch?v=leQsRqMN230

**Comment by philrz** [comment]
Parkay truly shines when it speaks: https://www.youtube.com/watch?v=s0PnxGqFNz8
