### ISSUE TITLE
Enforce unique constraints on space names

### ISSUE THREAD

**Issue by mattnibs** [brimsec/zq#791]
Currently we allow spaces to:
1. Have duplicate names (all spaces have unique ids)
2. Contain any unicode character

In light of the `zapi` cli we have seen that it useful to have a human readable, unique handle for spaceIDs. As such change space name so that:
1. They are unique among all spaces in a zqd instances
2. Containing only characters `a-zA-Z0-9_`

This will also have to include some undocumented endpoint for migrating old space name/ids to this new format (i.e. old brim spaces).

**Comment by alfred-landrum** [comment]
Reopening this as there's a need to discuss the name character restriction impact on the Brim UI.

**Comment by philrz** [comment]
Verified in Brim commit `cd25120` talking to `zqd` commit `ac2ea5e`. See https://github.com/brimsec/zq/issues/937#issuecomment-650311707.

Thanks @mattnibs and @alfred-landrum!
