### ISSUE TITLE
zar custom indexes accept mixed types (but shouldn't)

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#815]
`zar index <field>` checks that the type of `<field>` is the same in all records, and produces an error if not. The same is not true when building a custom index. We should check for and error on type changes when building a custom index. Or alternatively, rework things more broadly so that same-field-different-types can be handled.

This is the error with `zar index` (5629faf320c1b24b6867b2cf839ae2ccd0ff0a9f).
```sh
$ cat ../multitype.tzng 
#0:record[_path:string,ts:time,orig_h:ip]
0:[smb_cmd;1258594907.85978;192.168.2.1;]
#1:record[_path:string,ts:time,orig_h:string]
1:[smb_cmd;1258594908.85978;"hello";]
09:27 ~/tmp/logs
$ zar import !$
zar import ../multitype.tzng
09:27 ~/tmp/logs
$ zar index orig_h
/Users/henridf/tmp/logs/20091119/1258594908.85978.zng: creating index /Users/henridf/tmp/logs/20091119/1258594908.85978.zng.zar/zdx:field:orig_h
/Users/henridf/tmp/logs/20091119/1258594908.85978.zng.zar: type of key field changed from string to ip
```

With a custom index, there is no error and the index ends up containing multiple types, contradicting what the header announces:

```
$ zar zq -o keys.zng "cut orig_h | sort" _
09:28 ~/tmp/logs
09:28 ~/tmp/logs
$ zar zdx -o custom -k orig_h keys.zng
09:28 ~/tmp/logs
$ zq -t 20091119/1258594908.85978.zng.zar/custom.zng
#0:record[magic:string,version:string,child_field:string,keys:record[orig_h:ip]]
0:[zdx;0.2;_btree_child;-;]
#1:record[orig_h:ip]
1:[192.168.2.1;]
#2:record[orig_h:string]
2:["hello";]
```

**Comment by henridf** [comment]
Note that this issue remains with #816 (even though the CLI commands to create a custom index are different)

**Comment by philrz** [comment]
Perhaps this justifies a separate issue, but while trying to understand what's described here, I observed that even the `zar index` example does not leave things in a usable state, as an empty microindex ZNG file is left behind. As of `zq` commit `3d49cfb`:

```
$ zar import multitype.tzng 

$ zar index orig_h
/Users/phil/logs/20091119/1258594908.85978.zng: creating index /Users/phil/logs/20091119/1258594908.85978.zng.zar/zdx-field-orig_h
type of orig_h field changed from string to ip

$ tree -s $ZAR_ROOT
/Users/phil/logs
├── [        128]  20091119
│   ├── [         93]  1258594908.85978.zng
│   └── [         96]  1258594908.85978.zng.zar
│       └── [          0]  zdx-field-orig_h.zng
└── [        197]  zar.json

2 directories, 3 files

$ zar find orig_h=192.168.2.1
/Users/phil/logs/20091119/1258594908.85978.zng.zar/zdx-field-orig_h: /Users/phil/logs/20091119/1258594908.85978.zng.zar/zdx-field-orig_h: cannnot read zdx header
```

**Comment by henridf** [comment]
> Note that this issue remains with #816 (even though the CLI commands to create a custom index are different)

The CLI command post-#816 is: `zar index -q -o custom -k orig_h -z "cut orig_h | sort" _`

**Comment by henridf** [comment]
@philrz re https://github.com/brimsec/zq/issues/815#issuecomment-651423326 I noticed it too and filed as standalone bug https://github.com/brimsec/zq/issues/987.

**Comment by philrz** [comment]
Verified in `zq` commit `26d4b66`. Now in addition to the error message, I see the entry in the index is no longer being creating for the `string` value. I also added another `ip` value to the input data to convince myself that the indexing proceeded to add values of the proper type even after the error is floated.

```
$ cat multitype.tzng 
#0:record[_path:string,ts:time,orig_h:ip]
0:[smb_cmd;1258594907.85978;192.168.2.1;]
#1:record[_path:string,ts:time,orig_h:string]
1:[smb_cmd;1258594908.85978;"hello";]
0:[smb_cmd;1258594909.85978;192.168.2.2;]

$ zar import multitype.tzng 

$ zar index -q -o custom -k orig_h -z "cut orig_h | sort" _
key type changed from record[orig_h:ip] to record[orig_h:string]

$ zq -t $ZAR_ROOT/20091119/1258594909.85978.zng.zar/custom.zng 
#0:record[magic:string,version:string,child_field:string,keys:record[orig_h:ip]]
0:[zdx;0.2;_btree_child;-;]
#1:record[orig_h:ip]
1:[192.168.2.1;]
1:[192.168.2.2;]
```

Thanks @henridf!
