### ISSUE TITLE
Add syntax for keys-only/reducer-less groupby to ZQL

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#821]
There should be a way to express a "reducer-less" groupby in ZQL, that would compute a group-by table of all the unique values for its keys, without any reducer. (With identical results to `count() by <keys> | cut <keys>`).

Proposed syntax:

`... | group by <keys> | * `

Note that this is a grammar-only change; the runtime already supports this, and can already handle a reducer-less groupby AST (as used in #816) :

```
			&ast.GroupByProc{
				Keys: []string{keyName},
			},
```

**Comment by henridf** [comment]
Offline decision: the syntax will be `.. | by keys | ..`

**Comment by henridf** [comment]
> Offline decision: the syntax will be .. | by keys | ..

The time-binned variant will read a little odd `... | every 1h by keys | ...` but maybe that's ok.

**Comment by mccanne** [comment]
I put this in backlog as I've wanted to use it and it should be super easy (famous last words)

**Comment by philrz** [comment]
This functionality is verified via the user-facing ZQL docs being tracked in #1623.
