### ISSUE TITLE
groupby: remove special-cased time bin handling

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#828]
Once #535 is complete, we can get rid of the special-case time bin handling in the groupby proc by adding zql sugar that turns `-every X` into a groupby key `ts=Time.trunc(ts, X)`. 

This includes generalizing the "early timebin output" feature that is present in every-groupby, which outputs time-bins as soon as input record time has advanced past a bin. This early-emit will be controlled by a new `-sorted` flag that will tell groupby that the input is sorted on the primary groupby key, and that it is therefore safe to do early-emit.

**Comment by philrz** [comment]
@henridf: Hmm. As long as we're sugaring, would an additional option be appropriate to specify a field name other than `ts` to be used in that `-every` context? We know `ts` is the common name in Zeek land, but thinking of a life beyond Zeek.

**Comment by henridf** [comment]
Note that  for this use case you can always use the long form:

`count() by time.Trunc(myTs, 3600)`

which would be doing every 1h using the timestamp stored in myTs.

That said, if you can get consensus for adding some option syntax to specify a different time field along with `every` I will happily implement 🙂
