### ISSUE TITLE
"rename" processor

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#856]
https://github.com/brimsec/zq/issues/665 first proposed the idea of renaming fields as a side-effect of using the `cut` processor. In a [comment](https://github.com/brimsec/zq/issues/665#issuecomment-637668926), @henridf made the valid point that as a first step we should have an explicit `rename` processor, then after that exists we could start to offer renaming as a side-effect in other processors. In a group discussion, we agreed that this makes sense. Among other things, a user seeking to rename fields might look at the [ZQL processors doc](https://github.com/brimsec/zq/blob/master/zql/docs/processors/README.md) and see the word "rename" prominently in the table of contents and be off to the races.

The proposed syntax is a simple `... | rename source_ip=id.orig_h,dest_ip=id.resp_h` that would take a list of several `to=from` pairings. Data types (including aliases) would be preserved. We also agreed that this processor would be kept super simple with no expressions permitted, e.g. `rename bar=String.toLower(foo)` would _not_ be available. That's what `put` is for. When we're updating the docs, we should mention this so that way if users were expecting to do more than simple renaming, they know where to go.

**Comment by henridf** [comment]
An open question here is what do we do with nested records? 

For example, given an input record with type `record[id:record[orig_h:ip,resp_h:ip]]`, what should be the output for the flowgraph `rename dst=id.resp_h`?

It seems like the result should be:

`record[id:record[orig_h:ip],dst:ip]`

but i find it slightly odd to be able to "rename" an inner field into a different record. Maybe this is the right behavior but the proc should be instead called `mv` or `move` ?




result in a new record with a top-level `dst`

**Comment by henridf** [comment]
I've moved this back to the backlog and answering the above question is less pressing now that #665 (cut-with-rename) is under review.

**Comment by henridf** [comment]
Note for whenever I or anyone else comes back to this:  `rename x=arr[0]` should be an error.

**Comment by philrz** [comment]
Verified in `zq` commit `9528007`. Per the [example from the docs](https://github.com/brimsec/zq/tree/master/zql/docs/processors#rename):

```
$ zq -f table 'rename time=ts, id.src=id.orig_h, conntuple=id' conn.log.gz
_PATH TIME              UID                CONNTUPLE.SRC  CONNTUPLE.ORIG_P CONNTUPLE.RESP_H CONNTUPLE.RESP_P PROTO SERVICE  DURATION ORIG_BYTES RESP_BYTES CONN_STATE LOCAL_ORIG LOCAL_RESP MISSED_BYTES HISTORY     ORIG_PKTS ORIG_IP_BYTES RESP_PKTS RESP_IP_BYTES TUNNEL_PARENTS
conn  1521911721.255387 C8Tful1TvM3Zf5x8fl 10.164.94.120  39681            10.47.3.155      3389             tcp   -        0.004266 97         19         RSTR       -          -          0            ShADTdtr    10        730           6         342           -
conn  1521911721.411148 CXWfTK3LRdiuQxBbM6 10.47.25.80    50817            10.128.0.218     23189            tcp   -        0.000486 0          0          REJ        -          -          0            Sr          2         104           2         80            -
conn  1521911721.926018 CM59GGQhNEoKONb5i  10.47.25.80    50817            10.128.0.218     23189            tcp   -        0.000538 0          0          REJ        -          -          0            Sr          2         104           2         80            -
conn  1521911722.690601 CuKFds250kxFgkhh8f 10.47.25.80    50813            10.128.0.218     27765            tcp   -        0.000546 0          0          REJ        -          -          0            Sr          2         104           2         80            -
...
```

I've also verified this new ZQL is working in Brim commit `5935d3b` talking to `zqd` commit `9528007`.

![image](https://user-images.githubusercontent.com/5934157/87976000-3a8afa80-ca81-11ea-8e5e-a22d43ed2863.png)

Thanks @henridf!
