### ISSUE TITLE
Remove arbitrary sort order from groupby

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#871]
Groupby currently emits records in "deterministic but undefined" order. (This order is achieved by running `sort.Strings()` on the keys, which may or may not be a recognizable order depending on the key type.)

In an offline discussion, there was agreement to remove this and let groupby emit records in non-deterministic order (coming from Go's non-deterministic map iteration order). This issue consists of doing that.

Note that with the `-sorted` flag, groupby emits records in their incoming sorted order; this behavior will remain with the above change.

**Comment by philrz** [comment]
Verified in `zq` commit `821ae98`.

Going back to `zq` commit `8dab96b` that came right before the commit for the changes in #914, we can see in repeated runs of a `count()` aggregation how its output was previously "deterministic but undefined".

```
$ zq -t 'count() by _path' s*.log.gz
#0:record[_path:string,count:uint64]
0:[ssh;22;]
0:[ssl;35493;]
0:[smtp;1188;]
0:[snmp;65;]
0:[stats;5;]
0:[syslog;2378;]
0:[smb_files;12;]
0:[smb_mapping;393;]

$ zq -t 'count() by _path' s*.log.gz
#0:record[_path:string,count:uint64]
0:[ssh;22;]
0:[ssl;35493;]
0:[smtp;1188;]
0:[snmp;65;]
0:[stats;5;]
0:[syslog;2378;]
0:[smb_files;12;]
0:[smb_mapping;393;]

$ zq -t 'count() by _path' s*.log.gz
#0:record[_path:string,count:uint64]
0:[ssh;22;]
0:[ssl;35493;]
0:[smtp;1188;]
0:[snmp;65;]
0:[stats;5;]
0:[syslog;2378;]
0:[smb_files;12;]
0:[smb_mapping;393;]
```

Doing the same with `zq` commit `821ae98`, we see that the order now can change between the repeated runs.

```
$ zq -t 'count() by _path' s*.log.gz
#0:record[_path:string,count:uint64]
0:[snmp;65;]
0:[syslog;2378;]
0:[smb_files;12;]
0:[ssh;22;]
0:[stats;5;]
0:[ssl;35493;]
0:[smb_mapping;393;]
0:[smtp;1188;]

$ zq -t 'count() by _path' s*.log.gz
#0:record[_path:string,count:uint64]
0:[stats;5;]
0:[ssl;35493;]
0:[smb_mapping;393;]
0:[smtp;1188;]
0:[snmp;65;]
0:[syslog;2378;]
0:[smb_files;12;]
0:[ssh;22;]

$ zq -t 'count() by _path' s*.log.gz
#0:record[_path:string,count:uint64]
0:[ssh;22;]
0:[stats;5;]
0:[ssl;35493;]
0:[smb_mapping;393;]
0:[smtp;1188;]
0:[snmp;65;]
0:[syslog;2378;]
0:[smb_files;12;]
```

Beyond the fact that the deterministic-but-unsorted order wasn't providing any known benefits, the new approach does save some performance, particularly when there's lots of rows in the table that were previously being sorted.

```
$ zq -version
Version: v0.15.0-8-g8dab96b

$ time (zq 'count() by uid -limit 100000000' *.log.gz > /dev/null)
real	0m10.168s
user	0m23.419s
sys	0m0.624s

$ zq -version
Version: v0.15.0-10-g821ae98

$ time (zq 'count() by uid -limit 100000000' *.log.gz > /dev/null)
real	0m9.377s
user	0m23.194s
sys	0m0.630s
```

Thanks @henridf!
