### ISSUE TITLE
Failed attempt to write to S3 bucket looks like success

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#900]
Found while verifying https://github.com/brimsec/zq/issues/771. With `zq` commit `4e6680f`, if I attempt to send the output to an S3 bucket that doesn't exist, `zq` behaves as if it worked.

```
$ echo '{"foo": "bar"}' | zq -t -
#0:record[foo:string]
0:[bar;]

$ echo '{"foo": "bar"}' | zq -t -o s3://this-bucket-does-not-exist/foo.zng -
$ echo $?
0
```

**Comment by mattnibs** [comment]
Thanks @philrz on it

**Comment by philrz** [comment]
Verified in `zq` commit `10de8f6`. Now we get a proper error message and a non-zero return code.

```
$ echo '{"foo": "bar"}' | zq -t -o s3://this-bucket-does-not-exist/foo.zng -
open s3://this-bucket-does-not-exist/foo.zng: no such file or directory

$ echo $?
1
```

Thanks @mattnibs!
