### ISSUE TITLE
Existence of local directory prevents output to S3 directory

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#915]
I stumbled onto this one by accident while trying to verify https://github.com/brimsec/zq/issues/771. Repro is with `zq` commit `821ae98`.

If I have a local directory named `foo`, it seems `zq` won't let me write to a directory in an S3 bucket of the same name. Once I remove the local directory, it works fine.

```
$ ls -l foo
ls: foo: No such file or directory

$ aws s3 ls s3://zq-771/foo/
[no output... remote directory doesn't exist yet]

$ zq -t -d foo 'uid=Ckwqsn2ZSiVGtyiFO5' *
$ ls -l foo
total 24
-rw-r--r--  1 phil  staff  541 Jun 16 15:02 conn.tzng
-rw-r--r--  1 phil  staff  747 Jun 16 15:02 notice.tzng
-rw-r--r--  1 phil  staff  727 Jun 16 15:02 ssl.tzng

$ zq -t -d s3://zq-771/foo 'uid=Ckwqsn2ZSiVGtyiFO5' *
foo: is a directory

$ rm -rf foo

$ zq -t -d s3://zq-771/foo 'uid=Ckwqsn2ZSiVGtyiFO5' *
[no output... it succeeded this time!]

$ aws s3 ls s3://zq-771/foo/
2020-06-16 15:03:30        541 conn.tzng
2020-06-16 15:03:30        747 notice.tzng
2020-06-16 15:03:30        727 ssl.tzng
```

**Comment by mattnibs** [comment]
weird :trollface:

**Comment by mattnibs** [comment]
@philrz I believe I know what is going on here. This doesn't have to do with exporting to s3. Rather when you use zq * and your cwd has a directory zq fails because it cannot open the directory. Once you delete the directory, zq succeeds. Does this seem right? Move to close.

**Comment by philrz** [comment]
Right you are @mattnibs. Thanks for helping me see what I was not understanding before. I suspect there's still a usability enhancement that could come out of this, but I'll spin up a separate discussion about that. You seem quite correct that this is not S3-specific, so, closing as a "wontfix".

**Comment by philrz** [comment]
One more comment. I'd forgotten about the availability of this `zq` option:

```
    -e stop upon input errors (default "true")
```

If I'd realized that's what was going on during my original repro steps, I could have used this option to force it to work despite the existence of the `foo` directory.

```
$ zq -e=false -t -d s3://zq-771/foo 'uid=Ckwqsn2ZSiVGtyiFO5' *
foo: is a directory
[pause of several seconds... it's populating the S3 bucket despite the warning...]

$ aws s3 ls s3://zq-771/foo/
2020-07-01 16:35:59        541 conn.tzng
2020-07-01 16:35:59        747 notice.tzng
2020-07-01 16:35:59        727 ssl.tzng
```

Maybe there's a discussion to be had about flipping the default behavior of the `-e` flag, or having persistent user preferences for `zq` so a user could have it set the opposite of the default all the time. But I know that's beyond the scope of this original issue.
