### ISSUE TITLE
change space name character constraint

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#937]
We discussed the constraints we want to enforce on space names, and said that for the moment, we wanted to:
- disallow the `/` (forward slash) character, as we may eventually want to encode hierarchy in space/subspace names
- allow most other Unicode characters that aren't control chars.

Specifically, I think we should construct & use a regex that checks: `r != '/' && unicode.IsPrint(r)` for every rune r in the proposed space name.

**Comment by philrz** [comment]
Verified in Brim commit `cd25120` talking to `zqd` commit `ac2ea5e`.

The verification of the error message on the disallowed `/` is captured in a [verification comment](https://github.com/brimsec/brim/issues/900#issuecomment-650310623) in https://github.com/brimsec/brim/issues/900.

Also, I've verified that I can rename to include printable characters that were not possible before.

![image](https://user-images.githubusercontent.com/5934157/85886128-50671180-b79a-11ea-9122-c4dee9fae195.png)

Thanks @alfred-landrum!
