### ISSUE TITLE
types.json can turn ISO8601 into "time" type, but casting can't

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#962]
Repro is with `zq` commit `8cdcf4b` and the [streaming JSON zq-sample-data](https://github.com/brimsec/zq-sample-data/tree/master/zeek-ndjson).

If I use the `types.json` config, a field that started life as a JSON string that happens to hold an ISO8601 timestamp can be turned into a ZNG `time` type.

```
$ zq -j ~/work/zq/zeek/types.json -t 'cut _write_ts | put foo=_write_ts | head 1' weird.ndjson.gz 
#0:record[_write_ts:time,foo:time]
0:[1521911720.600843;1521911720.600843;]
```

However, if I try to use the casting syntax "a la carte" on this one field instead of using `types.json`, the cast fails.

```
$ zq -t 'cut _write_ts | put foo=_write_ts:time | head 1' weird.ndjson.gz 
bad cast
#0:record[_write_ts:string]
0:[2018-03-24T17:15:20.600843Z;]
```

**Comment by alfred-landrum** [comment]
We have the ZQL function `Time.fromISO`, which does what I think you're expecting the cast to do here. Is the ask here specifically to make a cast do what that function does?

**Comment by philrz** [comment]
@alfred-landrum: Yes, it looks like that would do the trick here.

```
$ zq -t 'cut _write_ts | put foo=Time.fromISO(_write_ts) | head 1' weird.ndjson.gz
#0:record[_write_ts:string,foo:time]
0:[2018-03-24T17:15:20.600843Z;1521911720.600843;]
```

In a wider sense, perhaps it would help for me to restate how I (as a user) look at ZQL casting. Having a comprehensive `types.json` file is great if I have a large/complex data source I'm going to read many times. However, for quick one-offs where I've got arbitrary NDJSON I want to query with `zq`, casting is a very useful way to convert to the correct data type "a la carte". I've admittedly not done an exhaustive test of every single conversion possible via `types.json` to confirm they're all possible via casting, so there might be other corner cases that fail besides an ISO timestamp converting to `time`. But I encountered this one in the course of normal usage, hence the bug.

**Comment by philrz** [comment]
@alfred-landrum and I talked about this one some more today.

While the function approach works for the example above, I pointed out that it doesn't help if you've got diverse input formats with intent to store them all as `time` type. For example:

```
$ cat foo.ndjson 
{"_write_ts": "2018-03-24T17:15:20.600843Z"}
{"_write_ts": 1521911720.600843}

$ zq -t "put foo=Time.fromISO(_write_ts)" foo.ndjson
Time.fromISO: bad argument
#0:record[_write_ts:string,foo:time]
0:[2018-03-24T17:15:20.600843Z;1521911720.600843;]
#1:record[_write_ts:float64]
1:[1521911720.600843;]
```

Also, there's no equivalent function at the moment to convert strings-that-look-like-IP-addresses to the `ip` type. So whether `:type` syntax or functions are deemed the ideal way to go (or both?), we're inconsistent at the moment.

We're in agreement that users would benefit from some single operation that converts to a target type whenever there's an obvious way to do it for supported input formats. Whether that's done through the `:type` syntax that we're calling "casting" at the moment, or more flexible functions like creating a `Time.fromAny()`, seems TBD.

Also, @alfred-landrum is not a fan of the term "casting" for what we're doing today with the `:type` syntax. So if we do maintain/extend that syntax, we may be due to change the name.

**Comment by philrz** [comment]
I've noticed that "casting" also can't currently handle `:port` as a destination type. Rather than open a new issue, I'll just log it here in the event that someone picks up the wider task of reconciling all such differences as we discussed in a recent group meeting. This is with GA `zq` tagged `v0.22.0`:

```
$ echo '{"foo": 80}' | zq -t 'put foo=foo:port' -
parse error: 1:13 (12): no match found, expected: " ", "\f", "\t", "\u00a0", "\ufeff", "\v", "bool", "bstring", "byte", "duration", "float64", "int16", "int32", "int64", "ip", "net", "string", "time", "uint16", "uint32" or "uint64"
```

**Comment by philrz** [comment]
Verified in `zq` commit dcb0284.

Repeating the original repro step, the cast approach now works where it did not before. Printing the output as ZSON rather than we did with TZNG back in the day:

```
zq-sample-data/zeek-ndjson$ zq -version
Version: v0.29.0-130-gdcb02843

zq-sample-data/zeek-ndjson$ zq -z 'cut _write_ts | put foo=_write_ts:time | head 1' weird.ndjson.gz
{_write_ts:"2018-03-24T17:15:20.600843Z",foo:2018-03-24T17:15:20.600843Z}
```

Thanks @mccanne!
