### ISSUE TITLE
spilled records not cleaned up if zq is interrupted

### ISSUE THREAD

**Issue by mikesbrown** [brimsec/zq#970]
If `zq` spills to disk on a sort or group-by, the records in `TempDir("", "zq-sort-")` aren't cleaned up if zq is interrupted.

I was able to simulate this by doing something like `zq -t 'sort ts' zq-sample-data/zeek-default/*.log.gz` and hitting Ctrl+C once `/tmp/zq-sort-*` appeared.

**Comment by nwt** [comment]
Should be fixed by the combination of #1093 and #1099.

**Comment by philrz** [comment]
Verified in `zq` commit `8bdbdb0`.

The first attached video captures the repro as of `zq` commit `9310cd0` that came just before the change. We do a `watch -n1 'ls $TMPDIR | grep zq-sort'` while attempting a `zq -t "sort -r ts" *` on a massive data set. As you can see, the `zq-sort-*` directory appears when the spill-to-disk kicks in, and when I Control-C the `zq`, the `zq-sort-*` directory is left behind.

[Repro.zip](https://github.com/brimsec/zq/files/5076974/Repro.zip)

Then repeating the same in `zq` commit `8bdbdb0`, the `zq-sort-*` directory is cleaned up automatically when I Control-C my `zq`.

[Verify.zip](https://github.com/brimsec/zq/files/5076984/Verify.zip)

Thanks @nwt!
