### ISSUE TITLE
zar s3 system tests

### ISSUE THREAD

**Issue by mattnibs** [brimsec/zq#973]
Use minio and ztest to write a series of system tests for all the newly s3-ified zar commands.

**Comment by henridf** [comment]
Are we ok with adding minio to ztest now? I think it makes sense, but there had been opposition in the past.

**Comment by alfred-landrum** [comment]
I'm ok with it: we're using more ztest style tests, and we're increasingly going to focus on S3 backed archives, so it seems like a useful fit going forward. @mattnibs had brought it'd be useful if the test framework could make it easier to launch & teardown the minio service; I'd suggested we should wait until we have a few tests in place to see how that could work.
