### ISSUE TITLE
record type and field indexes in archive metadata

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#989]
When a type or field index (ie, a non-custom index) is created, we should record its existence in the archive's metadata file, and when a user issues a non-custom index search, we should use the entries in the metadata file to choose what index to use for lookup.

**Comment by philrz** [comment]
Verified in `zq` commit `314d783`. After adding the type & field indexes first shown in the [zar README](https://github.com/brimsec/zq/blob/master/cmd/zar/README.md), here's what the additional info in the archive metadata looks like:

```
...
$ cat zar.json | jq .
...
  "indexes": {
    "zdx-field-uri": {
      "type": "field",
      "path": "zdx-field-uri"
    },
    "zdx-type-ip": {
      "type": "type",
      "path": "zdx-type-ip"
    }
  }
...
```

Thanks @henridf!
