### ISSUE TITLE
zar index does not handle more than 5 "levels"

### ISSUE THREAD

**Issue by mikesbrown** [brimsec/zq#995]
I was trying to achieve zar index parity with our older, closed-source indexing, so I ran `zar index :bstring` on a large data set. After a few minutes, there was a panic with the text:
```
file:///mnt/brim-workspace/zar/20180324/1521931333.963907.zng: creating index file:///mnt/brim-workspace/zar/20180324/1521931333.963907.zng.zar/zdx-type-bstring
panic: something wrong

goroutine 1 [running]:
github.com/brimsec/zq/zdx.newWriter(0xc012f22150, 0xc00fcb1440, 0x4, 0x0, 0x0, 0x0, 0xc00fcb1447, 0x0, 0xc00fcb1447, 0x4b, ...)
        /home/mikeb/zq/zdx/writer.go:73 +0x714
```
I checked the code, and this isn't a bug per se, but a [level assertion](https://github.com/brimsec/zq/blob/588c08edce5101cb5e448732e41aaedd27a16cce/zdx/writer.go#L73). More than 5 "levels" aren't allowed.
```go
func newWriter(zctx *resolver.Context, path iosrc.URI, keyFields []string, framesize, level int, hdr *zng.Record) (*Writer, error) {
	if level > 5 {
		panic("something wrong")
	}
```
Given the following, I assume this is related to the number of distinct microindices per chunk.
```
-rw-rw-r-- 1 mikeb mikeb 654K Jul  9 22:36 /mnt/brim-workspace/zar/20180324/1521931333.963907.zng.zar/zdx-type-bstring.1.zng
-rw-rw-r-- 1 mikeb mikeb 519K Jul  9 22:36 /mnt/brim-workspace/zar/20180324/1521931333.963907.zng.zar/zdx-type-bstring.2.zng
-rw-rw-r-- 1 mikeb mikeb 390K Jul  9 22:36 /mnt/brim-workspace/zar/20180324/1521931333.963907.zng.zar/zdx-type-bstring.3.zng
-rw-rw-r-- 1 mikeb mikeb 260K Jul  9 22:36 /mnt/brim-workspace/zar/20180324/1521931333.963907.zng.zar/zdx-type-bstring.4.zng
-rw-rw-r-- 1 mikeb mikeb 130K Jul  9 22:36 /mnt/brim-workspace/zar/20180324/1521931333.963907.zng.zar/zdx-type-bstring.5.zng
-rw-rw-r-- 1 mikeb mikeb 805K Jul  9 22:36 /mnt/brim-workspace/zar/20180324/1521931333.963907.zng.zar/zdx-type-bstring.zng
```
If this is just a bumper to prevent an early bug that didn't imagine this meany zdx's per chunk, maybe it can just go away.

If this is a bumper that's intentional, guidance or other defaults ought to be adjusted for how to overcome the barrier.

**Comment by alfred-landrum** [comment]
That sequence of actions hit the 5-level panic because of the large number of items that were attempted to be indexed; not a surprise on `zar index :bstring`. We can likely change the panic to a real error return for now, as I don't think we've seen it for any case other than the expected "too many items".

**Comment by alfred-landrum** [comment]
@mccanne - over to you since you're working on the index layout. As I mention above, we could convert to the panic to a real error, perhaps with a message saying that the backstop for index levels was hit.

**Comment by mccanne** [comment]
This is read to go in branch zdx-limit-levels

https://github.com/brimsec/zq/compare/zdx-limit-levels

but it is based off PR #1110.  Once that is merged I will rebase and put up the PR.

**Comment by mccanne** [comment]
https://github.com/brimsec/repo/compare/zdx-limit-levels...single-file-zdx

**Comment by philrz** [comment]
Verified in `zar` commit `b7023d5`.

When this issue was originally opened, it was a bit lacking in detail on precise `zq` commit and data set that was used in the repro. I took my best guess by going back to `zar` commit `90dddfc` that came right before the fixes linked to this issue, and used the full 70 wrccdc Zeek log data set we normally test with. The repro was a success:

```
$ zq * | zar import -s 25MB -
$ zar index :bstring
file:///mnt/logs/20181113/1542143467.180468.zng: creating index file:///mnt/logs/20181113/1542143467.180468.zng.zar/zdx-type-bstring
file:///mnt/logs/20180325/1521939157.087629.zng: creating index file:///mnt/logs/20180325/1521939157.087629.zng.zar/zdx-type-bstring
...
file:///mnt/logs/20180324/1521932737.639456.zng: creating index file:///mnt/logs/20180324/1521932737.639456.zng.zar/zdx-type-bstring
panic: something wrong

goroutine 1 [running]:
github.com/brimsec/zq/zdx.newWriter(0xc009e340e0, 0xc0001064b0, 0x4, 0x0, 0x0, 0x0, 0xc0001064b7, 0x0, 0xc0001064b7, 0x3d, ...)
        /root/zq/zdx/writer.go:73 +0x721
...
```

I then repeated the same with commit `b7023d5` and, while it took hours to complete, it _did_ complete without crashing.

Thanks @mccanne!
